import type { NationalParkDestination } from './types'

export const nationalParks: NationalParkDestination[] = [
  // ─── Rocky Mountain Region (6) ───────────────────────────────────────────────

  {
    activityType: 'parks',
    name: 'Yellowstone National Park',
    slug: 'yellowstone',
    state: 'Wyoming',
    country: 'US',
    region: 'Rocky Mountain',
    tagline: 'The world\'s first national park, where geothermal wonders and abundant wildlife create an unparalleled wilderness experience.',
    description: 'Yellowstone spans nearly 2.2 million acres across Wyoming, Montana, and Idaho, sitting atop one of the world\'s largest active volcanic systems. The park contains more than half of the world\'s active geysers, including the iconic Old Faithful, alongside prismatic hot springs, thundering waterfalls, and the grand canyon of the Yellowstone River. Its vast wilderness supports thriving populations of grizzly bears, wolves, bison, and elk in one of the last intact temperate ecosystems on Earth.',
    lat: 44.428,
    lng: -110.5885,
    nearestAirport: 'Bozeman Yellowstone International Airport',
    airportCode: 'BZN',
    driveFromAirport: '1 hour 30 minutes',
    established: 1872,
    acreage: 2219791,
    annualVisitors: '4.86 million',
    entranceFee: '$35 per vehicle',
    numberOfTrails: 900,
    highestPoint: 'Eagle Peak, 11,358 ft',
    season: 'Year-round (some roads close in winter)',
    petFriendly: false,
    camping: true,
    wilderness: true,
    bestMonths: ['May', 'June', 'July', 'August', 'September'],
    highlights: [
      'Old Faithful Geyser erupting every 44-125 minutes',
      'Grand Prismatic Spring with its rainbow-colored bacterial mats',
      'Lamar Valley wildlife watching for wolves, bison, and grizzlies',
      'Grand Canyon of the Yellowstone and Lower Falls',
      'Mammoth Hot Springs travertine terraces',
      'Hayden Valley elk and bison herds at dawn',
    ],
    hotels: [
      {
        name: 'Old Faithful Inn',
        slug: 'old-faithful-inn',
        priceRange: '$$$',
        pricePerNight: '$350-550',
        distanceToSlopes: 'Inside park',
        skiInSkiOut: true,
        description: 'The iconic 1904 log-and-stone lodge sits just steps from Old Faithful Geyser. This National Historic Landmark features a soaring lobby with a massive stone fireplace and hand-crafted woodwork throughout.',
        amenities: ['Restaurant', 'Gift Shop', 'Historic Tours', 'Geyser Views'],
        bookingUrl: 'https://www.hotels.com/affiliate?landingPage=https%3A%2F%2Fwww.hotels.com%2Fho492649%2Fold-faithful-inn-inside-the-park-yellowstone-national-park-united-states-of-america%2F&camref=1110lFmx3&creativeref=1011l66481',
        lat: 44.4605,
        lng: -110.8281,
      },
      {
        name: 'Lake Yellowstone Hotel',
        slug: 'lake-yellowstone-hotel',
        priceRange: '$$$',
        pricePerNight: '$300-480',
        distanceToSlopes: 'Inside park',
        skiInSkiOut: true,
        description: 'The oldest operating hotel in Yellowstone, this elegant Colonial Revival building overlooks Yellowstone Lake. Guests enjoy fine dining and stunning sunset views over the largest high-altitude lake in North America.',
        amenities: ['Fine Dining', 'Lakefront Views', 'Gift Shop', 'Sun Room Lounge'],
        bookingUrl: 'https://www.hotels.com/affiliate?landingPage=https%3A%2F%2Fwww.hotels.com%2Fho492943%2Flake-hotel-and-cottages-inside-the-park-yellowstone-national-park-united-states-of-america%2F&camref=1110lFmx3&creativeref=1011l66481',
        lat: 44.5522,
        lng: -110.3967,
      },
      {
        name: 'Explorer Cabins at Yellowstone',
        slug: 'explorer-cabins-at-yellowstone',
        priceRange: '$$',
        pricePerNight: '$180-320',
        distanceToSlopes: '1 mile from West Entrance',
        skiInSkiOut: false,
        description: 'Modern cabin-style accommodations in the gateway town of West Yellowstone, offering comfortable rooms with a rustic mountain aesthetic and easy access to the park\'s west entrance.',
        amenities: ['Free Parking', 'Hot Tub', 'Free Wi-Fi', 'Pet Friendly Rooms'],
        bookingUrl: 'https://www.hotels.com/affiliate?landingPage=https%3A%2F%2Fwww.hotels.com%2Fho440781%2Fexplorer-cabins-at-yellowstone-west-yellowstone-united-states-of-america%2F&camref=1110lFmx3&creativeref=1011l66481',
        lat: 44.6621,
        lng: -111.0955,
      },
      {
        name: 'Yellowstone Valley Inn',
        slug: 'yellowstone-valley-inn',
        priceRange: '$',
        pricePerNight: '$110-190',
        distanceToSlopes: '25 miles from Northeast Entrance',
        skiInSkiOut: false,
        description: 'A family-run inn in the scenic Wapiti Valley near Yellowstone\'s east entrance, offering affordable rooms, a general store, and horseback riding excursions into the Absaroka Range.',
        amenities: ['Free Parking', 'General Store', 'Horseback Riding', 'RV Sites'],
        bookingUrl: 'https://www.hotels.com/affiliate?landingPage=https%3A%2F%2Fwww.hotels.com%2Fho231073%2Fyellowstone-valley-inn-wapiti-united-states-of-america%2F&camref=1110lFmx3&creativeref=1011l66481',
        lat: 44.4968,
        lng: -109.8632,
      },
    ],
  },

  {
    activityType: 'parks',
    name: 'Grand Teton National Park',
    slug: 'grand-teton',
    state: 'Wyoming',
    country: 'US',
    region: 'Rocky Mountain',
    tagline: 'A dramatic wall of jagged peaks rising abruptly from the valley floor, reflected in pristine alpine lakes.',
    description: 'Grand Teton National Park protects the youngest mountain range in the Rockies, with the iconic Teton Range soaring more than 7,000 feet above the sagebrush flats of Jackson Hole. The park encompasses pristine alpine lakes, old-growth forests, and the winding Snake River, providing habitat for moose, bears, and trumpeter swans. Its proximity to Yellowstone creates one of the greatest wildlife corridors in the lower 48 states.',
    lat: 43.7904,
    lng: -110.6818,
    nearestAirport: 'Jackson Hole Airport',
    airportCode: 'JAC',
    driveFromAirport: '15 minutes',
    established: 1929,
    acreage: 310044,
    annualVisitors: '3.89 million',
    entranceFee: '$35 per vehicle',
    numberOfTrails: 230,
    highestPoint: 'Grand Teton, 13,775 ft',
    season: 'Year-round (Teton Park Road closes in winter)',
    petFriendly: false,
    camping: true,
    wilderness: true,
    bestMonths: ['June', 'July', 'August', 'September'],
    highlights: [
      'Sunrise at Schwabacher Landing with Teton reflections',
      'Jenny Lake boat ride and Cascade Canyon hike',
      'Snake River scenic float trips for wildlife viewing',
      'Moose and elk watching at Oxbow Bend',
      'Climbing the Grand Teton summit via the Exum Ridge',
    ],
    hotels: [
      {
        name: 'Jackson Lake Lodge',
        slug: 'jackson-lake-lodge',
        priceRange: '$$$',
        pricePerNight: '$320-520',
        distanceToSlopes: 'Inside park',
        skiInSkiOut: true,
        description: 'A mid-century lodge perched above Willow Flats with floor-to-ceiling windows framing an uninterrupted panorama of the entire Teton Range and Jackson Lake. Moose frequently graze on the grounds.',
        amenities: ['Restaurant', 'Heated Pool', 'Horseback Riding', 'Wildlife Viewing'],
        bookingUrl: 'https://www.hotels.com/affiliate?landingPage=https%3A%2F%2Fwww.hotels.com%2Fho225063%2Fjackson-lake-lodge-moran-united-states-of-america%2F&camref=1110lFmx3&creativeref=1011l66481',
        lat: 43.8553,
        lng: -110.6405,
      },
      {
        name: 'Jenny Lake Lodge',
        slug: 'jenny-lake-lodge',
        priceRange: '$$$$',
        pricePerNight: '$700-1100',
        distanceToSlopes: 'Inside park',
        skiInSkiOut: true,
        description: 'An exclusive collection of rustic-elegant log cabins nestled among wildflower meadows at the base of the Tetons. Rates include gourmet breakfast and five-course dinner in the intimate dining room.',
        amenities: ['Fine Dining', 'Bicycle Rentals', 'Guided Hikes', 'Concierge'],
        bookingUrl: 'https://www.hotels.com/affiliate?landingPage=https%3A%2F%2Fwww.hotels.com%2Fho214121%2Fjenny-lake-lodge-moose-united-states-of-america%2F&camref=1110lFmx3&creativeref=1011l66481',
        lat: 43.753,
        lng: -110.7213,
      },
      {
        name: 'Snow King Resort',
        slug: 'snow-king-resort',
        priceRange: '$$',
        pricePerNight: '$200-380',
        distanceToSlopes: '8 miles from park entrance',
        skiInSkiOut: false,
        description: 'Located in the heart of Jackson, this full-service resort at the base of Snow King Mountain offers year-round recreation and serves as an excellent base for exploring Grand Teton and Yellowstone.',
        amenities: ['Spa', 'Pool', 'Restaurant', 'Free Wi-Fi', 'Fitness Center'],
        bookingUrl: 'https://www.hotels.com/affiliate?landingPage=https%3A%2F%2Fwww.hotels.com%2Fho222324%2Fsnow-king-resort-hotel-luxury-residences-jackson-united-states-of-america%2F&camref=1110lFmx3&creativeref=1011l66481',
        lat: 43.4779,
        lng: -110.7624,
      },
    ],
  },

  {
    activityType: 'parks',
    name: 'Glacier National Park',
    slug: 'glacier',
    state: 'Montana',
    country: 'US',
    region: 'Rocky Mountain',
    tagline: 'The Crown of the Continent, where ancient glaciers carved dramatic alpine landscapes along the Continental Divide.',
    description: 'Glacier National Park encompasses over a million acres of pristine wilderness along the spine of the Northern Rockies, featuring rugged peaks, turquoise lakes, and dense cedar forests. The legendary Going-to-the-Sun Road traverses the park over Logan Pass, offering one of the most spectacular drives in North America. The park\'s remaining glaciers, along with over 700 miles of trails, draw hikers seeking some of the most dramatic alpine scenery in the lower 48 states.',
    lat: 48.7596,
    lng: -113.787,
    nearestAirport: 'Glacier Park International Airport',
    airportCode: 'FCA',
    driveFromAirport: '30 minutes',
    established: 1910,
    acreage: 1013572,
    annualVisitors: '2.96 million',
    entranceFee: '$35 per vehicle',
    numberOfTrails: 734,
    highestPoint: 'Mount Cleveland, 10,479 ft',
    season: 'Year-round (Going-to-the-Sun Road open June-October)',
    petFriendly: false,
    camping: true,
    wilderness: true,
    bestMonths: ['July', 'August', 'September'],
    highlights: [
      'Driving the Going-to-the-Sun Road across Logan Pass',
      'Hiking the Highline Trail along the Continental Divide',
      'Grinnell Glacier hike past turquoise alpine lakes',
      'Kayaking on crystal-clear Lake McDonald at sunset',
      'Spotting mountain goats and bighorn sheep near Hidden Lake',
    ],
    hotels: [
      {
        name: 'Many Glacier Hotel',
        slug: 'many-glacier-hotel',
        priceRange: '$$$',
        pricePerNight: '$280-450',
        distanceToSlopes: 'Inside park',
        skiInSkiOut: true,
        description: 'A historic Swiss-style chalet built in 1915, set on the shores of Swiftcurrent Lake with towering peaks rising on all sides. The Many Glacier valley is widely considered the park\'s most scenic area and best for wildlife.',
        amenities: ['Restaurant', 'Guided Boat Tours', 'Gift Shop', 'Lakefront Views'],
        bookingUrl: 'https://www.hotels.com/affiliate?landingPage=https%3A%2F%2Fwww.hotels.com%2Fho492967%2Fmany-glacier-hotel-inside-the-park-babb-united-states-of-america%2F&camref=1110lFmx3&creativeref=1011l66481',
        lat: 48.7968,
        lng: -113.6557,
      },
      {
        name: 'Lake McDonald Lodge',
        slug: 'lake-mcdonald-lodge',
        priceRange: '$$',
        pricePerNight: '$200-340',
        distanceToSlopes: 'Inside park',
        skiInSkiOut: true,
        description: 'A charming 1913 Swiss chalet on the shores of the park\'s largest lake, featuring a lobby filled with animal trophies and Native American artifacts. A classic base for exploring the western side of Glacier.',
        amenities: ['Restaurant', 'Gift Shop', 'Boat Rentals', 'Red Bus Tours'],
        bookingUrl: 'https://www.hotels.com/affiliate?landingPage=https%3A%2F%2Fwww.hotels.com%2Fho492838%2Flake-mcdonald-lodge-inside-the-park-west-glacier-united-states-of-america%2F&camref=1110lFmx3&creativeref=1011l66481',
        lat: 48.6169,
        lng: -113.878,
      },
      {
        name: 'Glacier Park Lodge',
        slug: 'glacier-park-lodge',
        priceRange: '$$',
        pricePerNight: '$190-310',
        distanceToSlopes: '1 mile from East Entrance',
        skiInSkiOut: false,
        description: 'Built by the Great Northern Railway in 1913, this grand lodge at the park\'s east entrance features a lobby supported by massive Douglas fir timbers and beautiful manicured gardens with a nine-hole golf course.',
        amenities: ['Restaurant', 'Pool', 'Golf Course', 'Gift Shop', 'Gardens'],
        bookingUrl: 'https://www.hotels.com/affiliate?landingPage=https%3A%2F%2Fwww.hotels.com%2Fho485512%2Fglacier-park-lodge-east-glacier-park-united-states-of-america%2F&camref=1110lFmx3&creativeref=1011l66481',
        lat: 48.4462,
        lng: -113.2131,
      },
      {
        name: 'Meadow Lake Resort',
        slug: 'meadow-lake-resort',
        priceRange: '$',
        pricePerNight: '$130-220',
        distanceToSlopes: '15 miles from West Entrance',
        skiInSkiOut: false,
        description: 'A relaxed resort in Columbia Falls with spacious rooms and full condos, offering an affordable gateway to Glacier with an on-site golf course, waterpark, and spa.',
        amenities: ['Pool', 'Waterpark', 'Golf', 'Spa', 'Free Parking'],
        bookingUrl: 'https://www.hotels.com/affiliate?landingPage=https%3A%2F%2Fwww.hotels.com%2Fho374443%2Fmeadow-lake-resort-condos-columbia-falls-united-states-of-america%2F&camref=1110lFmx3&creativeref=1011l66481',
        lat: 48.364,
        lng: -114.173,
      },
    ],
  },

  {
    activityType: 'parks',
    name: 'Rocky Mountain National Park',
    slug: 'rocky-mountain',
    state: 'Colorado',
    country: 'US',
    region: 'Rocky Mountain',
    tagline: 'Where alpine tundra meets towering peaks and pristine mountain lakes in the heart of the Colorado Rockies.',
    description: 'Rocky Mountain National Park straddles the Continental Divide in north-central Colorado, protecting 265,807 acres of alpine tundra, subalpine forests, and montane meadows. Trail Ridge Road climbs above 12,000 feet, making it one of the highest paved roads in the United States. The park\'s 77 peaks above 12,000 feet, 150 lakes, and abundant elk herds make it one of the most accessible high-alpine experiences in North America.',
    lat: 40.3428,
    lng: -105.6836,
    nearestAirport: 'Denver International Airport',
    airportCode: 'DEN',
    driveFromAirport: '2 hours',
    established: 1915,
    acreage: 265807,
    annualVisitors: '4.35 million',
    entranceFee: '$30 per vehicle',
    numberOfTrails: 355,
    highestPoint: 'Longs Peak, 14,259 ft',
    season: 'Year-round (Trail Ridge Road closes late October-May)',
    petFriendly: false,
    camping: true,
    wilderness: true,
    bestMonths: ['June', 'July', 'August', 'September', 'October'],
    highlights: [
      'Driving Trail Ridge Road through alpine tundra above treeline',
      'Summiting Longs Peak via the Keyhole Route',
      'Elk bugling during the fall rut in Horseshoe Park',
      'Hiking to Sky Pond through the Loch Vale',
      'Sunrise at Bear Lake with Hallett Peak reflections',
      'Snowshoeing to Emerald Lake in winter',
    ],
    hotels: [
      {
        name: 'Stanley Hotel',
        slug: 'stanley-hotel',
        priceRange: '$$$',
        pricePerNight: '$300-500',
        distanceToSlopes: '5 miles from Beaver Meadows Entrance',
        skiInSkiOut: false,
        description: 'The legendary 1909 Georgian Colonial hotel that inspired Stephen King\'s "The Shining," perched on a hillside overlooking Estes Park with panoramic views of the Continental Divide and Longs Peak.',
        amenities: ['Restaurant', 'Spa', 'Ghost Tours', 'Concert Hall', 'Free Wi-Fi'],
        bookingUrl: 'https://www.hotels.com/affiliate?landingPage=https%3A%2F%2Fwww.hotels.com%2Fho115926%2Fstanley-hotel-estes-park-united-states-of-america%2F&camref=1110lFmx3&creativeref=1011l66481',
        lat: 40.3832,
        lng: -105.5173,
      },
      {
        name: 'Ridgeline Hotel Estes Park',
        slug: 'ridgeline-hotel-estes-park',
        priceRange: '$$',
        pricePerNight: '$180-310',
        distanceToSlopes: '3 miles from Fall River Entrance',
        skiInSkiOut: false,
        description: 'A modern hotel nestled along the Fall River on the edge of Estes Park, offering contemporary rooms with mountain views, an indoor pool, and direct access to the park\'s Fall River entrance.',
        amenities: ['Pool', 'Hot Tub', 'Restaurant', 'Free Parking', 'Fitness Center'],
        bookingUrl: 'https://www.hotels.com/affiliate?landingPage=https%3A%2F%2Fwww.hotels.com%2Fho107942%2Fridgeline-hotel-estes-park-estes-park-united-states-of-america%2F&camref=1110lFmx3&creativeref=1011l66481',
        lat: 40.3751,
        lng: -105.5336,
      },
      {
        name: 'YMCA of the Rockies',
        slug: 'ymca-of-the-rockies',
        priceRange: '$',
        pricePerNight: '$100-180',
        distanceToSlopes: '2 miles from park boundary',
        skiInSkiOut: false,
        description: 'A sprawling family retreat center on 860 acres bordering the national park, offering lodge rooms and cabins with a wide range of outdoor programs and activities for all ages.',
        amenities: ['Pool', 'Hiking Trails', 'Horseback Riding', 'Mini Golf', 'Craft Center'],
        bookingUrl: 'https://www.hotels.com/affiliate?landingPage=https%3A%2F%2Fwww.hotels.com%2Fho2103996832%2Fymca-of-the-rockies-estes-park-estes-park-united-states-of-america%2F&camref=1110lFmx3&creativeref=1011l66481',
        lat: 40.3603,
        lng: -105.5614,
      },
    ],
  },

  {
    activityType: 'parks',
    name: 'Grand Canyon National Park',
    slug: 'grand-canyon',
    state: 'Arizona',
    country: 'US',
    region: 'Rocky Mountain',
    tagline: 'A mile-deep chasm carved by the Colorado River, revealing nearly two billion years of Earth\'s geological history.',
    description: 'Grand Canyon National Park protects 277 miles of the Colorado River and the immense canyon it has carved through layer upon layer of colorful rock. The canyon stretches up to 18 miles wide and over a mile deep, exposing rocks dating back 1.8 billion years. The South Rim offers the most accessible viewpoints and visitor services, while the remote North Rim stands 1,000 feet higher and receives a fraction of the visitors.',
    lat: 36.1069,
    lng: -112.1129,
    nearestAirport: 'Flagstaff Pulliam Airport',
    airportCode: 'FLG',
    driveFromAirport: '1 hour 20 minutes',
    established: 1919,
    acreage: 1218375,
    annualVisitors: '6.38 million',
    entranceFee: '$35 per vehicle',
    numberOfTrails: 91,
    highestPoint: 'Point Imperial (North Rim), 8,803 ft',
    season: 'South Rim year-round; North Rim May-October',
    petFriendly: false,
    camping: true,
    wilderness: true,
    bestMonths: ['March', 'April', 'May', 'September', 'October', 'November'],
    highlights: [
      'Sunrise from Mather Point on the South Rim',
      'Hiking Bright Angel Trail to Indian Garden or Phantom Ranch',
      'Rafting the Colorado River through the Inner Gorge',
      'Sunset from Hopi Point along the Rim Trail',
      'Backpacking rim-to-rim via the North Kaibab Trail',
      'Stargazing in an International Dark Sky Park',
    ],
    hotels: [
      {
        name: 'El Tovar Hotel',
        slug: 'el-tovar-hotel',
        priceRange: '$$$$',
        pricePerNight: '$400-650',
        distanceToSlopes: 'Inside park',
        skiInSkiOut: true,
        description: 'The crown jewel of Grand Canyon lodging since 1905, this National Historic Landmark sits just 20 feet from the South Rim. Designed in a rustic Arts and Crafts style, it offers the finest dining and most sought-after views in the park.',
        amenities: ['Fine Dining', 'Concierge', 'Gift Shop', 'Canyon Rim Access'],
        bookingUrl: 'https://www.hotels.com/affiliate?landingPage=https%3A%2F%2Fwww.hotels.com%2Fho492833%2Fel-tovar-inside-the-park-grand-canyon-united-states-of-america%2F&camref=1110lFmx3&creativeref=1011l66481',
        lat: 36.0544,
        lng: -112.1401,
      },
      {
        name: 'Bright Angel Lodge',
        slug: 'bright-angel-lodge',
        priceRange: '$$',
        pricePerNight: '$120-280',
        distanceToSlopes: 'Inside park',
        skiInSkiOut: true,
        description: 'A historic Mary Colter-designed lodge on the canyon rim, offering a range of rooms from rustic cabins to rim-side suites. The lodge sits at the trailhead of the popular Bright Angel Trail.',
        amenities: ['Restaurant', 'Cocktail Lounge', 'Gift Shop', 'Trail Access'],
        bookingUrl: 'https://www.hotels.com/affiliate?landingPage=https%3A%2F%2Fwww.hotels.com%2Fho492935%2Fbright-angel-lodge-inside-the-park-grand-canyon-united-states-of-america%2F&camref=1110lFmx3&creativeref=1011l66481',
        lat: 36.0568,
        lng: -112.1437,
      },
      {
        name: 'Grand Canyon Lodge North Rim',
        slug: 'grand-canyon-lodge-north-rim',
        priceRange: '$$',
        pricePerNight: '$180-300',
        distanceToSlopes: 'Inside park',
        skiInSkiOut: true,
        description: 'The only lodging on the North Rim, this 1937 limestone-and-timber lodge perches on the canyon edge at 8,200 feet. The sun room offers floor-to-ceiling views into the canyon\'s depths.',
        amenities: ['Restaurant', 'Saloon', 'Gift Shop', 'Canyon Views', 'Guided Tours'],
        bookingUrl: 'https://www.hotels.com/affiliate?landingPage=https%3A%2F%2Fwww.hotels.com%2Fho3423653408%2Fgrand-canyon-lodge%2F&camref=1110lFmx3&creativeref=1011l66481',
        lat: 36.1984,
        lng: -112.0569,
      },
      {
        name: 'Red Feather Lodge',
        slug: 'red-feather-lodge',
        priceRange: '$',
        pricePerNight: '$90-170',
        distanceToSlopes: '1 mile from South Entrance',
        skiInSkiOut: false,
        description: 'A comfortable and affordable hotel in the gateway village of Tusayan, just one mile from the park\'s south entrance. A solid budget-friendly base with modern amenities and easy shuttle access.',
        amenities: ['Pool', 'Hot Tub', 'Free Parking', 'Free Wi-Fi', 'Fitness Center'],
        bookingUrl: 'https://www.hotels.com/affiliate?landingPage=https%3A%2F%2Fwww.hotels.com%2Fho105473%2Fred-feather-lodge-grand-canyon-united-states-of-america%2F&camref=1110lFmx3&creativeref=1011l66481',
        lat: 35.9745,
        lng: -112.1369,
      },
    ],
  },

  {
    activityType: 'parks',
    name: 'Arches National Park',
    slug: 'arches',
    state: 'Utah',
    country: 'US',
    region: 'Rocky Mountain',
    tagline: 'Over 2,000 natural stone arches sculpted by erosion into a surreal red-rock landscape.',
    description: 'Arches National Park contains the densest concentration of natural stone arches in the world, with over 2,000 cataloged arches set among towering red sandstone fins, pinnacles, and balanced rocks. The park\'s 76,679 acres near Moab showcase millions of years of erosion at work on the Entrada Sandstone formation. From the iconic Delicate Arch to the soaring spans of Landscape Arch, the park offers an otherworldly landscape that transforms with the light of each passing hour.',
    lat: 38.7331,
    lng: -109.5925,
    nearestAirport: 'Grand Junction Regional Airport',
    airportCode: 'GJT',
    driveFromAirport: '1 hour 50 minutes',
    established: 1971,
    acreage: 76679,
    annualVisitors: '1.81 million',
    entranceFee: '$30 per vehicle',
    numberOfTrails: 29,
    highestPoint: 'Elephant Butte, 5,653 ft',
    season: 'Year-round',
    petFriendly: false,
    camping: true,
    wilderness: false,
    bestMonths: ['March', 'April', 'May', 'September', 'October'],
    highlights: [
      'Sunset hike to Delicate Arch, Utah\'s most iconic landmark',
      'Landscape Arch, the longest natural arch in North America at 306 feet',
      'Walking through the Fiery Furnace with a ranger guide',
      'Balanced Rock silhouetted against the La Sal Mountains',
      'The Windows Section loop for easy access to massive arches',
      'Dark sky stargazing with the Milky Way framing the arches',
    ],
    hotels: [
      {
        name: 'Red Cliffs Lodge',
        slug: 'red-cliffs-lodge',
        priceRange: '$$$',
        pricePerNight: '$280-420',
        distanceToSlopes: '14 miles from park entrance',
        skiInSkiOut: false,
        description: 'A riverside ranch resort set along the Colorado River on Highway 128, offering spacious suites with private patios facing the river and towering red cliffs. Home to the Moab Museum of Film and Western Heritage.',
        amenities: ['Restaurant', 'Pool', 'Horseback Riding', 'Winery', 'River Access'],
        bookingUrl: 'https://www.hotels.com/affiliate?landingPage=https%3A%2F%2Fwww.hotels.com%2Fho637097%2Fred-cliffs-lodge-moab-united-states-of-america%2F&camref=1110lFmx3&creativeref=1011l66481',
        lat: 38.6137,
        lng: -109.3982,
      },
      {
        name: 'Hoodoo Moab',
        slug: 'hoodoo-moab',
        priceRange: '$$',
        pricePerNight: '$180-320',
        distanceToSlopes: '5 miles from park entrance',
        skiInSkiOut: false,
        description: 'A stylish boutique hotel in downtown Moab with a curated art collection, rooftop pool, and modern desert-inspired design. Walking distance to Moab\'s best restaurants and outfitters.',
        amenities: ['Rooftop Pool', 'Restaurant', 'Bike Storage', 'Free Wi-Fi', 'Concierge'],
        bookingUrl: 'https://www.hotels.com/affiliate?landingPage=https%3A%2F%2Fwww.hotels.com%2Fho1068967008%2Fhoodoo-moab-curio-collection-by-hilton-moab-united-states-of-america%2F&camref=1110lFmx3&creativeref=1011l66481',
        lat: 38.5733,
        lng: -109.5498,
      },
      {
        name: 'Aarchway Inn',
        slug: 'aarchway-inn',
        priceRange: '$',
        pricePerNight: '$100-180',
        distanceToSlopes: '2 miles from park entrance',
        skiInSkiOut: false,
        description: 'A well-maintained motel on the north end of Moab, offering clean and comfortable rooms with easy access to both Arches and Canyonlands national parks. An excellent budget option for adventure travelers.',
        amenities: ['Pool', 'Hot Tub', 'Free Parking', 'Free Wi-Fi', 'BBQ Area'],
        bookingUrl: 'https://www.hotels.com/affiliate?landingPage=https%3A%2F%2Fwww.hotels.com%2Fho538722%2Faarchway-inn-moab-united-states-of-america%2F&camref=1110lFmx3&creativeref=1011l66481',
        lat: 38.5934,
        lng: -109.5511,
      },
    ],
  },

  // ─── Southwest Region (5) ────────────────────────────────────────────────────

  {
    activityType: 'parks',
    name: 'Zion National Park',
    slug: 'zion',
    state: 'Utah',
    country: 'US',
    region: 'Southwest',
    tagline: 'Towering red cliffs and narrow slot canyons carved by the Virgin River through the heart of the Colorado Plateau.',
    description: 'Zion National Park features some of the most dramatic canyon scenery on Earth, with massive sandstone cliffs rising 2,000 feet above the Virgin River. The park\'s 229 square miles encompass deep canyons, hanging gardens, emerald pools, and the famous Narrows, where hikers wade through the river between thousand-foot walls. Angels Landing offers one of America\'s most thrilling ridge walks, with chain-assisted scrambles along knife-edge ridges.',
    lat: 37.2982,
    lng: -113.0263,
    nearestAirport: 'St. George Regional Airport',
    airportCode: 'SGU',
    driveFromAirport: '1 hour',
    established: 1919,
    acreage: 147242,
    annualVisitors: '4.69 million',
    entranceFee: '$35 per vehicle',
    numberOfTrails: 90,
    highestPoint: 'Horse Ranch Mountain, 8,726 ft',
    season: 'Year-round',
    petFriendly: false,
    camping: true,
    wilderness: true,
    bestMonths: ['March', 'April', 'May', 'September', 'October', 'November'],
    highlights: [
      'Hiking Angels Landing via Walter\'s Wiggles and the chain section',
      'Wading through The Narrows in the Virgin River slot canyon',
      'Emerald Pools trail to hanging gardens and waterfalls',
      'Canyoneering through the Subway slot canyon',
      'Canyon Overlook Trail for panoramic views of Zion Canyon',
      'Observation Point for the highest vantage over the canyon',
    ],
    hotels: [
      {
        name: 'Zion Lodge',
        slug: 'zion-lodge',
        priceRange: '$$$',
        pricePerNight: '$250-400',
        distanceToSlopes: 'Inside park',
        skiInSkiOut: true,
        description: 'The only lodging inside Zion Canyon, this historic lodge sits beneath towering sandstone walls near the Grotto trailhead. Cabin and suite options offer a rare chance to stay within the park after the shuttle stops running.',
        amenities: ['Restaurant', 'Gift Shop', 'Shuttle Access', 'Trail Access'],
        bookingUrl: 'https://www.hotels.com/affiliate?landingPage=https%3A%2F%2Fwww.hotels.com%2Fho492899%2Fzion-lodge-inside-the-park-springdale-united-states-of-america%2F&camref=1110lFmx3&creativeref=1011l66481',
        lat: 37.2502,
        lng: -112.9571,
      },
      {
        name: 'SpringHill Suites by Marriott Springdale',
        slug: 'springhill-suites-springdale',
        priceRange: '$$',
        pricePerNight: '$200-350',
        distanceToSlopes: '0.5 miles from South Entrance',
        skiInSkiOut: false,
        description: 'A modern all-suite hotel at the doorstep of Zion\'s south entrance in Springdale, offering spacious rooms with kitchenettes and a rooftop terrace with views of the Watchman and the Towers of the Virgin.',
        amenities: ['Pool', 'Hot Tub', 'Free Breakfast', 'Free Wi-Fi', 'Shuttle Stop'],
        bookingUrl: 'https://www.hotels.com/affiliate?landingPage=https%3A%2F%2Fwww.hotels.com%2Fho524158272%2Fspringhill-suites-by-marriott-springdale-zion-national-park-springdale-united-states-of-america%2F&camref=1110lFmx3&creativeref=1011l66481',
        lat: 37.1889,
        lng: -112.9986,
      },
      {
        name: 'Cable Mountain Lodge',
        slug: 'cable-mountain-lodge',
        priceRange: '$$',
        pricePerNight: '$190-330',
        distanceToSlopes: '0.3 miles from South Entrance',
        skiInSkiOut: false,
        description: 'A boutique lodge in Springdale offering well-appointed rooms and suites with private balconies overlooking the Virgin River and Zion\'s canyon walls. Steps from the park shuttle and Springdale dining.',
        amenities: ['Pool', 'Hot Tub', 'Kitchenettes', 'Free Parking', 'River Views'],
        bookingUrl: 'https://www.hotels.com/affiliate?landingPage=https%3A%2F%2Fwww.hotels.com%2Fho426967%2Fcable-mountain-lodge-springdale-united-states-of-america%2F&camref=1110lFmx3&creativeref=1011l66481',
        lat: 37.1912,
        lng: -112.9982,
      },
      {
        name: 'Bumbleberry Inn',
        slug: 'bumbleberry-inn',
        priceRange: '$',
        pricePerNight: '$100-190',
        distanceToSlopes: '1 mile from South Entrance',
        skiInSkiOut: false,
        description: 'A charming family-owned inn in the heart of Springdale, known for its bumbleberry pie and warm hospitality. Clean, comfortable rooms at a great value with mountain views and easy shuttle access.',
        amenities: ['Free Parking', 'Gift Shop', 'Free Wi-Fi', 'Shuttle Access'],
        bookingUrl: 'https://www.hotels.com/affiliate?landingPage=https%3A%2F%2Fwww.hotels.com%2Fho443337%2Fbumbleberry-inn-springdale-united-states-of-america%2F&camref=1110lFmx3&creativeref=1011l66481',
        lat: 37.1851,
        lng: -112.9989,
      },
    ],
  },

  {
    activityType: 'parks',
    name: 'Bryce Canyon National Park',
    slug: 'bryce-canyon',
    state: 'Utah',
    country: 'US',
    region: 'Southwest',
    tagline: 'An amphitheater of thousands of crimson hoodoos standing like a silent stone army along the Paunsaugunt Plateau.',
    description: 'Bryce Canyon National Park is renowned for its otherworldly collection of hoodoos -- tall, thin rock spires formed by frost weathering and stream erosion. The park\'s series of natural amphitheaters carved into the eastern edge of the Paunsaugunt Plateau display some of the most vivid and varied color combinations found in any landscape on Earth. At elevations between 8,000 and 9,000 feet, Bryce offers exceptionally clear air and some of the darkest night skies in North America.',
    lat: 37.593,
    lng: -112.1871,
    nearestAirport: 'St. George Regional Airport',
    airportCode: 'SGU',
    driveFromAirport: '2 hours 30 minutes',
    established: 1928,
    acreage: 35835,
    annualVisitors: '2.41 million',
    entranceFee: '$35 per vehicle',
    numberOfTrails: 50,
    highestPoint: 'Rainbow Point, 9,115 ft',
    season: 'Year-round',
    petFriendly: false,
    camping: true,
    wilderness: false,
    bestMonths: ['May', 'June', 'July', 'August', 'September'],
    highlights: [
      'Sunrise at Bryce Amphitheater watching hoodoos glow orange and gold',
      'Hiking the Navajo Loop and Queen\'s Garden combination trail',
      'Stargazing in one of the darkest skies in North America',
      'Snowshoeing among snow-capped hoodoos in winter',
      'The Wall Street narrows section with towering Douglas firs',
    ],
    hotels: [
      {
        name: 'The Lodge at Bryce Canyon',
        slug: 'lodge-at-bryce-canyon',
        priceRange: '$$$',
        pricePerNight: '$240-380',
        distanceToSlopes: 'Inside park',
        skiInSkiOut: true,
        description: 'A 1925 National Historic Landmark lodge set among ponderosa pines on the canyon rim, offering motel rooms, cabins, and suites with direct access to the Rim Trail and Sunset Point.',
        amenities: ['Restaurant', 'Gift Shop', 'Trail Access', 'Horseback Riding'],
        bookingUrl: 'https://www.hotels.com/affiliate?landingPage=https%3A%2F%2Fwww.hotels.com%2Fho3423684192%2F&camref=1110lFmx3&creativeref=1011l66481',
        lat: 37.6282,
        lng: -112.1662,
      },
      {
        name: 'Best Western Plus Bryce Canyon Grand Hotel',
        slug: 'best-western-bryce-canyon-grand',
        priceRange: '$$',
        pricePerNight: '$170-280',
        distanceToSlopes: '3 miles from park entrance',
        skiInSkiOut: false,
        description: 'A well-appointed hotel just outside the park entrance in Bryce Canyon City, offering spacious rooms, an indoor pool and hot tub, and easy access to the park shuttle.',
        amenities: ['Pool', 'Hot Tub', 'Free Breakfast', 'Free Parking', 'Fitness Center'],
        bookingUrl: 'https://www.hotels.com/affiliate?landingPage=https%3A%2F%2Fwww.hotels.com%2Fho311405%2Fbest-western-plus-bryce-canyon-grand-hotel-bryce-canyon-united-states-of-america%2F&camref=1110lFmx3&creativeref=1011l66481',
        lat: 37.6694,
        lng: -112.1527,
      },
      {
        name: 'Bryce Canyon Pines',
        slug: 'bryce-canyon-pines',
        priceRange: '$',
        pricePerNight: '$90-160',
        distanceToSlopes: '6 miles from park entrance',
        skiInSkiOut: false,
        description: 'A cozy family-operated motel and restaurant along Highway 12, known for its homemade pie and warm country hospitality. A simple and affordable base for exploring Bryce, Red Canyon, and Kodachrome Basin.',
        amenities: ['Restaurant', 'Pool', 'Horseback Riding', 'Free Parking'],
        bookingUrl: 'https://www.hotels.com/affiliate?landingPage=https%3A%2F%2Fwww.hotels.com%2Fho1568623776%2Fbryce-canyon-pines-bryce-canyon-united-states-of-america%2F&camref=1110lFmx3&creativeref=1011l66481',
        lat: 37.6908,
        lng: -112.1832,
      },
    ],
  },

  {
    activityType: 'parks',
    name: 'Canyonlands National Park',
    slug: 'canyonlands',
    state: 'Utah',
    country: 'US',
    region: 'Southwest',
    tagline: 'A wilderness of countless canyons and fantastically formed buttes carved by the Colorado and Green rivers.',
    description: 'Canyonlands is Utah\'s largest national park, divided into four distinct districts by the Colorado and Green rivers. The Island in the Sky mesa offers sweeping panoramas from 1,000 feet above the river, the Needles district features colorful sandstone spires and archaeological sites, and the remote Maze is considered the most inaccessible district in the national park system. The rivers\' confluence creates a vast labyrinth of canyons stretching to the horizon.',
    lat: 38.3269,
    lng: -109.8783,
    nearestAirport: 'Grand Junction Regional Airport',
    airportCode: 'GJT',
    driveFromAirport: '2 hours',
    established: 1964,
    acreage: 337598,
    annualVisitors: '911,594',
    entranceFee: '$30 per vehicle',
    numberOfTrails: 86,
    highestPoint: 'Cathedral Point, 7,120 ft',
    season: 'Year-round',
    petFriendly: false,
    camping: true,
    wilderness: true,
    bestMonths: ['March', 'April', 'May', 'September', 'October'],
    highlights: [
      'Grand View Point Overlook for a 100-mile panorama',
      'Mesa Arch at sunrise framing the La Sal Mountains',
      'Mountain biking the White Rim Road over 3-4 days',
      'Hiking the Chesler Park Loop through the Needles',
      'Confluence Overlook where the Colorado and Green rivers meet',
      'Four-wheel driving through the remote Maze District',
    ],
    hotels: [
      {
        name: 'Sorrel River Ranch Resort',
        slug: 'sorrel-river-ranch-resort',
        priceRange: '$$$$',
        pricePerNight: '$450-750',
        distanceToSlopes: '25 miles from Island in the Sky entrance',
        skiInSkiOut: false,
        description: 'A luxury riverside ranch resort along the Colorado River surrounded by towering red rock mesas. Full-service spa, horseback riding, and gourmet dining make it the premier lodging near Canyonlands.',
        amenities: ['Spa', 'Restaurant', 'Horseback Riding', 'Pool', 'River Access'],
        bookingUrl: 'https://www.hotels.com/affiliate?landingPage=https%3A%2F%2Fwww.hotels.com%2Fho493643%2Fsorrel-river-ranch-resort-moab-united-states-of-america%2F&camref=1110lFmx3&creativeref=1011l66481',
        lat: 38.6223,
        lng: -109.4192,
      },
      {
        name: 'Gonzo Inn',
        slug: 'gonzo-inn',
        priceRange: '$$',
        pricePerNight: '$170-290',
        distanceToSlopes: '32 miles from Island in the Sky entrance',
        skiInSkiOut: false,
        description: 'A retro-chic boutique hotel in downtown Moab with a vibrant mid-century modern aesthetic, courtyard pool, and art-filled common areas. Named as a nod to the adventurous spirit of Moab.',
        amenities: ['Pool', 'Hot Tub', 'Free Parking', 'Free Wi-Fi', 'Bike Storage'],
        bookingUrl: 'https://www.hotels.com/affiliate?landingPage=https%3A%2F%2Fwww.hotels.com%2Fho532208%2Fthe-gonzo-inn-moab-united-states-of-america%2F&camref=1110lFmx3&creativeref=1011l66481',
        lat: 38.5722,
        lng: -109.5508,
      },
      {
        name: 'Moab Valley Inn',
        slug: 'moab-valley-inn',
        priceRange: '$',
        pricePerNight: '$90-170',
        distanceToSlopes: '30 miles from Island in the Sky entrance',
        skiInSkiOut: false,
        description: 'A well-maintained hotel on Moab\'s main street offering comfortable rooms, outdoor pool, and a convenient location near restaurants and outfitters for Canyonlands and Arches adventures.',
        amenities: ['Pool', 'Free Parking', 'Free Wi-Fi', 'Guest Laundry'],
        bookingUrl: 'https://www.hotels.com/affiliate?landingPage=https%3A%2F%2Fwww.hotels.com%2Fho545221%2Fmoab-valley-inn-moab-united-states-of-america%2F&camref=1110lFmx3&creativeref=1011l66481',
        lat: 38.5745,
        lng: -109.5495,
      },
    ],
  },

  {
    activityType: 'parks',
    name: 'Joshua Tree National Park',
    slug: 'joshua-tree',
    state: 'California',
    country: 'US',
    region: 'Southwest',
    tagline: 'Where two deserts converge beneath twisted Joshua trees and giant boulder piles under vast starlit skies.',
    description: 'Joshua Tree National Park lies at the ecological crossroads of the Mojave and Colorado deserts, creating a surreal landscape where spiky Joshua trees stand sentinel among enormous granite boulder formations. The park\'s 790,636 acres offer world-class rock climbing on over 8,000 routes, stark desert gardens, old mining ruins, and some of the clearest night skies in Southern California. The park\'s proximity to Palm Springs and Los Angeles makes it one of the most accessible desert wilderness areas in the West.',
    lat: 33.8734,
    lng: -115.901,
    nearestAirport: 'Palm Springs International Airport',
    airportCode: 'PSP',
    driveFromAirport: '45 minutes',
    established: 1994,
    acreage: 790636,
    annualVisitors: '3.02 million',
    entranceFee: '$30 per vehicle',
    numberOfTrails: 52,
    highestPoint: 'Quail Mountain, 5,814 ft',
    season: 'Year-round (best to avoid summer heat)',
    petFriendly: false,
    camping: true,
    wilderness: true,
    bestMonths: ['October', 'November', 'December', 'January', 'February', 'March'],
    highlights: [
      'Rock climbing in the Wonderland of Rocks and Hidden Valley',
      'Sunset at Keys View overlooking the Coachella Valley and Salton Sea',
      'Hiking the 49 Palms Oasis trail to a desert fan palm oasis',
      'Cholla Cactus Garden glowing golden at sunset',
      'Stargazing as an International Dark Sky Park',
      'Exploring the historic Keys Ranch on a ranger-guided tour',
    ],
    hotels: [
      {
        name: 'High Desert Motel',
        slug: 'high-desert-motel',
        priceRange: '$$',
        pricePerNight: '$160-280',
        distanceToSlopes: '5 miles from West Entrance',
        skiInSkiOut: false,
        description: 'A clean, comfortable motel in Joshua Tree village, just minutes from the park\'s West Entrance. Simple rooms with desert views and easy access to local restaurants.',
        amenities: ['Pool', 'Free Parking', 'Courtyard', 'Free Wi-Fi'],
        bookingUrl: 'https://www.hotels.com/affiliate?landingPage=https%3A%2F%2Fwww.hotels.com%2Fho225804%2Fhigh-desert-motel-joshua-tree-national-park-joshua-tree-united-states-of-america%2F&camref=1110lFmx3&creativeref=1011l66481',
        lat: 34.1345,
        lng: -116.3133,
      },
      {
        name: 'Holiday Inn Express Twentynine Palms',
        slug: 'holiday-inn-express-twentynine-palms',
        priceRange: '$$',
        pricePerNight: '$140-230',
        distanceToSlopes: '3 miles from North Entrance',
        skiInSkiOut: false,
        description: 'A reliable chain hotel in Twentynine Palms, serving as a convenient base for the park\'s north entrance. Modern rooms, hot breakfast included, and an outdoor pool for cooling off after desert hikes.',
        amenities: ['Pool', 'Free Breakfast', 'Free Parking', 'Free Wi-Fi', 'Fitness Center'],
        bookingUrl: 'https://www.hotels.com/affiliate?landingPage=https%3A%2F%2Fwww.hotels.com%2Fho352899%2Fholiday-inn-express-hotel-suites-twentynine-palms-an-ihg-hotel-twentynine-palms-united-states-of-america%2F&camref=1110lFmx3&creativeref=1011l66481',
        lat: 34.1356,
        lng: -116.0522,
      },
      {
        name: 'Ace Hotel & Swim Club',
        slug: 'ace-hotel-swim-club',
        priceRange: '$$$',
        pricePerNight: '$250-400',
        distanceToSlopes: '30 miles from West Entrance',
        skiInSkiOut: false,
        description: 'A hip, design-forward hotel in Palm Springs housed in a converted 1965 motel, featuring vintage-inspired rooms, a DJ-curated pool scene, and a popular restaurant. A stylish desert retreat after a day in Joshua Tree.',
        amenities: ['Pool', 'Spa', 'Restaurant', 'Live Music', 'Free Wi-Fi'],
        bookingUrl: 'https://www.hotels.com/affiliate?landingPage=https%3A%2F%2Fwww.hotels.com%2Fho117262%2Face-hotel-and-swim-club-palm-springs-united-states-of-america%2F&camref=1110lFmx3&creativeref=1011l66481',
        lat: 33.8403,
        lng: -116.5453,
      },
    ],
  },

  {
    activityType: 'parks',
    name: 'Saguaro National Park',
    slug: 'saguaro',
    state: 'Arizona',
    country: 'US',
    region: 'Southwest',
    tagline: 'The iconic saguaro cactus forests of the Sonoran Desert flanking Tucson in two distinct mountain districts.',
    description: 'Saguaro National Park protects the nation\'s largest cacti in two separate districts on either side of Tucson, Arizona. The Rincon Mountain District to the east rises from desert scrub into pine forests, while the Tucson Mountain District to the west showcases dense saguaro forests at lower elevations. The park preserves a complete Sonoran Desert ecosystem where saguaros can live over 200 years and grow to 50 feet tall, providing homes for Gila woodpeckers, elf owls, and countless other desert species.',
    lat: 32.2967,
    lng: -111.1666,
    nearestAirport: 'Tucson International Airport',
    airportCode: 'TUS',
    driveFromAirport: '30 minutes',
    established: 1994,
    acreage: 92126,
    annualVisitors: '1.08 million',
    entranceFee: '$25 per vehicle',
    numberOfTrails: 165,
    highestPoint: 'Mica Mountain, 8,666 ft',
    season: 'Year-round (best to avoid extreme summer heat)',
    petFriendly: false,
    camping: true,
    wilderness: true,
    bestMonths: ['October', 'November', 'December', 'January', 'February', 'March', 'April'],
    highlights: [
      'Sunset on the Bajada Loop Drive through dense saguaro forests',
      'Hiking to the summit of Wasson Peak for 360-degree desert views',
      'Spring wildflower blooms carpeting the desert floor',
      'Saguaro blossoms in late May, Arizona\'s state flower',
      'Cactus Forest Scenic Loop Drive in the Rincon District',
      'Spotting Gila monsters, roadrunners, and javelinas at dawn',
    ],
    hotels: [
      {
        name: 'Tanque Verde Ranch',
        slug: 'tanque-verde-ranch',
        priceRange: '$$$$',
        pricePerNight: '$400-650',
        distanceToSlopes: '2 miles from Rincon District entrance',
        skiInSkiOut: false,
        description: 'A premier all-inclusive dude ranch nestled against the Rincon Mountains, operating since 1868. Horseback riding, nature programs, and gourmet Southwestern cuisine create an authentic desert ranch experience.',
        amenities: ['All-Inclusive Meals', 'Horseback Riding', 'Pool', 'Spa', 'Tennis'],
        bookingUrl: 'https://www.hotels.com/affiliate?landingPage=https%3A%2F%2Fwww.hotels.com%2Fho529680%2Ftanque-verde-ranch-tucson-united-states-of-america%2F&camref=1110lFmx3&creativeref=1011l66481',
        lat: 32.1862,
        lng: -110.7124,
      },
      {
        name: 'JW Marriott Starr Pass Resort',
        slug: 'jw-marriott-starr-pass',
        priceRange: '$$$',
        pricePerNight: '$280-450',
        distanceToSlopes: '8 miles from Tucson Mountain District',
        skiInSkiOut: false,
        description: 'A luxurious desert resort set in the Tucson Mountains with a championship golf course, full-service spa, lazy river pool complex, and panoramic views of the Sonoran Desert landscape.',
        amenities: ['Spa', 'Golf', 'Pool', 'Restaurant', 'Fitness Center'],
        bookingUrl: 'https://www.hotels.com/affiliate?landingPage=https%3A%2F%2Fwww.hotels.com%2Fho224660%2Fjw-marriott-starr-pass-resort-and-spa-tucson-united-states-of-america%2F&camref=1110lFmx3&creativeref=1011l66481',
        lat: 32.1858,
        lng: -111.0378,
      },
      {
        name: 'Hotel Congress',
        slug: 'hotel-congress',
        priceRange: '$',
        pricePerNight: '$100-180',
        distanceToSlopes: '15 miles from Tucson Mountain District',
        skiInSkiOut: false,
        description: 'A landmark 1919 downtown Tucson hotel with a storied past, famous as the site where John Dillinger was captured. Eclectic rooms, a lively bar and music venue, and a beloved cafe make it a Tucson institution.',
        amenities: ['Restaurant', 'Live Music Venue', 'Bar', 'Free Wi-Fi'],
        bookingUrl: 'https://www.hotels.com/affiliate?landingPage=https%3A%2F%2Fwww.hotels.com%2Fho550388%2Fthe-hotel-congress-tucson-united-states-of-america%2F&camref=1110lFmx3&creativeref=1011l66481',
        lat: 32.2224,
        lng: -110.9666,
      },
    ],
  },

  // ─── Pacific Region (4) ──────────────────────────────────────────────────────

  {
    activityType: 'parks',
    name: 'Yosemite National Park',
    slug: 'yosemite',
    state: 'California',
    country: 'US',
    region: 'Pacific',
    tagline: 'Granite monoliths, thundering waterfalls, and ancient giant sequoias in the Sierra Nevada\'s crown jewel valley.',
    description: 'Yosemite National Park protects nearly 1,200 square miles of Sierra Nevada wilderness, centered around the iconic Yosemite Valley with its sheer granite walls, plunging waterfalls, and meadows threaded by the Merced River. El Capitan and Half Dome are among the world\'s most famous rock formations, attracting climbers from around the globe. Beyond the valley, the park encompasses vast wilderness, three groves of ancient giant sequoias, and the high country of Tuolumne Meadows.',
    lat: 37.8651,
    lng: -119.5383,
    nearestAirport: 'Fresno Yosemite International Airport',
    airportCode: 'FAT',
    driveFromAirport: '2 hours 30 minutes',
    established: 1890,
    acreage: 761748,
    annualVisitors: '3.88 million',
    entranceFee: '$35 per vehicle',
    numberOfTrails: 800,
    highestPoint: 'Mount Lyell, 13,114 ft',
    season: 'Year-round (Tioga Road and Glacier Point Road close in winter)',
    petFriendly: false,
    camping: true,
    wilderness: true,
    bestMonths: ['May', 'June', 'July', 'August', 'September'],
    highlights: [
      'Hiking the Mist Trail to Vernal and Nevada Falls',
      'Watching the Firefall at Horsetail Fall in February',
      'Climbing or viewing El Capitan, the world\'s largest granite monolith',
      'Half Dome cables hike for a summit above 8,800 feet',
      'Mariposa Grove of ancient giant sequoias',
      'Tuolumne Meadows high country in summer',
    ],
    hotels: [
      {
        name: 'The Ahwahnee',
        slug: 'the-ahwahnee',
        priceRange: '$$$$',
        pricePerNight: '$500-900',
        distanceToSlopes: 'Inside park',
        skiInSkiOut: true,
        description: 'The grand dame of national park lodges, this 1927 landmark blends Art Deco design with Native American motifs beneath soaring cathedral ceilings. Floor-to-ceiling windows frame views of Half Dome, Glacier Point, and Yosemite Falls.',
        amenities: ['Fine Dining', 'Pool', 'Gift Shop', 'Concierge', 'Guided Tours'],
        bookingUrl: 'https://www.hotels.com/affiliate?landingPage=https%3A%2F%2Fwww.hotels.com%2Fho313936%2Fthe-ahwahnee-yosemite-national-park-united-states-of-america%2F&camref=1110lFmx3&creativeref=1011l66481',
        lat: 37.7468,
        lng: -119.5754,
      },
      {
        name: 'Yosemite Valley Lodge',
        slug: 'yosemite-valley-lodge',
        priceRange: '$$',
        pricePerNight: '$200-350',
        distanceToSlopes: 'Inside park',
        skiInSkiOut: true,
        description: 'A modern lodge at the base of Yosemite Falls offering comfortable rooms surrounded by meadows and pine forests. The central location provides walking access to the valley\'s main attractions and shuttle stops.',
        amenities: ['Restaurant', 'Pool', 'Bike Rentals', 'Tour Desk', 'Amphitheater'],
        bookingUrl: 'https://www.hotels.com/affiliate?landingPage=https%3A%2F%2Fwww.hotels.com%2Fho521949376%2Fyosemite-valley-lodge-yosemite-national-park-united-states-of-america%2F&camref=1110lFmx3&creativeref=1011l66481',
        lat: 37.7426,
        lng: -119.5977,
      },
      {
        name: 'Rush Creek Lodge',
        slug: 'rush-creek-lodge',
        priceRange: '$$$',
        pricePerNight: '$300-500',
        distanceToSlopes: '2 miles from Big Oak Flat Entrance',
        skiInSkiOut: false,
        description: 'A modern mountain lodge on 20 acres near the park\'s Highway 120 entrance, featuring a saltwater pool complex, tavern restaurant, guided activities, and hillside suites with forest views.',
        amenities: ['Restaurant', 'Pool', 'Spa', 'Game Room', 'Guided Activities'],
        bookingUrl: 'https://www.hotels.com/affiliate?landingPage=https%3A%2F%2Fwww.hotels.com%2Fho383686912%2Frush-creek-lodge-at-yosemite-groveland-united-states-of-america%2F&camref=1110lFmx3&creativeref=1011l66481',
        lat: 37.8582,
        lng: -119.852,
      },
      {
        name: 'Yosemite Bug Rustic Mountain Resort',
        slug: 'yosemite-bug-rustic-mountain-resort',
        priceRange: '$',
        pricePerNight: '$80-160',
        distanceToSlopes: '25 miles from Arch Rock Entrance',
        skiInSkiOut: false,
        description: 'An eclectic mountain retreat on the bus route to Yosemite, offering everything from dorm beds to private cabins. The on-site cafe, spa, and friendly community vibe make it a backpacker favorite.',
        amenities: ['Restaurant', 'Spa', 'Free Parking', 'Community Kitchen', 'Free Wi-Fi'],
        bookingUrl: 'https://www.hotels.com/affiliate?landingPage=https%3A%2F%2Fwww.hotels.com%2Fho3376744576%2Fyosemite-bug-rustic-mountain-resort-midpines-united-states-of-america%2F&camref=1110lFmx3&creativeref=1011l66481',
        lat: 37.5808,
        lng: -119.8524,
      },
    ],
  },

  {
    activityType: 'parks',
    name: 'Sequoia & Kings Canyon National Parks',
    slug: 'sequoia-kings-canyon',
    state: 'California',
    country: 'US',
    region: 'Pacific',
    tagline: 'Home to the world\'s largest trees and the deepest canyon in North America, hidden in the southern Sierra Nevada.',
    description: 'These jointly managed parks protect groves of the world\'s largest trees by volume -- the giant sequoias -- including General Sherman, the largest living tree on Earth. Kings Canyon plunges deeper than even the Grand Canyon, carved by glaciers and the Kings River through granite walls. Together, the parks encompass over 865,000 acres of Sierra Nevada wilderness, from foothills chaparral to the 14,505-foot summit of Mount Whitney, the tallest peak in the contiguous United States.',
    lat: 36.5651,
    lng: -118.773,
    nearestAirport: 'Fresno Yosemite International Airport',
    airportCode: 'FAT',
    driveFromAirport: '1 hour 30 minutes',
    established: 1890,
    acreage: 865964,
    annualVisitors: '1.88 million',
    entranceFee: '$35 per vehicle',
    numberOfTrails: 800,
    highestPoint: 'Mount Whitney, 14,505 ft',
    season: 'Year-round (Generals Highway and Kings Canyon Scenic Byway close in winter)',
    petFriendly: false,
    camping: true,
    wilderness: true,
    bestMonths: ['June', 'July', 'August', 'September'],
    highlights: [
      'Standing beside General Sherman, the world\'s largest tree by volume',
      'Driving the Kings Canyon Scenic Byway into the canyon depths',
      'Hiking through the Giant Forest among thousands of sequoias',
      'Crystal Cave tour through marble caverns with stalactites',
      'Moro Rock stairway climb for panoramic Great Western Divide views',
      'Backpacking the Rae Lakes Loop through alpine wilderness',
    ],
    hotels: [
      {
        name: 'Wuksachi Lodge',
        slug: 'wuksachi-lodge',
        priceRange: '$$$',
        pricePerNight: '$250-400',
        distanceToSlopes: 'Inside park',
        skiInSkiOut: true,
        description: 'The premier lodge in Sequoia National Park, set at 7,200 feet among the sequoia groves. The cedar-and-stone lodge offers modern rooms with forest views and an excellent dining room featuring locally sourced cuisine.',
        amenities: ['Restaurant', 'Gift Shop', 'Free Parking', 'Ski Shuttle (Winter)'],
        bookingUrl: 'https://www.hotels.com/affiliate?landingPage=https%3A%2F%2Fwww.hotels.com%2Fho237287%2Fwuksachi-lodge-sequoia-national-park-united-states-of-america%2F&camref=1110lFmx3&creativeref=1011l66481',
        lat: 36.5778,
        lng: -118.7442,
      },
      {
        name: 'John Muir Lodge',
        slug: 'john-muir-lodge',
        priceRange: '$$',
        pricePerNight: '$180-290',
        distanceToSlopes: 'Inside park',
        skiInSkiOut: true,
        description: 'A timber-and-stone lodge in Grant Grove Village within Kings Canyon, offering comfortable rooms with a cozy lobby fireplace. Centrally located between the two parks\' major attractions.',
        amenities: ['Restaurant', 'Gift Shop', 'Free Parking', 'Trail Access'],
        bookingUrl: 'https://www.hotels.com/affiliate?landingPage=https%3A%2F%2Fwww.hotels.com%2Fho445293%2Fjohn-muir-lodge-kings-canyon-national-park-united-states-of-america%2F&camref=1110lFmx3&creativeref=1011l66481',
        lat: 36.7406,
        lng: -118.9648,
      },
      {
        name: 'Montecito Sequoia Lodge',
        slug: 'montecito-sequoia-lodge',
        priceRange: '$$',
        pricePerNight: '$170-280',
        distanceToSlopes: 'Inside park (between Sequoia and Kings Canyon)',
        skiInSkiOut: true,
        description: 'A year-round family lodge nestled between the two parks, offering an all-inclusive camp experience in summer with meals, activities, and a private lake. In winter, it serves as a cross-country ski and snowshoe center.',
        amenities: ['All-Inclusive Meals', 'Lake', 'Pool', 'Archery', 'Canoeing'],
        bookingUrl: 'https://www.hotels.com/affiliate?landingPage=https%3A%2F%2Fwww.hotels.com%2Fho389687%2Fmontecito-sequoia-lodge-kings-canyon-national-park-united-states-of-america%2F&camref=1110lFmx3&creativeref=1011l66481',
        lat: 36.6421,
        lng: -118.8532,
      },
    ],
  },

  {
    activityType: 'parks',
    name: 'Olympic National Park',
    slug: 'olympic',
    state: 'Washington',
    country: 'US',
    region: 'Pacific',
    tagline: 'Glacier-capped peaks, temperate rainforests, and rugged Pacific coastline all within a single extraordinary park.',
    description: 'Olympic National Park encompasses nearly a million acres of the Olympic Peninsula, protecting three distinct ecosystems: glacier-clad mountains, old-growth temperate rainforests receiving up to 12 feet of rain per year, and 73 miles of wild Pacific coastline. The park\'s isolation on a peninsula has created unique species found nowhere else on Earth, including the Olympic marmot and Olympic torrent salamander. From the summit of Mount Olympus to the tide pools of Rialto Beach, the park\'s diversity is unmatched.',
    lat: 47.8021,
    lng: -123.6044,
    nearestAirport: 'Seattle-Tacoma International Airport',
    airportCode: 'SEA',
    driveFromAirport: '2 hours 30 minutes (to Port Angeles)',
    established: 1938,
    acreage: 922650,
    annualVisitors: '3.28 million',
    entranceFee: '$30 per vehicle',
    numberOfTrails: 611,
    highestPoint: 'Mount Olympus, 7,980 ft',
    season: 'Year-round (some roads close in winter)',
    petFriendly: false,
    camping: true,
    wilderness: true,
    bestMonths: ['June', 'July', 'August', 'September'],
    highlights: [
      'Hiking through the Hoh Rain Forest among moss-draped old growth',
      'Sunset at Rialto Beach with sea stacks and tide pools',
      'Hurricane Ridge alpine meadows and mountain panoramas',
      'Sol Duc Hot Springs soaking in old-growth forest',
      'Marymere Falls trail to a 90-foot waterfall near Lake Crescent',
      'Shi Shi Beach and Point of the Arches sea stack formations',
    ],
    hotels: [
      {
        name: 'Lake Crescent Lodge',
        slug: 'lake-crescent-lodge',
        priceRange: '$$',
        pricePerNight: '$200-340',
        distanceToSlopes: 'Inside park',
        skiInSkiOut: true,
        description: 'A 1916 lodge on the shores of the crystalline glacial lake, surrounded by old-growth forest. Roosevelt cabins and lodge rooms offer a peaceful retreat with rowing, kayaking, and hiking from the doorstep.',
        amenities: ['Restaurant', 'Boat Rentals', 'Gift Shop', 'Trail Access'],
        bookingUrl: 'https://www.hotels.com/affiliate?landingPage=https%3A%2F%2Fwww.hotels.com%2Fho135103872%2Flake-crescent-lodge-port-angeles-united-states-of-america%2F&camref=1110lFmx3&creativeref=1011l66481',
        lat: 48.0568,
        lng: -123.7935,
      },
      {
        name: 'Kalaloch Lodge',
        slug: 'kalaloch-lodge',
        priceRange: '$$',
        pricePerNight: '$210-360',
        distanceToSlopes: 'Inside park',
        skiInSkiOut: true,
        description: 'A bluff-top lodge overlooking the Pacific Ocean and Kalaloch Beach, offering lodge rooms and rustic cabins with ocean views. The park\'s only coastal lodging, with direct beach access and stunning sunsets.',
        amenities: ['Restaurant', 'Gift Shop', 'Beach Access', 'Ocean Views'],
        bookingUrl: 'https://www.hotels.com/affiliate?landingPage=https%3A%2F%2Fwww.hotels.com%2Fho214932%2Fkalaloch-lodge-kalaloch-united-states-of-america%2F&camref=1110lFmx3&creativeref=1011l66481',
        lat: 47.6136,
        lng: -124.3741,
      },
      {
        name: 'Lake Quinault Lodge',
        slug: 'lake-quinault-lodge',
        priceRange: '$$',
        pricePerNight: '$180-280',
        distanceToSlopes: '30 min drive',
        skiInSkiOut: false,
        description: 'A historic 1926 lakeside lodge on the shores of Lake Quinault in the Olympic rainforest. Cozy rooms, a fireplace lobby, and easy access to rainforest trails.',
        amenities: ['Restaurant', 'Fireplace Lobby', 'Lake Views', 'WiFi'],
        bookingUrl: 'https://www.hotels.com/affiliate?landingPage=https%3A%2F%2Fwww.hotels.com%2Fho218284%2Flake-quinault-lodge-quinault-united-states-of-america%2F&camref=1110lFmx3&creativeref=1011l66481',
        lat: 47.4593,
        lng: -123.8485,
      },
      {
        name: 'Olympic Lodge',
        slug: 'olympic-lodge',
        priceRange: '$',
        pricePerNight: '$120-200',
        distanceToSlopes: '5 miles from Hurricane Ridge entrance',
        skiInSkiOut: false,
        description: 'A comfortable lodge in Port Angeles, the main gateway to Olympic National Park, offering spacious rooms with mountain views, an outdoor pool, and easy access to Hurricane Ridge and the park\'s northern trails.',
        amenities: ['Pool', 'Free Breakfast', 'Free Parking', 'Free Wi-Fi', 'Fitness Center'],
        bookingUrl: 'https://www.hotels.com/affiliate?landingPage=https%3A%2F%2Fwww.hotels.com%2Fho1802208%2Folympic-lodge-port-angeles-united-states-of-america%2F&camref=1110lFmx3&creativeref=1011l66481',
        lat: 48.1031,
        lng: -123.4261,
      },
    ],
  },

  {
    activityType: 'parks',
    name: 'Mount Rainier National Park',
    slug: 'mount-rainier',
    state: 'Washington',
    country: 'US',
    region: 'Pacific',
    tagline: 'The most glaciated peak in the contiguous United States, rising 14,411 feet above wildflower-carpeted alpine meadows.',
    description: 'Mount Rainier National Park centers on the massive stratovolcano that dominates the Pacific Northwest skyline, carrying 25 major glaciers containing over one cubic mile of ice. The park\'s 236,381 acres range from old-growth forest to subalpine meadows that explode with wildflowers each summer, to the permanent snowfields and crevassed glaciers above. Paradise, on the mountain\'s south side, holds the record for the most snowfall measured in a single season in the United States at 93.5 feet.',
    lat: 46.8523,
    lng: -121.7603,
    nearestAirport: 'Seattle-Tacoma International Airport',
    airportCode: 'SEA',
    driveFromAirport: '2 hours',
    established: 1899,
    acreage: 236381,
    annualVisitors: '2.29 million',
    entranceFee: '$30 per vehicle',
    numberOfTrails: 260,
    highestPoint: 'Mount Rainier summit, 14,411 ft',
    season: 'Year-round (Sunrise Road closes in winter)',
    petFriendly: false,
    camping: true,
    wilderness: true,
    bestMonths: ['July', 'August', 'September'],
    highlights: [
      'Wildflower meadows at Paradise with the mountain towering above',
      'Sunrise visitor center for the closest drive-up views of the summit',
      'Hiking the Skyline Trail loop at Paradise through alpine meadows',
      'Climbing to Camp Muir at 10,188 feet for summit attempts',
      'Grove of the Patriarchs walk among 1,000-year-old trees',
      'Reflection Lakes mirroring Mount Rainier on calm mornings',
    ],
    hotels: [
      {
        name: 'Paradise Inn',
        slug: 'paradise-inn',
        priceRange: '$$',
        pricePerNight: '$180-300',
        distanceToSlopes: 'Inside park',
        skiInSkiOut: true,
        description: 'A 1916 rustic alpine lodge at 5,400 feet on the south side of Mount Rainier, featuring exposed timber construction, a massive stone fireplace, and direct access to the Paradise meadows and trail system.',
        amenities: ['Restaurant', 'Gift Shop', 'Lounge', 'Trail Access'],
        bookingUrl: 'https://www.hotels.com/affiliate?landingPage=https%3A%2F%2Fwww.hotels.com%2Fho712487904%2Fparadise-inn-paradise-united-states-of-america%2F&camref=1110lFmx3&creativeref=1011l66481',
        lat: 46.7862,
        lng: -121.7355,
      },
      {
        name: 'National Park Inn',
        slug: 'national-park-inn',
        priceRange: '$$',
        pricePerNight: '$160-260',
        distanceToSlopes: 'Inside park',
        skiInSkiOut: true,
        description: 'A cozy year-round inn at the Longmire historic district within the park, offering simple but comfortable rooms with a front porch overlooking Mount Rainier. The park\'s only lodging open in winter.',
        amenities: ['Restaurant', 'Gift Shop', 'Hiking Trails', 'General Store'],
        bookingUrl: 'https://www.hotels.com/affiliate?landingPage=https%3A%2F%2Fwww.hotels.com%2Fho711172288%2Fnational-park-inn-longmire-united-states-of-america%2F&camref=1110lFmx3&creativeref=1011l66481',
        lat: 46.7498,
        lng: -121.8114,
      },
      {
        name: 'Alexander\'s Lodge',
        slug: 'alexanders-lodge',
        priceRange: '$',
        pricePerNight: '$120-200',
        distanceToSlopes: '1 mile from Nisqually Entrance',
        skiInSkiOut: false,
        description: 'A charming 1912 bed-and-breakfast lodge at the Nisqually entrance to Mount Rainier, offering individually decorated rooms and a hearty breakfast. One of the oldest operating lodges in the region.',
        amenities: ['Free Breakfast', 'Free Parking', 'Hot Tub', 'Garden'],
        bookingUrl: 'https://www.hotels.com/affiliate?landingPage=https%3A%2F%2Fwww.hotels.com%2Fho555689%2Falexander-s-lodge-ashford-united-states-of-america%2F&camref=1110lFmx3&creativeref=1011l66481',
        lat: 46.7568,
        lng: -121.9146,
      },
    ],
  },

  // ─── Southeast Region (3) ────────────────────────────────────────────────────

  {
    activityType: 'parks',
    name: 'Great Smoky Mountains National Park',
    slug: 'great-smoky-mountains',
    state: 'Tennessee/North Carolina',
    country: 'US',
    region: 'Southeast',
    tagline: 'America\'s most visited national park, where ancient mountains meet the world\'s finest temperate deciduous forest.',
    description: 'Straddling the border of Tennessee and North Carolina, the Great Smoky Mountains protect the largest remaining tract of old-growth forest in the eastern United States. The park\'s name comes from the natural fog that often clings to its peaks, created by moisture released by the incredibly diverse vegetation. With over 19,000 documented species and estimates of 80,000-100,000 total species, the Smokies are among the most biodiverse places in the temperate world, earning its designation as a UNESCO World Heritage Site.',
    lat: 35.6118,
    lng: -83.4895,
    nearestAirport: 'McGhee Tyson Airport',
    airportCode: 'TYS',
    driveFromAirport: '45 minutes',
    established: 1934,
    acreage: 522427,
    annualVisitors: '12.78 million',
    entranceFee: 'Free (parking tags required: $5/day)',
    numberOfTrails: 849,
    highestPoint: 'Clingmans Dome, 6,643 ft',
    season: 'Year-round',
    petFriendly: false,
    camping: true,
    wilderness: true,
    bestMonths: ['April', 'May', 'June', 'September', 'October'],
    highlights: [
      'Clingmans Dome observation tower for 360-degree mountain views',
      'Cades Cove loop for wildlife, historic cabins, and fall color',
      'Synchronous firefly displays in Elkmont each June',
      'Hiking to Ramsey Cascades, the park\'s tallest waterfall at 100 feet',
      'Fall foliage driving on Newfound Gap Road',
      'Exploring historic Cataloochee Valley for elk watching',
    ],
    hotels: [
      {
        name: 'The Park Vista, a DoubleTree by Hilton',
        slug: 'park-vista-doubletree',
        priceRange: '$$',
        pricePerNight: '$160-280',
        distanceToSlopes: '5 min drive',
        skiInSkiOut: false,
        description: 'A hilltop hotel overlooking the Smoky Mountains with panoramic views, indoor pool, and easy access to downtown Gatlinburg and park entrances.',
        amenities: ['Pool', 'Restaurant', 'Mountain Views', 'WiFi', 'Fitness Center'],
        bookingUrl: 'https://www.hotels.com/affiliate?landingPage=https%3A%2F%2Fwww.hotels.com%2Fho126498%2Fthe-park-vista-a-doubletree-by-hilton-hotel-gatlinburg-gatlinburg-united-states-of-america%2F&camref=1110lFmx3&creativeref=1011l66481',
        lat: 35.7118,
        lng: -83.518,
      },
      {
        name: 'Bearskin Lodge on the River',
        slug: 'bearskin-lodge-on-the-river',
        priceRange: '$$',
        pricePerNight: '$180-300',
        distanceToSlopes: '0.5 miles from Gatlinburg entrance',
        skiInSkiOut: false,
        description: 'A riverside lodge on the Little Pigeon River at the edge of Gatlinburg, offering rooms with private balconies, river views, and the sound of the rushing mountain stream. Walking distance to the park\'s Sugarlands entrance.',
        amenities: ['Pool', 'Hot Tub', 'River Access', 'Free Parking', 'Balconies'],
        bookingUrl: 'https://www.hotels.com/affiliate?landingPage=https%3A%2F%2Fwww.hotels.com%2Fho529719%2Fbearskin-lodge-on-the-river-gatlinburg-united-states-of-america%2F&camref=1110lFmx3&creativeref=1011l66481',
        lat: 35.7139,
        lng: -83.5074,
      },
      {
        name: 'Balsam Mountain Inn',
        slug: 'balsam-mountain-inn',
        priceRange: '$$',
        pricePerNight: '$160-260',
        distanceToSlopes: '15 miles from Blue Ridge Parkway entrance',
        skiInSkiOut: false,
        description: 'A beautifully restored 1908 inn perched at 3,500 feet in the village of Balsam, North Carolina. This National Register property offers 50 rooms furnished with antiques and a wraparound porch with mountain views.',
        amenities: ['Restaurant', 'Library', 'Gardens', 'Free Parking', 'Hiking Trails'],
        bookingUrl: 'https://www.hotels.com/affiliate?landingPage=https%3A%2F%2Fwww.hotels.com%2Fho3755636768%2Fbalsam-mountain-inn%2F&camref=1110lFmx3&creativeref=1011l66481',
        lat: 35.4429,
        lng: -83.1006,
      },
      {
        name: 'Wild Bear Inn',
        slug: 'wild-bear-inn',
        priceRange: '$',
        pricePerNight: '$90-160',
        distanceToSlopes: '3 miles from Gatlinburg entrance',
        skiInSkiOut: false,
        description: 'A family-friendly resort in Pigeon Forge offering affordable suites with kitchenettes, an indoor pool and waterslide, and a game room. Convenient to both the national park and local attractions.',
        amenities: ['Pool', 'Waterslide', 'Game Room', 'Free Parking', 'Kitchenettes'],
        bookingUrl: 'https://www.hotels.com/affiliate?landingPage=https%3A%2F%2Fwww.hotels.com%2Fho119563%2Fwild-bear-inn-pigeon-forge-united-states-of-america%2F&camref=1110lFmx3&creativeref=1011l66481',
        lat: 35.7567,
        lng: -83.5523,
      },
    ],
  },

  {
    activityType: 'parks',
    name: 'Everglades National Park',
    slug: 'everglades',
    state: 'Florida',
    country: 'US',
    region: 'Southeast',
    tagline: 'A vast river of grass flowing slowly to the sea, harboring a unique subtropical wilderness found nowhere else in North America.',
    description: 'Everglades National Park protects 1.5 million acres of the southern tip of Florida\'s vast subtropical wetland, the only place in the world where alligators and crocodiles coexist. The park encompasses sawgrass prairies, mangrove forests, coastal lowlands, and the shallow waters of Florida Bay. This UNESCO World Heritage Site and International Biosphere Reserve is home to 36 threatened or protected species, including the endangered Florida panther and West Indian manatee.',
    lat: 25.2866,
    lng: -80.8987,
    nearestAirport: 'Miami International Airport',
    airportCode: 'MIA',
    driveFromAirport: '1 hour',
    established: 1947,
    acreage: 1508938,
    annualVisitors: '954,786',
    entranceFee: '$30 per vehicle',
    numberOfTrails: 39,
    highestPoint: '8 ft above sea level',
    season: 'Year-round (dry season December-April is best)',
    petFriendly: false,
    camping: true,
    wilderness: true,
    bestMonths: ['December', 'January', 'February', 'March', 'April'],
    highlights: [
      'Anhinga Trail boardwalk for close-up wildlife viewing',
      'Kayaking through the Ten Thousand Islands mangrove maze',
      'Airboat rides through sawgrass prairies at the park\'s edge',
      'Shark Valley tram tour and observation tower',
      'Flamingo marina area for manatees and roseate spoonbills',
      'Stargazing from the remote coastal prairies',
    ],
    hotels: [
      {
        name: 'Flamingo Lodge (Flamingo Adventures)',
        slug: 'flamingo-lodge',
        priceRange: '$$',
        pricePerNight: '$160-280',
        distanceToSlopes: 'Inside park',
        skiInSkiOut: true,
        description: 'The only lodging within Everglades National Park, located at Flamingo on the southern tip overlooking Florida Bay. Eco-tents and cottages offer rustic waterfront accommodations with kayak and boat rentals on site.',
        amenities: ['Boat Rentals', 'Kayak Rentals', 'Marina', 'Cafe', 'Bike Rentals'],
        bookingUrl: 'https://www.hotels.com/affiliate?landingPage=https%3A%2F%2Fwww.hotels.com%2Fho3834004448%2Fflamingo-adventures-lodge%2F&camref=1110lFmx3&creativeref=1011l66481',
        lat: 25.1413,
        lng: -80.9252,
      },
      {
        name: 'Ivey House Everglades Adventures',
        slug: 'ivey-house-everglades-adventures',
        priceRange: '$',
        pricePerNight: '$100-180',
        distanceToSlopes: '3 miles from Gulf Coast entrance',
        skiInSkiOut: false,
        description: 'A friendly eco-lodge in Everglades City that serves as the base for guided kayak, canoe, and boat tours into the Ten Thousand Islands. Comfortable rooms and a pool surrounded by tropical gardens.',
        amenities: ['Pool', 'Guided Tours', 'Kayak Rentals', 'Free Parking', 'Free Wi-Fi'],
        bookingUrl: 'https://www.hotels.com/affiliate?landingPage=https%3A%2F%2Fwww.hotels.com%2Fho261135%2Fivey-house-everglades-adventures-hotel-everglades-city-united-states-of-america%2F&camref=1110lFmx3&creativeref=1011l66481',
        lat: 25.858,
        lng: -81.381,
      },
      {
        name: 'DoubleTree by Hilton Miami Airport',
        slug: 'doubletree-miami-airport',
        priceRange: '$$',
        pricePerNight: '$150-250',
        distanceToSlopes: '35 miles from Ernest Coe entrance',
        skiInSkiOut: false,
        description: 'A full-service hotel near Miami International Airport, convenient for visitors arriving by air who plan to explore the Everglades. Modern rooms, a tropical pool deck, and multiple dining options.',
        amenities: ['Pool', 'Restaurant', 'Airport Shuttle', 'Free Wi-Fi', 'Fitness Center'],
        bookingUrl: 'https://www.hotels.com/affiliate?landingPage=https%3A%2F%2Fwww.hotels.com%2Fho115624%2Fdoubletree-by-hilton-hotel-miami-airport-convention-center-miami-united-states-of-america%2F&camref=1110lFmx3&creativeref=1011l66481',
        lat: 25.7909,
        lng: -80.2728,
      },
    ],
  },

  {
    activityType: 'parks',
    name: 'Acadia National Park',
    slug: 'acadia',
    state: 'Maine',
    country: 'US',
    region: 'Southeast',
    tagline: 'Where granite mountains meet the Atlantic Ocean on the rugged coast of Maine\'s Mount Desert Island.',
    description: 'Acadia National Park protects the highest rocky headlands along the Atlantic coastline of the United States, located primarily on Mount Desert Island off the coast of Maine. The park\'s 49,075 acres encompass granite peaks, ocean shoreline, woodlands, and lakes, offering one of the first places in the U.S. to see the sunrise each morning from the summit of Cadillac Mountain. Its historic carriage roads, built by John D. Rockefeller Jr., provide 45 miles of car-free paths through the landscape.',
    lat: 44.3386,
    lng: -68.2733,
    nearestAirport: 'Bangor International Airport',
    airportCode: 'BGR',
    driveFromAirport: '1 hour',
    established: 1919,
    acreage: 49075,
    annualVisitors: '4.07 million',
    entranceFee: '$35 per vehicle',
    numberOfTrails: 158,
    highestPoint: 'Cadillac Mountain, 1,530 ft',
    season: 'Year-round (Park Loop Road partially closes in winter)',
    petFriendly: true,
    camping: true,
    wilderness: false,
    bestMonths: ['June', 'July', 'August', 'September', 'October'],
    highlights: [
      'Sunrise from Cadillac Mountain, the first in the eastern U.S.',
      'Hiking the Precipice Trail with iron rungs and ladders',
      'Biking the 45-mile network of historic carriage roads',
      'Jordan Pond House for popovers and tea with mountain views',
      'Thunder Hole where waves crash into a narrow granite inlet',
      'Fall foliage reflecting in Eagle Lake and Jordan Pond',
    ],
    hotels: [
      {
        name: 'Bar Harbor Inn & Spa',
        slug: 'bar-harbor-inn-spa',
        priceRange: '$$$',
        pricePerNight: '$300-500',
        distanceToSlopes: '2 miles from park entrance',
        skiInSkiOut: false,
        description: 'A waterfront resort on eight acres overlooking Frenchman Bay in downtown Bar Harbor. The historic main inn and modern oceanfront lodge offer elegant rooms with sweeping ocean and island views.',
        amenities: ['Spa', 'Restaurant', 'Pool', 'Waterfront', 'Free Wi-Fi'],
        bookingUrl: 'https://www.hotels.com/affiliate?landingPage=https%3A%2F%2Fwww.hotels.com%2Fho237104%2Fbar-harbor-inn-bar-harbor-united-states-of-america%2F&camref=1110lFmx3&creativeref=1011l66481',
        lat: 44.3905,
        lng: -68.2042,
      },
      {
        name: 'Asticou Inn',
        slug: 'asticou-inn',
        priceRange: '$$$',
        pricePerNight: '$260-420',
        distanceToSlopes: '1 mile from park entrance',
        skiInSkiOut: false,
        description: 'A grand 1883 inn overlooking Northeast Harbor with meticulously maintained Asticou Azalea Garden. Classic New England charm with modern comforts, a fine dining restaurant, and a heated pool.',
        amenities: ['Restaurant', 'Pool', 'Tennis', 'Gardens', 'Dock'],
        bookingUrl: 'https://www.hotels.com/affiliate?landingPage=https%3A%2F%2Fwww.hotels.com%2Fho197758%2Fasticou-inn-northeast-harbor-united-states-of-america%2F&camref=1110lFmx3&creativeref=1011l66481',
        lat: 44.3036,
        lng: -68.2876,
      },
      {
        name: 'Acadia Inn',
        slug: 'acadia-inn',
        priceRange: '$$',
        pricePerNight: '$160-280',
        distanceToSlopes: '1 mile from park entrance',
        skiInSkiOut: false,
        description: 'A well-located inn on Route 3 in Bar Harbor offering clean, comfortable rooms with an outdoor pool and hot tub. Walking distance to the Island Explorer shuttle that provides free transportation throughout the park.',
        amenities: ['Pool', 'Hot Tub', 'Free Parking', 'Free Wi-Fi', 'Shuttle Access'],
        bookingUrl: 'https://www.hotels.com/affiliate?landingPage=https%3A%2F%2Fwww.hotels.com%2Fho417084%2Facadia-inn-bar-harbor-united-states-of-america%2F&camref=1110lFmx3&creativeref=1011l66481',
        lat: 44.3776,
        lng: -68.2241,
      },
      {
        name: 'Atlantic Oceanside Hotel & Event Center',
        slug: 'atlantic-oceanside-hotel',
        priceRange: '$$',
        pricePerNight: '$160-300',
        distanceToSlopes: '5 min drive',
        skiInSkiOut: false,
        description: 'An oceanfront hotel on the shores of Frenchman Bay with private beach access, outdoor pool, and views of the Porcupine Islands. Minutes from Acadia\'s main entrance.',
        amenities: ['Pool', 'Private Beach', 'Ocean Views', 'WiFi', 'Restaurant'],
        bookingUrl: 'https://www.hotels.com/affiliate?landingPage=https%3A%2F%2Fwww.hotels.com%2Fho117580%2Fatlantic-oceanside-hotel-and-event-center-bar-harbor-united-states-of-america%2F&camref=1110lFmx3&creativeref=1011l66481',
        lat: 44.3917,
        lng: -68.215,
      },
    ],
  },

  // ─── Alaska/Hawaii Region (2) ────────────────────────────────────────────────

  {
    activityType: 'parks',
    name: 'Denali National Park',
    slug: 'denali',
    state: 'Alaska',
    country: 'US',
    region: 'Alaska/Hawaii',
    tagline: 'North America\'s tallest peak presides over six million acres of raw Alaskan wilderness teeming with grizzlies, wolves, and caribou.',
    description: 'Denali National Park and Preserve encompasses six million acres of wild interior Alaska centered around Denali (formerly Mount McKinley), the highest peak in North America at 20,310 feet. The park has only one road, most of which is accessible only by park bus, keeping the vast tundra and boreal forests in a near-pristine state. Grizzly bears, wolves, Dall sheep, moose, and caribou roam freely across a landscape that stretches from lowland spruce forest through alpine tundra to permanent glacial ice.',
    lat: 63.3333,
    lng: -150.5,
    nearestAirport: 'Fairbanks International Airport',
    airportCode: 'FAI',
    driveFromAirport: '2 hours 15 minutes',
    established: 1917,
    acreage: 6045153,
    annualVisitors: '591,399',
    entranceFee: '$15 per person',
    numberOfTrails: 35,
    highestPoint: 'Denali (Mount McKinley), 20,310 ft',
    season: 'Year-round (Park Road beyond Mile 3 open June-September)',
    petFriendly: false,
    camping: true,
    wilderness: true,
    bestMonths: ['June', 'July', 'August'],
    highlights: [
      'Denali summit visible on clear days from Wonder Lake',
      'Bus tour deep into the park on the 92-mile Park Road',
      'Grizzly bear and caribou viewing from the Eielson Visitor Center',
      'Flightseeing around Denali\'s summit and Ruth Glacier',
      'Hiking off-trail across open tundra with no established paths',
      'Northern lights viewing in late August and September',
    ],
    hotels: [
      {
        name: 'Denali Princess Wilderness Lodge',
        slug: 'denali-princess-wilderness-lodge',
        priceRange: '$$$',
        pricePerNight: '$280-450',
        distanceToSlopes: '1 mile from park entrance',
        skiInSkiOut: false,
        description: 'A sprawling riverside lodge on the Nenana River just outside the park entrance, offering rooms and bungalows with mountain views, multiple dining options, and organized excursions into the park.',
        amenities: ['Restaurant', 'Dinner Theater', 'Gift Shop', 'Tour Desk', 'River Views'],
        bookingUrl: 'https://www.hotels.com/affiliate?landingPage=https%3A%2F%2Fwww.hotels.com%2Fho112800%2Fdenali-princess-wilderness-lodge-denali-national-park-united-states-of-america%2F&camref=1110lFmx3&creativeref=1011l66481',
        lat: 63.7339,
        lng: -148.9145,
      },
      {
        name: 'Denali Bluffs Hotel',
        slug: 'denali-bluffs-hotel',
        priceRange: '$$',
        pricePerNight: '$180-320',
        distanceToSlopes: '1 mile to park entrance',
        skiInSkiOut: false,
        description: 'A hillside hotel near the Denali park entrance with stunning mountain views from private balconies. Close to the Denali Visitor Center and shuttle stops.',
        amenities: ['Mountain Views', 'Balconies', 'Restaurant', 'WiFi', 'Shuttle'],
        bookingUrl: 'https://www.hotels.com/affiliate?landingPage=https%3A%2F%2Fwww.hotels.com%2Fho262498%2Fdenali-bluffs-hotel-denali-national-park-united-states-of-america%2F&camref=1110lFmx3&creativeref=1011l66481',
        lat: 63.7328,
        lng: -148.9144,
      },
      {
        name: 'McKinley Chalet Resort',
        slug: 'mckinley-chalet-resort',
        priceRange: '$$',
        pricePerNight: '$180-310',
        distanceToSlopes: '2 miles from park entrance',
        skiInSkiOut: false,
        description: 'A large resort along the Nenana River canyon near the park entrance, offering multiple room categories, a dinner theater, and rafting excursions. Popular with tour groups exploring Denali.',
        amenities: ['Restaurant', 'Tour Desk', 'Gift Shop', 'Free Parking', 'Rafting'],
        bookingUrl: 'https://www.hotels.com/affiliate?landingPage=https%3A%2F%2Fwww.hotels.com%2Fho212455%2Fmckinley-chalet-resort-denali-national-park-united-states-of-america%2F&camref=1110lFmx3&creativeref=1011l66481',
        lat: 63.7362,
        lng: -148.9041,
      },
    ],
  },

  {
    activityType: 'parks',
    name: 'Haleakala National Park',
    slug: 'haleakala',
    state: 'Hawaii',
    country: 'US',
    region: 'Alaska/Hawaii',
    tagline: 'A sacred volcanic summit above the clouds on Maui, where the demigod Maui lassoed the sun.',
    description: 'Haleakala National Park protects the massive shield volcano that forms more than 75% of the island of Maui, from its 10,023-foot summit to the pools and waterfalls of Kipahulu on the coast. The summit crater is a vast erosional depression spanning 7 miles long and 2 miles wide, with cinder cones rising from its floor. The park protects more endangered species than any other national park, including the Hawaiian goose (nene) and the extraordinary silversword plant that blooms only once in its lifetime.',
    lat: 20.7204,
    lng: -156.1552,
    nearestAirport: 'Kahului Airport',
    airportCode: 'OGG',
    driveFromAirport: '1 hour 15 minutes (to summit)',
    established: 1916,
    acreage: 33265,
    annualVisitors: '1.28 million',
    entranceFee: '$30 per vehicle',
    numberOfTrails: 30,
    highestPoint: 'Haleakala summit (Pu\'u \'Ula\'ula), 10,023 ft',
    season: 'Year-round',
    petFriendly: false,
    camping: true,
    wilderness: true,
    bestMonths: ['April', 'May', 'June', 'September', 'October', 'November'],
    highlights: [
      'Watching sunrise from the 10,023-foot summit above the clouds',
      'Hiking the Sliding Sands Trail into the volcanic crater',
      'Seven Sacred Pools (Ohe\'o Gulch) at Kipahulu for swimming',
      'Spotting the rare Haleakala silversword plant in bloom',
      'Mountain biking down the volcano from summit to sea level',
      'Stargazing from one of the clearest viewpoints on Earth',
    ],
    hotels: [
      {
        name: 'Montage Kapalua Bay',
        slug: 'montage-kapalua-bay',
        priceRange: '$$$$',
        pricePerNight: '$600-1200',
        distanceToSlopes: '35 miles from park entrance',
        skiInSkiOut: false,
        description: 'An ultra-luxury oceanfront resort on Kapalua Bay, consistently rated among Maui\'s finest. Spacious residential-style suites with full kitchens, a world-class spa, and stunning sunset views over Molokai.',
        amenities: ['Spa', 'Pool', 'Beach Access', 'Restaurant', 'Golf', 'Tennis'],
        bookingUrl: 'https://www.hotels.com/affiliate?landingPage=https%3A%2F%2Fwww.hotels.com%2Fho429193%2Fmontage-kapalua-bay-lahaina-united-states-of-america%2F&camref=1110lFmx3&creativeref=1011l66481',
        lat: 21.0024,
        lng: -156.6649,
      },
      {
        name: 'Lumeria Maui',
        slug: 'lumeria-maui',
        priceRange: '$$$',
        pricePerNight: '$300-500',
        distanceToSlopes: '30 min drive to summit',
        skiInSkiOut: false,
        description: 'A serene retreat in upcountry Maui surrounded by gardens and ocean views. The closest upscale accommodation to Haleakala\'s summit, offering yoga, farm-to-table dining, and a tranquil atmosphere.',
        amenities: ['Restaurant', 'Yoga', 'Gardens', 'Ocean Views', 'WiFi'],
        bookingUrl: 'https://www.hotels.com/affiliate?landingPage=https%3A%2F%2Fwww.hotels.com%2Fho389017%2Flumeria-maui-an-educational-retreat-makawao-united-states-of-america%2F&camref=1110lFmx3&creativeref=1011l66481',
        lat: 20.8553,
        lng: -156.3303,
      },
      {
        name: 'Maui Seaside Hotel',
        slug: 'maui-seaside-hotel',
        priceRange: '$',
        pricePerNight: '$120-200',
        distanceToSlopes: '25 miles from park entrance',
        skiInSkiOut: false,
        description: 'A no-frills local hotel in Kahului near the airport, offering affordable rooms with a pool and Japanese restaurant. A practical budget base for early-morning sunrise trips to Haleakala summit.',
        amenities: ['Pool', 'Restaurant', 'Free Parking', 'Free Wi-Fi'],
        bookingUrl: 'https://www.hotels.com/affiliate?landingPage=https%3A%2F%2Fwww.hotels.com%2Fho170660%2Fmaui-seaside-hotel-kahului-united-states-of-america%2F&camref=1110lFmx3&creativeref=1011l66481',
        lat: 20.8893,
        lng: -156.4729,
      },
    ],
  },
]

// ─── Helper Functions ──────────────────────────────────────────────────────────

export function getParkBySlug(slug: string): NationalParkDestination | undefined {
  return nationalParks.find((p) => p.slug === slug)
}

export function getParksByRegion(region: string): NationalParkDestination[] {
  return nationalParks.filter((p) => p.region === region)
}

export function getAllParkSlugs(): string[] {
  return nationalParks.map((p) => p.slug)
}

export function sortParks(
  parks: NationalParkDestination[],
  sortKey: string
): NationalParkDestination[] {
  const sorted = [...parks]

  switch (sortKey) {
    case 'name-asc':
      return sorted.sort((a, b) => a.name.localeCompare(b.name))
    case 'name-desc':
      return sorted.sort((a, b) => b.name.localeCompare(a.name))
    case 'acreage-desc':
      return sorted.sort((a, b) => b.acreage - a.acreage)
    case 'trails-desc':
      return sorted.sort((a, b) => b.numberOfTrails - a.numberOfTrails)
    case 'visitors-desc':
      return sorted.sort((a, b) => {
        const parseVisitors = (v: string): number => {
          const cleaned = v.replace(/[^0-9.]/g, '')
          const num = parseFloat(cleaned)
          if (v.toLowerCase().includes('million')) {
            return num * 1_000_000
          }
          return num
        }
        return parseVisitors(b.annualVisitors) - parseVisitors(a.annualVisitors)
      })
    default:
      return sorted
  }
}

export function filterParks(
  parks: NationalParkDestination[],
  filters: {
    camping?: string
    petFriendly?: string
    wilderness?: string
    freeEntrance?: string
  }
): NationalParkDestination[] {
  return parks.filter((park) => {
    if (filters.camping === 'true' && !park.camping) return false
    if (filters.camping === 'false' && park.camping) return false

    if (filters.petFriendly === 'true' && !park.petFriendly) return false
    if (filters.petFriendly === 'false' && park.petFriendly) return false

    if (filters.wilderness === 'true' && !park.wilderness) return false
    if (filters.wilderness === 'false' && park.wilderness) return false

    if (filters.freeEntrance === 'true') {
      const isFree =
        park.entranceFee.toLowerCase().includes('free') ||
        park.entranceFee === '$0'
      if (!isFree) return false
    }
    if (filters.freeEntrance === 'false') {
      const isFree =
        park.entranceFee.toLowerCase().includes('free') ||
        park.entranceFee === '$0'
      if (isFree) return false
    }

    return true
  })
}
