import type { ParkWeatherMonth, ParkWeather } from './types'

export const parkWeatherData: ParkWeather[] = [
  {
    slug: 'yellowstone',
    monthly: [
      { month: 'January', avgHighF: 25, avgLowF: 5, avgPrecipitationInches: 1.2, rainyDays: 10, sunnyDays: 12 },
      { month: 'February', avgHighF: 29, avgLowF: 7, avgPrecipitationInches: 1.0, rainyDays: 9, sunnyDays: 12 },
      { month: 'March', avgHighF: 37, avgLowF: 14, avgPrecipitationInches: 1.3, rainyDays: 11, sunnyDays: 12 },
      { month: 'April', avgHighF: 46, avgLowF: 23, avgPrecipitationInches: 1.5, rainyDays: 11, sunnyDays: 11 },
      { month: 'May', avgHighF: 57, avgLowF: 31, avgPrecipitationInches: 2.2, rainyDays: 13, sunnyDays: 11 },
      { month: 'June', avgHighF: 67, avgLowF: 38, avgPrecipitationInches: 2.0, rainyDays: 11, sunnyDays: 14 },
      { month: 'July', avgHighF: 78, avgLowF: 43, avgPrecipitationInches: 1.3, rainyDays: 7, sunnyDays: 20 },
      { month: 'August', avgHighF: 77, avgLowF: 42, avgPrecipitationInches: 1.2, rainyDays: 7, sunnyDays: 20 },
      { month: 'September', avgHighF: 65, avgLowF: 33, avgPrecipitationInches: 1.3, rainyDays: 8, sunnyDays: 17 },
      { month: 'October', avgHighF: 50, avgLowF: 24, avgPrecipitationInches: 1.2, rainyDays: 8, sunnyDays: 15 },
      { month: 'November', avgHighF: 34, avgLowF: 13, avgPrecipitationInches: 1.1, rainyDays: 9, sunnyDays: 12 },
      { month: 'December', avgHighF: 25, avgLowF: 5, avgPrecipitationInches: 1.2, rainyDays: 10, sunnyDays: 11 },
    ],
  },
  {
    slug: 'grand-teton',
    monthly: [
      { month: 'January', avgHighF: 24, avgLowF: 2, avgPrecipitationInches: 1.8, rainyDays: 11, sunnyDays: 11 },
      { month: 'February', avgHighF: 28, avgLowF: 4, avgPrecipitationInches: 1.4, rainyDays: 10, sunnyDays: 11 },
      { month: 'March', avgHighF: 37, avgLowF: 13, avgPrecipitationInches: 1.5, rainyDays: 10, sunnyDays: 12 },
      { month: 'April', avgHighF: 47, avgLowF: 22, avgPrecipitationInches: 1.4, rainyDays: 10, sunnyDays: 12 },
      { month: 'May', avgHighF: 58, avgLowF: 30, avgPrecipitationInches: 2.0, rainyDays: 12, sunnyDays: 12 },
      { month: 'June', avgHighF: 68, avgLowF: 37, avgPrecipitationInches: 1.8, rainyDays: 10, sunnyDays: 15 },
      { month: 'July', avgHighF: 79, avgLowF: 42, avgPrecipitationInches: 1.1, rainyDays: 6, sunnyDays: 21 },
      { month: 'August', avgHighF: 78, avgLowF: 40, avgPrecipitationInches: 1.0, rainyDays: 6, sunnyDays: 21 },
      { month: 'September', avgHighF: 66, avgLowF: 31, avgPrecipitationInches: 1.2, rainyDays: 7, sunnyDays: 18 },
      { month: 'October', avgHighF: 51, avgLowF: 22, avgPrecipitationInches: 1.2, rainyDays: 7, sunnyDays: 16 },
      { month: 'November', avgHighF: 34, avgLowF: 12, avgPrecipitationInches: 1.5, rainyDays: 9, sunnyDays: 12 },
      { month: 'December', avgHighF: 24, avgLowF: 3, avgPrecipitationInches: 1.8, rainyDays: 11, sunnyDays: 10 },
    ],
  },
  {
    slug: 'glacier',
    monthly: [
      { month: 'January', avgHighF: 28, avgLowF: 13, avgPrecipitationInches: 2.5, rainyDays: 13, sunnyDays: 8 },
      { month: 'February', avgHighF: 33, avgLowF: 16, avgPrecipitationInches: 1.9, rainyDays: 11, sunnyDays: 9 },
      { month: 'March', avgHighF: 40, avgLowF: 21, avgPrecipitationInches: 1.7, rainyDays: 11, sunnyDays: 10 },
      { month: 'April', avgHighF: 50, avgLowF: 29, avgPrecipitationInches: 1.6, rainyDays: 10, sunnyDays: 11 },
      { month: 'May', avgHighF: 60, avgLowF: 36, avgPrecipitationInches: 2.3, rainyDays: 13, sunnyDays: 11 },
      { month: 'June', avgHighF: 68, avgLowF: 43, avgPrecipitationInches: 2.8, rainyDays: 13, sunnyDays: 12 },
      { month: 'July', avgHighF: 78, avgLowF: 48, avgPrecipitationInches: 1.4, rainyDays: 7, sunnyDays: 19 },
      { month: 'August', avgHighF: 77, avgLowF: 47, avgPrecipitationInches: 1.3, rainyDays: 7, sunnyDays: 19 },
      { month: 'September', avgHighF: 64, avgLowF: 38, avgPrecipitationInches: 1.5, rainyDays: 8, sunnyDays: 15 },
      { month: 'October', avgHighF: 48, avgLowF: 29, avgPrecipitationInches: 1.6, rainyDays: 9, sunnyDays: 13 },
      { month: 'November', avgHighF: 33, avgLowF: 20, avgPrecipitationInches: 2.1, rainyDays: 12, sunnyDays: 8 },
      { month: 'December', avgHighF: 27, avgLowF: 13, avgPrecipitationInches: 2.4, rainyDays: 13, sunnyDays: 7 },
    ],
  },
  {
    slug: 'rocky-mountain',
    monthly: [
      { month: 'January', avgHighF: 36, avgLowF: 16, avgPrecipitationInches: 0.5, rainyDays: 6, sunnyDays: 18 },
      { month: 'February', avgHighF: 37, avgLowF: 16, avgPrecipitationInches: 0.5, rainyDays: 6, sunnyDays: 17 },
      { month: 'March', avgHighF: 42, avgLowF: 21, avgPrecipitationInches: 1.0, rainyDays: 9, sunnyDays: 15 },
      { month: 'April', avgHighF: 49, avgLowF: 26, avgPrecipitationInches: 1.5, rainyDays: 10, sunnyDays: 13 },
      { month: 'May', avgHighF: 58, avgLowF: 34, avgPrecipitationInches: 1.8, rainyDays: 12, sunnyDays: 13 },
      { month: 'June', avgHighF: 68, avgLowF: 41, avgPrecipitationInches: 1.5, rainyDays: 10, sunnyDays: 16 },
      { month: 'July', avgHighF: 75, avgLowF: 46, avgPrecipitationInches: 1.8, rainyDays: 12, sunnyDays: 16 },
      { month: 'August', avgHighF: 73, avgLowF: 45, avgPrecipitationInches: 1.7, rainyDays: 11, sunnyDays: 17 },
      { month: 'September', avgHighF: 66, avgLowF: 38, avgPrecipitationInches: 1.2, rainyDays: 8, sunnyDays: 18 },
      { month: 'October', avgHighF: 54, avgLowF: 29, avgPrecipitationInches: 0.9, rainyDays: 6, sunnyDays: 19 },
      { month: 'November', avgHighF: 42, avgLowF: 21, avgPrecipitationInches: 0.7, rainyDays: 6, sunnyDays: 17 },
      { month: 'December', avgHighF: 35, avgLowF: 15, avgPrecipitationInches: 0.5, rainyDays: 6, sunnyDays: 17 },
    ],
  },
  {
    slug: 'grand-canyon',
    monthly: [
      { month: 'January', avgHighF: 44, avgLowF: 18, avgPrecipitationInches: 1.3, rainyDays: 5, sunnyDays: 20 },
      { month: 'February', avgHighF: 48, avgLowF: 21, avgPrecipitationInches: 1.5, rainyDays: 5, sunnyDays: 18 },
      { month: 'March', avgHighF: 55, avgLowF: 25, avgPrecipitationInches: 1.3, rainyDays: 5, sunnyDays: 19 },
      { month: 'April', avgHighF: 63, avgLowF: 32, avgPrecipitationInches: 0.9, rainyDays: 4, sunnyDays: 21 },
      { month: 'May', avgHighF: 73, avgLowF: 39, avgPrecipitationInches: 0.6, rainyDays: 3, sunnyDays: 25 },
      { month: 'June', avgHighF: 84, avgLowF: 47, avgPrecipitationInches: 0.4, rainyDays: 2, sunnyDays: 27 },
      { month: 'July', avgHighF: 88, avgLowF: 54, avgPrecipitationInches: 1.7, rainyDays: 8, sunnyDays: 18 },
      { month: 'August', avgHighF: 85, avgLowF: 53, avgPrecipitationInches: 2.2, rainyDays: 9, sunnyDays: 17 },
      { month: 'September', avgHighF: 79, avgLowF: 47, avgPrecipitationInches: 1.4, rainyDays: 5, sunnyDays: 22 },
      { month: 'October', avgHighF: 65, avgLowF: 36, avgPrecipitationInches: 1.1, rainyDays: 4, sunnyDays: 22 },
      { month: 'November', avgHighF: 52, avgLowF: 25, avgPrecipitationInches: 0.9, rainyDays: 4, sunnyDays: 21 },
      { month: 'December', avgHighF: 43, avgLowF: 18, avgPrecipitationInches: 1.4, rainyDays: 5, sunnyDays: 19 },
    ],
  },
  {
    slug: 'arches',
    monthly: [
      { month: 'January', avgHighF: 42, avgLowF: 18, avgPrecipitationInches: 0.6, rainyDays: 4, sunnyDays: 21 },
      { month: 'February', avgHighF: 50, avgLowF: 25, avgPrecipitationInches: 0.5, rainyDays: 4, sunnyDays: 19 },
      { month: 'March', avgHighF: 62, avgLowF: 33, avgPrecipitationInches: 0.7, rainyDays: 5, sunnyDays: 20 },
      { month: 'April', avgHighF: 71, avgLowF: 40, avgPrecipitationInches: 0.8, rainyDays: 4, sunnyDays: 21 },
      { month: 'May', avgHighF: 82, avgLowF: 49, avgPrecipitationInches: 0.6, rainyDays: 4, sunnyDays: 24 },
      { month: 'June', avgHighF: 95, avgLowF: 58, avgPrecipitationInches: 0.4, rainyDays: 2, sunnyDays: 27 },
      { month: 'July', avgHighF: 100, avgLowF: 65, avgPrecipitationInches: 0.8, rainyDays: 4, sunnyDays: 24 },
      { month: 'August', avgHighF: 97, avgLowF: 63, avgPrecipitationInches: 0.7, rainyDays: 5, sunnyDays: 23 },
      { month: 'September', avgHighF: 87, avgLowF: 52, avgPrecipitationInches: 0.7, rainyDays: 4, sunnyDays: 23 },
      { month: 'October', avgHighF: 71, avgLowF: 39, avgPrecipitationInches: 0.9, rainyDays: 4, sunnyDays: 22 },
      { month: 'November', avgHighF: 55, avgLowF: 27, avgPrecipitationInches: 0.5, rainyDays: 3, sunnyDays: 22 },
      { month: 'December', avgHighF: 42, avgLowF: 18, avgPrecipitationInches: 0.5, rainyDays: 4, sunnyDays: 20 },
    ],
  },
  {
    slug: 'zion',
    monthly: [
      { month: 'January', avgHighF: 52, avgLowF: 29, avgPrecipitationInches: 1.5, rainyDays: 5, sunnyDays: 19 },
      { month: 'February', avgHighF: 57, avgLowF: 32, avgPrecipitationInches: 1.6, rainyDays: 6, sunnyDays: 17 },
      { month: 'March', avgHighF: 63, avgLowF: 36, avgPrecipitationInches: 1.5, rainyDays: 6, sunnyDays: 18 },
      { month: 'April', avgHighF: 73, avgLowF: 43, avgPrecipitationInches: 1.0, rainyDays: 4, sunnyDays: 21 },
      { month: 'May', avgHighF: 83, avgLowF: 52, avgPrecipitationInches: 0.5, rainyDays: 3, sunnyDays: 25 },
      { month: 'June', avgHighF: 95, avgLowF: 60, avgPrecipitationInches: 0.3, rainyDays: 2, sunnyDays: 28 },
      { month: 'July', avgHighF: 100, avgLowF: 68, avgPrecipitationInches: 0.7, rainyDays: 4, sunnyDays: 24 },
      { month: 'August', avgHighF: 97, avgLowF: 66, avgPrecipitationInches: 1.0, rainyDays: 5, sunnyDays: 23 },
      { month: 'September', avgHighF: 91, avgLowF: 57, avgPrecipitationInches: 0.7, rainyDays: 3, sunnyDays: 25 },
      { month: 'October', avgHighF: 75, avgLowF: 45, avgPrecipitationInches: 1.0, rainyDays: 4, sunnyDays: 22 },
      { month: 'November', avgHighF: 61, avgLowF: 34, avgPrecipitationInches: 1.0, rainyDays: 4, sunnyDays: 20 },
      { month: 'December', avgHighF: 51, avgLowF: 28, avgPrecipitationInches: 1.2, rainyDays: 5, sunnyDays: 19 },
    ],
  },
  {
    slug: 'bryce-canyon',
    monthly: [
      { month: 'January', avgHighF: 37, avgLowF: 10, avgPrecipitationInches: 1.2, rainyDays: 6, sunnyDays: 18 },
      { month: 'February', avgHighF: 39, avgLowF: 13, avgPrecipitationInches: 1.0, rainyDays: 6, sunnyDays: 16 },
      { month: 'March', avgHighF: 47, avgLowF: 19, avgPrecipitationInches: 1.1, rainyDays: 6, sunnyDays: 17 },
      { month: 'April', avgHighF: 56, avgLowF: 26, avgPrecipitationInches: 0.8, rainyDays: 5, sunnyDays: 19 },
      { month: 'May', avgHighF: 66, avgLowF: 34, avgPrecipitationInches: 0.7, rainyDays: 5, sunnyDays: 22 },
      { month: 'June', avgHighF: 77, avgLowF: 41, avgPrecipitationInches: 0.4, rainyDays: 3, sunnyDays: 26 },
      { month: 'July', avgHighF: 83, avgLowF: 50, avgPrecipitationInches: 1.1, rainyDays: 7, sunnyDays: 20 },
      { month: 'August', avgHighF: 80, avgLowF: 48, avgPrecipitationInches: 1.4, rainyDays: 8, sunnyDays: 19 },
      { month: 'September', avgHighF: 73, avgLowF: 39, avgPrecipitationInches: 1.0, rainyDays: 5, sunnyDays: 22 },
      { month: 'October', avgHighF: 60, avgLowF: 28, avgPrecipitationInches: 1.0, rainyDays: 5, sunnyDays: 21 },
      { month: 'November', avgHighF: 46, avgLowF: 18, avgPrecipitationInches: 0.8, rainyDays: 4, sunnyDays: 20 },
      { month: 'December', avgHighF: 37, avgLowF: 10, avgPrecipitationInches: 1.0, rainyDays: 5, sunnyDays: 18 },
    ],
  },
  {
    slug: 'canyonlands',
    monthly: [
      { month: 'January', avgHighF: 41, avgLowF: 19, avgPrecipitationInches: 0.5, rainyDays: 4, sunnyDays: 21 },
      { month: 'February', avgHighF: 49, avgLowF: 26, avgPrecipitationInches: 0.5, rainyDays: 4, sunnyDays: 19 },
      { month: 'March', avgHighF: 60, avgLowF: 34, avgPrecipitationInches: 0.7, rainyDays: 5, sunnyDays: 20 },
      { month: 'April', avgHighF: 70, avgLowF: 42, avgPrecipitationInches: 0.7, rainyDays: 4, sunnyDays: 21 },
      { month: 'May', avgHighF: 81, avgLowF: 51, avgPrecipitationInches: 0.6, rainyDays: 3, sunnyDays: 25 },
      { month: 'June', avgHighF: 94, avgLowF: 60, avgPrecipitationInches: 0.3, rainyDays: 2, sunnyDays: 27 },
      { month: 'July', avgHighF: 99, avgLowF: 67, avgPrecipitationInches: 0.7, rainyDays: 4, sunnyDays: 24 },
      { month: 'August', avgHighF: 96, avgLowF: 64, avgPrecipitationInches: 0.7, rainyDays: 5, sunnyDays: 23 },
      { month: 'September', avgHighF: 86, avgLowF: 53, avgPrecipitationInches: 0.7, rainyDays: 4, sunnyDays: 23 },
      { month: 'October', avgHighF: 70, avgLowF: 40, avgPrecipitationInches: 0.9, rainyDays: 4, sunnyDays: 22 },
      { month: 'November', avgHighF: 54, avgLowF: 28, avgPrecipitationInches: 0.5, rainyDays: 3, sunnyDays: 22 },
      { month: 'December', avgHighF: 41, avgLowF: 19, avgPrecipitationInches: 0.4, rainyDays: 4, sunnyDays: 20 },
    ],
  },
  {
    slug: 'joshua-tree',
    monthly: [
      { month: 'January', avgHighF: 57, avgLowF: 32, avgPrecipitationInches: 0.6, rainyDays: 3, sunnyDays: 23 },
      { month: 'February', avgHighF: 60, avgLowF: 35, avgPrecipitationInches: 0.7, rainyDays: 3, sunnyDays: 21 },
      { month: 'March', avgHighF: 67, avgLowF: 40, avgPrecipitationInches: 0.5, rainyDays: 3, sunnyDays: 23 },
      { month: 'April', avgHighF: 75, avgLowF: 47, avgPrecipitationInches: 0.2, rainyDays: 1, sunnyDays: 26 },
      { month: 'May', avgHighF: 85, avgLowF: 55, avgPrecipitationInches: 0.1, rainyDays: 1, sunnyDays: 28 },
      { month: 'June', avgHighF: 96, avgLowF: 64, avgPrecipitationInches: 0.0, rainyDays: 0, sunnyDays: 30 },
      { month: 'July', avgHighF: 101, avgLowF: 71, avgPrecipitationInches: 0.3, rainyDays: 2, sunnyDays: 27 },
      { month: 'August', avgHighF: 99, avgLowF: 69, avgPrecipitationInches: 0.4, rainyDays: 2, sunnyDays: 27 },
      { month: 'September', avgHighF: 93, avgLowF: 61, avgPrecipitationInches: 0.3, rainyDays: 1, sunnyDays: 27 },
      { month: 'October', avgHighF: 80, avgLowF: 49, avgPrecipitationInches: 0.3, rainyDays: 2, sunnyDays: 26 },
      { month: 'November', avgHighF: 66, avgLowF: 38, avgPrecipitationInches: 0.3, rainyDays: 2, sunnyDays: 24 },
      { month: 'December', avgHighF: 56, avgLowF: 31, avgPrecipitationInches: 0.5, rainyDays: 3, sunnyDays: 22 },
    ],
  },
  {
    slug: 'saguaro',
    monthly: [
      { month: 'January', avgHighF: 65, avgLowF: 39, avgPrecipitationInches: 0.9, rainyDays: 4, sunnyDays: 22 },
      { month: 'February', avgHighF: 68, avgLowF: 41, avgPrecipitationInches: 0.8, rainyDays: 4, sunnyDays: 21 },
      { month: 'March', avgHighF: 74, avgLowF: 46, avgPrecipitationInches: 0.7, rainyDays: 3, sunnyDays: 24 },
      { month: 'April', avgHighF: 82, avgLowF: 52, avgPrecipitationInches: 0.3, rainyDays: 2, sunnyDays: 26 },
      { month: 'May', avgHighF: 92, avgLowF: 61, avgPrecipitationInches: 0.2, rainyDays: 1, sunnyDays: 28 },
      { month: 'June', avgHighF: 101, avgLowF: 70, avgPrecipitationInches: 0.2, rainyDays: 1, sunnyDays: 28 },
      { month: 'July', avgHighF: 100, avgLowF: 75, avgPrecipitationInches: 2.2, rainyDays: 10, sunnyDays: 17 },
      { month: 'August', avgHighF: 97, avgLowF: 73, avgPrecipitationInches: 2.1, rainyDays: 10, sunnyDays: 18 },
      { month: 'September', avgHighF: 96, avgLowF: 68, avgPrecipitationInches: 1.3, rainyDays: 5, sunnyDays: 23 },
      { month: 'October', avgHighF: 87, avgLowF: 56, avgPrecipitationInches: 0.8, rainyDays: 3, sunnyDays: 25 },
      { month: 'November', avgHighF: 74, avgLowF: 45, avgPrecipitationInches: 0.5, rainyDays: 3, sunnyDays: 24 },
      { month: 'December', avgHighF: 64, avgLowF: 39, avgPrecipitationInches: 0.9, rainyDays: 4, sunnyDays: 22 },
    ],
  },
  {
    slug: 'yosemite',
    monthly: [
      { month: 'January', avgHighF: 48, avgLowF: 28, avgPrecipitationInches: 5.5, rainyDays: 10, sunnyDays: 13 },
      { month: 'February', avgHighF: 52, avgLowF: 29, avgPrecipitationInches: 5.2, rainyDays: 10, sunnyDays: 12 },
      { month: 'March', avgHighF: 55, avgLowF: 31, avgPrecipitationInches: 4.8, rainyDays: 10, sunnyDays: 13 },
      { month: 'April', avgHighF: 62, avgLowF: 35, avgPrecipitationInches: 2.5, rainyDays: 7, sunnyDays: 17 },
      { month: 'May', avgHighF: 71, avgLowF: 42, avgPrecipitationInches: 1.2, rainyDays: 4, sunnyDays: 23 },
      { month: 'June', avgHighF: 81, avgLowF: 49, avgPrecipitationInches: 0.5, rainyDays: 1, sunnyDays: 28 },
      { month: 'July', avgHighF: 90, avgLowF: 55, avgPrecipitationInches: 0.3, rainyDays: 1, sunnyDays: 30 },
      { month: 'August', avgHighF: 89, avgLowF: 54, avgPrecipitationInches: 0.2, rainyDays: 1, sunnyDays: 30 },
      { month: 'September', avgHighF: 83, avgLowF: 48, avgPrecipitationInches: 0.6, rainyDays: 2, sunnyDays: 27 },
      { month: 'October', avgHighF: 70, avgLowF: 39, avgPrecipitationInches: 1.5, rainyDays: 4, sunnyDays: 23 },
      { month: 'November', avgHighF: 55, avgLowF: 31, avgPrecipitationInches: 3.6, rainyDays: 7, sunnyDays: 16 },
      { month: 'December', avgHighF: 47, avgLowF: 27, avgPrecipitationInches: 5.0, rainyDays: 10, sunnyDays: 13 },
    ],
  },
  {
    slug: 'sequoia-kings-canyon',
    monthly: [
      { month: 'January', avgHighF: 45, avgLowF: 26, avgPrecipitationInches: 4.8, rainyDays: 9, sunnyDays: 14 },
      { month: 'February', avgHighF: 48, avgLowF: 27, avgPrecipitationInches: 4.5, rainyDays: 9, sunnyDays: 13 },
      { month: 'March', avgHighF: 52, avgLowF: 29, avgPrecipitationInches: 4.2, rainyDays: 9, sunnyDays: 14 },
      { month: 'April', avgHighF: 59, avgLowF: 33, avgPrecipitationInches: 2.2, rainyDays: 6, sunnyDays: 18 },
      { month: 'May', avgHighF: 68, avgLowF: 40, avgPrecipitationInches: 1.0, rainyDays: 4, sunnyDays: 23 },
      { month: 'June', avgHighF: 79, avgLowF: 47, avgPrecipitationInches: 0.3, rainyDays: 1, sunnyDays: 28 },
      { month: 'July', avgHighF: 87, avgLowF: 53, avgPrecipitationInches: 0.2, rainyDays: 1, sunnyDays: 30 },
      { month: 'August', avgHighF: 86, avgLowF: 52, avgPrecipitationInches: 0.2, rainyDays: 1, sunnyDays: 30 },
      { month: 'September', avgHighF: 79, avgLowF: 46, avgPrecipitationInches: 0.5, rainyDays: 2, sunnyDays: 27 },
      { month: 'October', avgHighF: 67, avgLowF: 37, avgPrecipitationInches: 1.3, rainyDays: 4, sunnyDays: 23 },
      { month: 'November', avgHighF: 53, avgLowF: 29, avgPrecipitationInches: 3.0, rainyDays: 7, sunnyDays: 17 },
      { month: 'December', avgHighF: 45, avgLowF: 25, avgPrecipitationInches: 4.3, rainyDays: 9, sunnyDays: 14 },
    ],
  },
  {
    slug: 'olympic',
    monthly: [
      { month: 'January', avgHighF: 44, avgLowF: 34, avgPrecipitationInches: 10.8, rainyDays: 19, sunnyDays: 4 },
      { month: 'February', avgHighF: 47, avgLowF: 34, avgPrecipitationInches: 8.2, rainyDays: 16, sunnyDays: 5 },
      { month: 'March', avgHighF: 50, avgLowF: 35, avgPrecipitationInches: 7.5, rainyDays: 17, sunnyDays: 6 },
      { month: 'April', avgHighF: 55, avgLowF: 37, avgPrecipitationInches: 5.4, rainyDays: 14, sunnyDays: 8 },
      { month: 'May', avgHighF: 60, avgLowF: 42, avgPrecipitationInches: 3.5, rainyDays: 12, sunnyDays: 12 },
      { month: 'June', avgHighF: 64, avgLowF: 47, avgPrecipitationInches: 2.6, rainyDays: 10, sunnyDays: 14 },
      { month: 'July', avgHighF: 69, avgLowF: 50, avgPrecipitationInches: 1.2, rainyDays: 5, sunnyDays: 21 },
      { month: 'August', avgHighF: 70, avgLowF: 50, avgPrecipitationInches: 1.4, rainyDays: 5, sunnyDays: 21 },
      { month: 'September', avgHighF: 66, avgLowF: 47, avgPrecipitationInches: 2.8, rainyDays: 8, sunnyDays: 16 },
      { month: 'October', avgHighF: 56, avgLowF: 41, avgPrecipitationInches: 6.8, rainyDays: 15, sunnyDays: 8 },
      { month: 'November', avgHighF: 48, avgLowF: 37, avgPrecipitationInches: 10.2, rainyDays: 19, sunnyDays: 4 },
      { month: 'December', avgHighF: 43, avgLowF: 33, avgPrecipitationInches: 11.5, rainyDays: 20, sunnyDays: 3 },
    ],
  },
  {
    slug: 'mount-rainier',
    monthly: [
      { month: 'January', avgHighF: 36, avgLowF: 24, avgPrecipitationInches: 10.5, rainyDays: 18, sunnyDays: 4 },
      { month: 'February', avgHighF: 38, avgLowF: 24, avgPrecipitationInches: 7.8, rainyDays: 15, sunnyDays: 5 },
      { month: 'March', avgHighF: 41, avgLowF: 25, avgPrecipitationInches: 7.2, rainyDays: 16, sunnyDays: 6 },
      { month: 'April', avgHighF: 48, avgLowF: 30, avgPrecipitationInches: 5.0, rainyDays: 14, sunnyDays: 8 },
      { month: 'May', avgHighF: 56, avgLowF: 36, avgPrecipitationInches: 3.2, rainyDays: 12, sunnyDays: 12 },
      { month: 'June', avgHighF: 62, avgLowF: 42, avgPrecipitationInches: 2.4, rainyDays: 10, sunnyDays: 15 },
      { month: 'July', avgHighF: 69, avgLowF: 47, avgPrecipitationInches: 1.0, rainyDays: 5, sunnyDays: 22 },
      { month: 'August', avgHighF: 70, avgLowF: 47, avgPrecipitationInches: 1.3, rainyDays: 5, sunnyDays: 21 },
      { month: 'September', avgHighF: 62, avgLowF: 42, avgPrecipitationInches: 3.0, rainyDays: 9, sunnyDays: 15 },
      { month: 'October', avgHighF: 50, avgLowF: 34, avgPrecipitationInches: 6.5, rainyDays: 14, sunnyDays: 8 },
      { month: 'November', avgHighF: 39, avgLowF: 27, avgPrecipitationInches: 9.8, rainyDays: 18, sunnyDays: 4 },
      { month: 'December', avgHighF: 34, avgLowF: 23, avgPrecipitationInches: 10.8, rainyDays: 19, sunnyDays: 3 },
    ],
  },
  {
    slug: 'great-smoky-mountains',
    monthly: [
      { month: 'January', avgHighF: 47, avgLowF: 25, avgPrecipitationInches: 4.2, rainyDays: 10, sunnyDays: 10 },
      { month: 'February', avgHighF: 51, avgLowF: 27, avgPrecipitationInches: 4.0, rainyDays: 10, sunnyDays: 10 },
      { month: 'March', avgHighF: 59, avgLowF: 34, avgPrecipitationInches: 4.5, rainyDays: 11, sunnyDays: 11 },
      { month: 'April', avgHighF: 68, avgLowF: 41, avgPrecipitationInches: 4.2, rainyDays: 10, sunnyDays: 12 },
      { month: 'May', avgHighF: 75, avgLowF: 50, avgPrecipitationInches: 4.6, rainyDays: 12, sunnyDays: 12 },
      { month: 'June', avgHighF: 81, avgLowF: 58, avgPrecipitationInches: 5.2, rainyDays: 12, sunnyDays: 13 },
      { month: 'July', avgHighF: 84, avgLowF: 62, avgPrecipitationInches: 5.5, rainyDays: 13, sunnyDays: 13 },
      { month: 'August', avgHighF: 83, avgLowF: 61, avgPrecipitationInches: 4.8, rainyDays: 12, sunnyDays: 14 },
      { month: 'September', avgHighF: 78, avgLowF: 55, avgPrecipitationInches: 3.8, rainyDays: 9, sunnyDays: 15 },
      { month: 'October', avgHighF: 68, avgLowF: 43, avgPrecipitationInches: 3.2, rainyDays: 8, sunnyDays: 16 },
      { month: 'November', avgHighF: 57, avgLowF: 33, avgPrecipitationInches: 3.8, rainyDays: 9, sunnyDays: 12 },
      { month: 'December', avgHighF: 49, avgLowF: 27, avgPrecipitationInches: 4.0, rainyDays: 10, sunnyDays: 10 },
    ],
  },
  {
    slug: 'everglades',
    monthly: [
      { month: 'January', avgHighF: 77, avgLowF: 57, avgPrecipitationInches: 1.8, rainyDays: 5, sunnyDays: 21 },
      { month: 'February', avgHighF: 79, avgLowF: 58, avgPrecipitationInches: 1.5, rainyDays: 4, sunnyDays: 21 },
      { month: 'March', avgHighF: 82, avgLowF: 61, avgPrecipitationInches: 1.9, rainyDays: 5, sunnyDays: 22 },
      { month: 'April', avgHighF: 85, avgLowF: 65, avgPrecipitationInches: 2.6, rainyDays: 6, sunnyDays: 22 },
      { month: 'May', avgHighF: 88, avgLowF: 70, avgPrecipitationInches: 5.2, rainyDays: 11, sunnyDays: 16 },
      { month: 'June', avgHighF: 90, avgLowF: 74, avgPrecipitationInches: 8.8, rainyDays: 17, sunnyDays: 10 },
      { month: 'July', avgHighF: 91, avgLowF: 75, avgPrecipitationInches: 8.2, rainyDays: 18, sunnyDays: 10 },
      { month: 'August', avgHighF: 91, avgLowF: 75, avgPrecipitationInches: 8.5, rainyDays: 18, sunnyDays: 10 },
      { month: 'September', avgHighF: 90, avgLowF: 74, avgPrecipitationInches: 8.0, rainyDays: 17, sunnyDays: 10 },
      { month: 'October', avgHighF: 86, avgLowF: 70, avgPrecipitationInches: 5.5, rainyDays: 12, sunnyDays: 15 },
      { month: 'November', avgHighF: 82, avgLowF: 63, avgPrecipitationInches: 2.5, rainyDays: 6, sunnyDays: 20 },
      { month: 'December', avgHighF: 78, avgLowF: 58, avgPrecipitationInches: 1.6, rainyDays: 5, sunnyDays: 21 },
    ],
  },
  {
    slug: 'acadia',
    monthly: [
      { month: 'January', avgHighF: 31, avgLowF: 12, avgPrecipitationInches: 3.8, rainyDays: 11, sunnyDays: 9 },
      { month: 'February', avgHighF: 33, avgLowF: 13, avgPrecipitationInches: 3.2, rainyDays: 10, sunnyDays: 9 },
      { month: 'March', avgHighF: 40, avgLowF: 22, avgPrecipitationInches: 3.8, rainyDays: 11, sunnyDays: 10 },
      { month: 'April', avgHighF: 51, avgLowF: 33, avgPrecipitationInches: 3.8, rainyDays: 11, sunnyDays: 10 },
      { month: 'May', avgHighF: 62, avgLowF: 42, avgPrecipitationInches: 3.6, rainyDays: 12, sunnyDays: 11 },
      { month: 'June', avgHighF: 71, avgLowF: 51, avgPrecipitationInches: 3.4, rainyDays: 11, sunnyDays: 13 },
      { month: 'July', avgHighF: 77, avgLowF: 57, avgPrecipitationInches: 3.1, rainyDays: 10, sunnyDays: 15 },
      { month: 'August', avgHighF: 76, avgLowF: 56, avgPrecipitationInches: 3.0, rainyDays: 9, sunnyDays: 16 },
      { month: 'September', avgHighF: 69, avgLowF: 49, avgPrecipitationInches: 3.6, rainyDays: 9, sunnyDays: 14 },
      { month: 'October', avgHighF: 56, avgLowF: 39, avgPrecipitationInches: 4.2, rainyDays: 10, sunnyDays: 12 },
      { month: 'November', avgHighF: 45, avgLowF: 30, avgPrecipitationInches: 4.5, rainyDays: 11, sunnyDays: 8 },
      { month: 'December', avgHighF: 35, avgLowF: 18, avgPrecipitationInches: 4.0, rainyDays: 11, sunnyDays: 8 },
    ],
  },
  {
    slug: 'denali',
    monthly: [
      { month: 'January', avgHighF: 8, avgLowF: -10, avgPrecipitationInches: 0.6, rainyDays: 7, sunnyDays: 10 },
      { month: 'February', avgHighF: 12, avgLowF: -7, avgPrecipitationInches: 0.5, rainyDays: 6, sunnyDays: 11 },
      { month: 'March', avgHighF: 22, avgLowF: -2, avgPrecipitationInches: 0.4, rainyDays: 5, sunnyDays: 14 },
      { month: 'April', avgHighF: 35, avgLowF: 14, avgPrecipitationInches: 0.5, rainyDays: 5, sunnyDays: 14 },
      { month: 'May', avgHighF: 51, avgLowF: 30, avgPrecipitationInches: 0.8, rainyDays: 7, sunnyDays: 14 },
      { month: 'June', avgHighF: 63, avgLowF: 42, avgPrecipitationInches: 1.8, rainyDays: 11, sunnyDays: 12 },
      { month: 'July', avgHighF: 65, avgLowF: 46, avgPrecipitationInches: 2.8, rainyDays: 14, sunnyDays: 10 },
      { month: 'August', avgHighF: 60, avgLowF: 42, avgPrecipitationInches: 2.5, rainyDays: 13, sunnyDays: 10 },
      { month: 'September', avgHighF: 49, avgLowF: 32, avgPrecipitationInches: 1.5, rainyDays: 10, sunnyDays: 11 },
      { month: 'October', avgHighF: 29, avgLowF: 13, avgPrecipitationInches: 0.8, rainyDays: 8, sunnyDays: 11 },
      { month: 'November', avgHighF: 14, avgLowF: -3, avgPrecipitationInches: 0.7, rainyDays: 7, sunnyDays: 9 },
      { month: 'December', avgHighF: 7, avgLowF: -11, avgPrecipitationInches: 0.7, rainyDays: 7, sunnyDays: 8 },
    ],
  },
  {
    slug: 'haleakala',
    monthly: [
      { month: 'January', avgHighF: 62, avgLowF: 44, avgPrecipitationInches: 3.8, rainyDays: 10, sunnyDays: 15 },
      { month: 'February', avgHighF: 62, avgLowF: 43, avgPrecipitationInches: 3.2, rainyDays: 9, sunnyDays: 14 },
      { month: 'March', avgHighF: 63, avgLowF: 44, avgPrecipitationInches: 4.0, rainyDays: 12, sunnyDays: 13 },
      { month: 'April', avgHighF: 64, avgLowF: 45, avgPrecipitationInches: 3.2, rainyDays: 11, sunnyDays: 13 },
      { month: 'May', avgHighF: 66, avgLowF: 47, avgPrecipitationInches: 1.5, rainyDays: 7, sunnyDays: 18 },
      { month: 'June', avgHighF: 69, avgLowF: 50, avgPrecipitationInches: 0.6, rainyDays: 4, sunnyDays: 22 },
      { month: 'July', avgHighF: 70, avgLowF: 51, avgPrecipitationInches: 0.8, rainyDays: 5, sunnyDays: 21 },
      { month: 'August', avgHighF: 71, avgLowF: 52, avgPrecipitationInches: 0.8, rainyDays: 5, sunnyDays: 21 },
      { month: 'September', avgHighF: 71, avgLowF: 51, avgPrecipitationInches: 0.7, rainyDays: 5, sunnyDays: 21 },
      { month: 'October', avgHighF: 69, avgLowF: 49, avgPrecipitationInches: 1.8, rainyDays: 8, sunnyDays: 17 },
      { month: 'November', avgHighF: 66, avgLowF: 47, avgPrecipitationInches: 3.0, rainyDays: 10, sunnyDays: 14 },
      { month: 'December', avgHighF: 63, avgLowF: 45, avgPrecipitationInches: 3.8, rainyDays: 11, sunnyDays: 14 },
    ],
  },
  {
    slug: 'badlands',
    monthly: [
      { month: 'January', avgHighF: 34, avgLowF: 11, avgPrecipitationInches: 0.4, rainyDays: 5, sunnyDays: 18 },
      { month: 'February', avgHighF: 38, avgLowF: 14, avgPrecipitationInches: 0.5, rainyDays: 5, sunnyDays: 17 },
      { month: 'March', avgHighF: 48, avgLowF: 23, avgPrecipitationInches: 1.0, rainyDays: 7, sunnyDays: 16 },
      { month: 'April', avgHighF: 58, avgLowF: 32, avgPrecipitationInches: 1.8, rainyDays: 9, sunnyDays: 14 },
      { month: 'May', avgHighF: 69, avgLowF: 43, avgPrecipitationInches: 2.8, rainyDays: 11, sunnyDays: 14 },
      { month: 'June', avgHighF: 80, avgLowF: 53, avgPrecipitationInches: 2.9, rainyDays: 10, sunnyDays: 16 },
      { month: 'July', avgHighF: 89, avgLowF: 59, avgPrecipitationInches: 2.1, rainyDays: 8, sunnyDays: 20 },
      { month: 'August', avgHighF: 89, avgLowF: 57, avgPrecipitationInches: 1.5, rainyDays: 7, sunnyDays: 21 },
      { month: 'September', avgHighF: 78, avgLowF: 46, avgPrecipitationInches: 1.2, rainyDays: 6, sunnyDays: 19 },
      { month: 'October', avgHighF: 62, avgLowF: 33, avgPrecipitationInches: 1.2, rainyDays: 6, sunnyDays: 19 },
      { month: 'November', avgHighF: 47, avgLowF: 21, avgPrecipitationInches: 0.6, rainyDays: 5, sunnyDays: 17 },
      { month: 'December', avgHighF: 35, avgLowF: 12, avgPrecipitationInches: 0.4, rainyDays: 5, sunnyDays: 17 },
    ],
  },
  {
    slug: 'big-bend',
    monthly: [
      { month: 'January', avgHighF: 61, avgLowF: 35, avgPrecipitationInches: 0.4, rainyDays: 3, sunnyDays: 23 },
      { month: 'February', avgHighF: 66, avgLowF: 39, avgPrecipitationInches: 0.4, rainyDays: 3, sunnyDays: 21 },
      { month: 'March', avgHighF: 75, avgLowF: 46, avgPrecipitationInches: 0.4, rainyDays: 2, sunnyDays: 24 },
      { month: 'April', avgHighF: 83, avgLowF: 53, avgPrecipitationInches: 0.6, rainyDays: 3, sunnyDays: 24 },
      { month: 'May', avgHighF: 90, avgLowF: 61, avgPrecipitationInches: 1.2, rainyDays: 4, sunnyDays: 24 },
      { month: 'June', avgHighF: 95, avgLowF: 67, avgPrecipitationInches: 1.8, rainyDays: 5, sunnyDays: 23 },
      { month: 'July', avgHighF: 94, avgLowF: 68, avgPrecipitationInches: 2.1, rainyDays: 7, sunnyDays: 20 },
      { month: 'August', avgHighF: 92, avgLowF: 66, avgPrecipitationInches: 2.3, rainyDays: 8, sunnyDays: 19 },
      { month: 'September', avgHighF: 87, avgLowF: 61, avgPrecipitationInches: 2.0, rainyDays: 6, sunnyDays: 20 },
      { month: 'October', avgHighF: 79, avgLowF: 52, avgPrecipitationInches: 1.6, rainyDays: 5, sunnyDays: 22 },
      { month: 'November', avgHighF: 68, avgLowF: 42, avgPrecipitationInches: 0.6, rainyDays: 3, sunnyDays: 23 },
      { month: 'December', avgHighF: 61, avgLowF: 35, avgPrecipitationInches: 0.5, rainyDays: 3, sunnyDays: 22 },
    ],
  },
  {
    slug: 'black-canyon-of-the-gunnison',
    monthly: [
      { month: 'January', avgHighF: 35, avgLowF: 10, avgPrecipitationInches: 1.0, rainyDays: 7, sunnyDays: 17 },
      { month: 'February', avgHighF: 39, avgLowF: 14, avgPrecipitationInches: 0.9, rainyDays: 6, sunnyDays: 16 },
      { month: 'March', avgHighF: 48, avgLowF: 22, avgPrecipitationInches: 1.1, rainyDays: 7, sunnyDays: 17 },
      { month: 'April', avgHighF: 57, avgLowF: 29, avgPrecipitationInches: 1.2, rainyDays: 7, sunnyDays: 17 },
      { month: 'May', avgHighF: 67, avgLowF: 37, avgPrecipitationInches: 1.3, rainyDays: 8, sunnyDays: 18 },
      { month: 'June', avgHighF: 78, avgLowF: 44, avgPrecipitationInches: 0.7, rainyDays: 5, sunnyDays: 23 },
      { month: 'July', avgHighF: 85, avgLowF: 52, avgPrecipitationInches: 1.2, rainyDays: 7, sunnyDays: 20 },
      { month: 'August', avgHighF: 82, avgLowF: 50, avgPrecipitationInches: 1.4, rainyDays: 8, sunnyDays: 19 },
      { month: 'September', avgHighF: 74, avgLowF: 42, avgPrecipitationInches: 1.2, rainyDays: 6, sunnyDays: 21 },
      { month: 'October', avgHighF: 61, avgLowF: 31, avgPrecipitationInches: 1.2, rainyDays: 6, sunnyDays: 20 },
      { month: 'November', avgHighF: 45, avgLowF: 19, avgPrecipitationInches: 1.0, rainyDays: 6, sunnyDays: 18 },
      { month: 'December', avgHighF: 35, avgLowF: 10, avgPrecipitationInches: 1.0, rainyDays: 7, sunnyDays: 16 },
    ],
  },
  {
    slug: 'capitol-reef',
    monthly: [
      { month: 'January', avgHighF: 40, avgLowF: 18, avgPrecipitationInches: 0.5, rainyDays: 4, sunnyDays: 21 },
      { month: 'February', avgHighF: 47, avgLowF: 24, avgPrecipitationInches: 0.5, rainyDays: 4, sunnyDays: 19 },
      { month: 'March', avgHighF: 58, avgLowF: 31, avgPrecipitationInches: 0.6, rainyDays: 4, sunnyDays: 21 },
      { month: 'April', avgHighF: 66, avgLowF: 38, avgPrecipitationInches: 0.5, rainyDays: 4, sunnyDays: 22 },
      { month: 'May', avgHighF: 77, avgLowF: 47, avgPrecipitationInches: 0.6, rainyDays: 4, sunnyDays: 24 },
      { month: 'June', avgHighF: 88, avgLowF: 55, avgPrecipitationInches: 0.4, rainyDays: 2, sunnyDays: 27 },
      { month: 'July', avgHighF: 93, avgLowF: 63, avgPrecipitationInches: 0.8, rainyDays: 5, sunnyDays: 23 },
      { month: 'August', avgHighF: 90, avgLowF: 61, avgPrecipitationInches: 0.9, rainyDays: 5, sunnyDays: 22 },
      { month: 'September', avgHighF: 81, avgLowF: 51, avgPrecipitationInches: 0.8, rainyDays: 4, sunnyDays: 23 },
      { month: 'October', avgHighF: 66, avgLowF: 38, avgPrecipitationInches: 0.8, rainyDays: 4, sunnyDays: 22 },
      { month: 'November', avgHighF: 51, avgLowF: 27, avgPrecipitationInches: 0.5, rainyDays: 3, sunnyDays: 22 },
      { month: 'December', avgHighF: 40, avgLowF: 18, avgPrecipitationInches: 0.4, rainyDays: 4, sunnyDays: 20 },
    ],
  },
  {
    slug: 'carlsbad-caverns',
    monthly: [
      { month: 'January', avgHighF: 56, avgLowF: 30, avgPrecipitationInches: 0.5, rainyDays: 3, sunnyDays: 23 },
      { month: 'February', avgHighF: 61, avgLowF: 34, avgPrecipitationInches: 0.5, rainyDays: 3, sunnyDays: 21 },
      { month: 'March', avgHighF: 69, avgLowF: 40, avgPrecipitationInches: 0.4, rainyDays: 2, sunnyDays: 24 },
      { month: 'April', avgHighF: 78, avgLowF: 49, avgPrecipitationInches: 0.5, rainyDays: 3, sunnyDays: 24 },
      { month: 'May', avgHighF: 87, avgLowF: 58, avgPrecipitationInches: 1.1, rainyDays: 4, sunnyDays: 24 },
      { month: 'June', avgHighF: 94, avgLowF: 66, avgPrecipitationInches: 1.4, rainyDays: 5, sunnyDays: 23 },
      { month: 'July', avgHighF: 93, avgLowF: 67, avgPrecipitationInches: 2.2, rainyDays: 8, sunnyDays: 19 },
      { month: 'August', avgHighF: 90, avgLowF: 66, avgPrecipitationInches: 2.5, rainyDays: 9, sunnyDays: 18 },
      { month: 'September', avgHighF: 84, avgLowF: 59, avgPrecipitationInches: 2.3, rainyDays: 7, sunnyDays: 19 },
      { month: 'October', avgHighF: 75, avgLowF: 49, avgPrecipitationInches: 1.4, rainyDays: 5, sunnyDays: 22 },
      { month: 'November', avgHighF: 64, avgLowF: 38, avgPrecipitationInches: 0.6, rainyDays: 3, sunnyDays: 23 },
      { month: 'December', avgHighF: 56, avgLowF: 30, avgPrecipitationInches: 0.6, rainyDays: 3, sunnyDays: 22 },
    ],
  },
  {
    slug: 'great-sand-dunes',
    monthly: [
      { month: 'January', avgHighF: 37, avgLowF: 8, avgPrecipitationInches: 0.4, rainyDays: 4, sunnyDays: 21 },
      { month: 'February', avgHighF: 40, avgLowF: 12, avgPrecipitationInches: 0.4, rainyDays: 4, sunnyDays: 19 },
      { month: 'March', avgHighF: 49, avgLowF: 20, avgPrecipitationInches: 0.6, rainyDays: 5, sunnyDays: 20 },
      { month: 'April', avgHighF: 57, avgLowF: 27, avgPrecipitationInches: 0.8, rainyDays: 6, sunnyDays: 19 },
      { month: 'May', avgHighF: 66, avgLowF: 36, avgPrecipitationInches: 1.1, rainyDays: 7, sunnyDays: 19 },
      { month: 'June', avgHighF: 77, avgLowF: 43, avgPrecipitationInches: 0.8, rainyDays: 5, sunnyDays: 23 },
      { month: 'July', avgHighF: 82, avgLowF: 50, avgPrecipitationInches: 1.5, rainyDays: 9, sunnyDays: 18 },
      { month: 'August', avgHighF: 79, avgLowF: 48, avgPrecipitationInches: 1.7, rainyDays: 9, sunnyDays: 18 },
      { month: 'September', avgHighF: 72, avgLowF: 40, avgPrecipitationInches: 1.0, rainyDays: 6, sunnyDays: 21 },
      { month: 'October', avgHighF: 60, avgLowF: 28, avgPrecipitationInches: 0.8, rainyDays: 4, sunnyDays: 22 },
      { month: 'November', avgHighF: 46, avgLowF: 17, avgPrecipitationInches: 0.5, rainyDays: 4, sunnyDays: 21 },
      { month: 'December', avgHighF: 36, avgLowF: 8, avgPrecipitationInches: 0.4, rainyDays: 4, sunnyDays: 20 },
    ],
  },
  {
    slug: 'guadalupe-mountains',
    monthly: [
      { month: 'January', avgHighF: 55, avgLowF: 30, avgPrecipitationInches: 0.5, rainyDays: 3, sunnyDays: 23 },
      { month: 'February', avgHighF: 59, avgLowF: 33, avgPrecipitationInches: 0.5, rainyDays: 3, sunnyDays: 21 },
      { month: 'March', avgHighF: 66, avgLowF: 39, avgPrecipitationInches: 0.4, rainyDays: 2, sunnyDays: 24 },
      { month: 'April', avgHighF: 74, avgLowF: 47, avgPrecipitationInches: 0.5, rainyDays: 3, sunnyDays: 24 },
      { month: 'May', avgHighF: 82, avgLowF: 56, avgPrecipitationInches: 1.2, rainyDays: 5, sunnyDays: 23 },
      { month: 'June', avgHighF: 90, avgLowF: 63, avgPrecipitationInches: 1.6, rainyDays: 5, sunnyDays: 23 },
      { month: 'July', avgHighF: 89, avgLowF: 64, avgPrecipitationInches: 2.5, rainyDays: 9, sunnyDays: 18 },
      { month: 'August', avgHighF: 86, avgLowF: 62, avgPrecipitationInches: 2.8, rainyDays: 9, sunnyDays: 18 },
      { month: 'September', avgHighF: 81, avgLowF: 56, avgPrecipitationInches: 2.2, rainyDays: 7, sunnyDays: 19 },
      { month: 'October', avgHighF: 73, avgLowF: 47, avgPrecipitationInches: 1.3, rainyDays: 5, sunnyDays: 22 },
      { month: 'November', avgHighF: 63, avgLowF: 37, avgPrecipitationInches: 0.6, rainyDays: 3, sunnyDays: 23 },
      { month: 'December', avgHighF: 55, avgLowF: 30, avgPrecipitationInches: 0.6, rainyDays: 3, sunnyDays: 22 },
    ],
  },
  {
    slug: 'mesa-verde',
    monthly: [
      { month: 'January', avgHighF: 38, avgLowF: 16, avgPrecipitationInches: 1.2, rainyDays: 6, sunnyDays: 18 },
      { month: 'February', avgHighF: 42, avgLowF: 20, avgPrecipitationInches: 1.1, rainyDays: 6, sunnyDays: 17 },
      { month: 'March', avgHighF: 50, avgLowF: 26, avgPrecipitationInches: 1.2, rainyDays: 6, sunnyDays: 18 },
      { month: 'April', avgHighF: 59, avgLowF: 32, avgPrecipitationInches: 1.0, rainyDays: 5, sunnyDays: 20 },
      { month: 'May', avgHighF: 70, avgLowF: 41, avgPrecipitationInches: 1.0, rainyDays: 5, sunnyDays: 22 },
      { month: 'June', avgHighF: 82, avgLowF: 50, avgPrecipitationInches: 0.5, rainyDays: 3, sunnyDays: 26 },
      { month: 'July', avgHighF: 87, avgLowF: 57, avgPrecipitationInches: 1.5, rainyDays: 8, sunnyDays: 19 },
      { month: 'August', avgHighF: 84, avgLowF: 55, avgPrecipitationInches: 1.8, rainyDays: 9, sunnyDays: 18 },
      { month: 'September', avgHighF: 76, avgLowF: 47, avgPrecipitationInches: 1.4, rainyDays: 6, sunnyDays: 21 },
      { month: 'October', avgHighF: 63, avgLowF: 36, avgPrecipitationInches: 1.3, rainyDays: 5, sunnyDays: 21 },
      { month: 'November', avgHighF: 48, avgLowF: 24, avgPrecipitationInches: 1.1, rainyDays: 5, sunnyDays: 19 },
      { month: 'December', avgHighF: 38, avgLowF: 16, avgPrecipitationInches: 1.2, rainyDays: 6, sunnyDays: 17 },
    ],
  },
  {
    slug: 'petrified-forest',
    monthly: [
      { month: 'January', avgHighF: 46, avgLowF: 19, avgPrecipitationInches: 0.5, rainyDays: 3, sunnyDays: 22 },
      { month: 'February', avgHighF: 51, avgLowF: 23, avgPrecipitationInches: 0.5, rainyDays: 3, sunnyDays: 20 },
      { month: 'March', avgHighF: 58, avgLowF: 28, avgPrecipitationInches: 0.6, rainyDays: 3, sunnyDays: 22 },
      { month: 'April', avgHighF: 66, avgLowF: 34, avgPrecipitationInches: 0.4, rainyDays: 2, sunnyDays: 24 },
      { month: 'May', avgHighF: 76, avgLowF: 43, avgPrecipitationInches: 0.4, rainyDays: 2, sunnyDays: 26 },
      { month: 'June', avgHighF: 87, avgLowF: 52, avgPrecipitationInches: 0.3, rainyDays: 2, sunnyDays: 27 },
      { month: 'July', avgHighF: 91, avgLowF: 60, avgPrecipitationInches: 1.2, rainyDays: 7, sunnyDays: 20 },
      { month: 'August', avgHighF: 88, avgLowF: 58, avgPrecipitationInches: 1.5, rainyDays: 8, sunnyDays: 19 },
      { month: 'September', avgHighF: 82, avgLowF: 50, avgPrecipitationInches: 1.0, rainyDays: 5, sunnyDays: 22 },
      { month: 'October', avgHighF: 68, avgLowF: 37, avgPrecipitationInches: 0.8, rainyDays: 4, sunnyDays: 23 },
      { month: 'November', avgHighF: 55, avgLowF: 26, avgPrecipitationInches: 0.5, rainyDays: 3, sunnyDays: 22 },
      { month: 'December', avgHighF: 45, avgLowF: 19, avgPrecipitationInches: 0.5, rainyDays: 3, sunnyDays: 21 },
    ],
  },
  {
    slug: 'theodore-roosevelt',
    monthly: [
      { month: 'January', avgHighF: 26, avgLowF: 3, avgPrecipitationInches: 0.4, rainyDays: 5, sunnyDays: 17 },
      { month: 'February', avgHighF: 32, avgLowF: 8, avgPrecipitationInches: 0.4, rainyDays: 5, sunnyDays: 16 },
      { month: 'March', avgHighF: 44, avgLowF: 20, avgPrecipitationInches: 0.7, rainyDays: 6, sunnyDays: 17 },
      { month: 'April', avgHighF: 57, avgLowF: 31, avgPrecipitationInches: 1.2, rainyDays: 7, sunnyDays: 16 },
      { month: 'May', avgHighF: 68, avgLowF: 42, avgPrecipitationInches: 2.2, rainyDays: 10, sunnyDays: 15 },
      { month: 'June', avgHighF: 78, avgLowF: 51, avgPrecipitationInches: 2.8, rainyDays: 10, sunnyDays: 16 },
      { month: 'July', avgHighF: 86, avgLowF: 57, avgPrecipitationInches: 1.8, rainyDays: 7, sunnyDays: 21 },
      { month: 'August', avgHighF: 87, avgLowF: 55, avgPrecipitationInches: 1.3, rainyDays: 6, sunnyDays: 22 },
      { month: 'September', avgHighF: 74, avgLowF: 44, avgPrecipitationInches: 1.2, rainyDays: 6, sunnyDays: 19 },
      { month: 'October', avgHighF: 58, avgLowF: 31, avgPrecipitationInches: 1.0, rainyDays: 5, sunnyDays: 19 },
      { month: 'November', avgHighF: 42, avgLowF: 18, avgPrecipitationInches: 0.5, rainyDays: 5, sunnyDays: 17 },
      { month: 'December', avgHighF: 29, avgLowF: 6, avgPrecipitationInches: 0.4, rainyDays: 5, sunnyDays: 16 },
    ],
  },
  {
    slug: 'white-sands',
    monthly: [
      { month: 'January', avgHighF: 57, avgLowF: 27, avgPrecipitationInches: 0.5, rainyDays: 3, sunnyDays: 24 },
      { month: 'February', avgHighF: 62, avgLowF: 31, avgPrecipitationInches: 0.4, rainyDays: 2, sunnyDays: 22 },
      { month: 'March', avgHighF: 70, avgLowF: 37, avgPrecipitationInches: 0.3, rainyDays: 2, sunnyDays: 25 },
      { month: 'April', avgHighF: 79, avgLowF: 45, avgPrecipitationInches: 0.3, rainyDays: 1, sunnyDays: 27 },
      { month: 'May', avgHighF: 88, avgLowF: 54, avgPrecipitationInches: 0.5, rainyDays: 2, sunnyDays: 27 },
      { month: 'June', avgHighF: 97, avgLowF: 63, avgPrecipitationInches: 0.7, rainyDays: 3, sunnyDays: 26 },
      { month: 'July', avgHighF: 96, avgLowF: 66, avgPrecipitationInches: 1.8, rainyDays: 8, sunnyDays: 19 },
      { month: 'August', avgHighF: 93, avgLowF: 64, avgPrecipitationInches: 2.0, rainyDays: 8, sunnyDays: 19 },
      { month: 'September', avgHighF: 87, avgLowF: 57, avgPrecipitationInches: 1.5, rainyDays: 6, sunnyDays: 21 },
      { month: 'October', avgHighF: 77, avgLowF: 45, avgPrecipitationInches: 1.0, rainyDays: 4, sunnyDays: 23 },
      { month: 'November', avgHighF: 65, avgLowF: 33, avgPrecipitationInches: 0.5, rainyDays: 2, sunnyDays: 24 },
      { month: 'December', avgHighF: 56, avgLowF: 27, avgPrecipitationInches: 0.6, rainyDays: 3, sunnyDays: 23 },
    ],
  },
  {
    slug: 'wind-cave',
    monthly: [
      { month: 'January', avgHighF: 36, avgLowF: 12, avgPrecipitationInches: 0.4, rainyDays: 5, sunnyDays: 18 },
      { month: 'February', avgHighF: 39, avgLowF: 15, avgPrecipitationInches: 0.5, rainyDays: 5, sunnyDays: 17 },
      { month: 'March', avgHighF: 47, avgLowF: 22, avgPrecipitationInches: 0.9, rainyDays: 7, sunnyDays: 16 },
      { month: 'April', avgHighF: 56, avgLowF: 30, avgPrecipitationInches: 1.8, rainyDays: 9, sunnyDays: 14 },
      { month: 'May', avgHighF: 66, avgLowF: 40, avgPrecipitationInches: 2.8, rainyDays: 12, sunnyDays: 13 },
      { month: 'June', avgHighF: 77, avgLowF: 50, avgPrecipitationInches: 2.6, rainyDays: 10, sunnyDays: 16 },
      { month: 'July', avgHighF: 85, avgLowF: 56, avgPrecipitationInches: 2.2, rainyDays: 8, sunnyDays: 20 },
      { month: 'August', avgHighF: 85, avgLowF: 54, avgPrecipitationInches: 1.6, rainyDays: 7, sunnyDays: 21 },
      { month: 'September', avgHighF: 74, avgLowF: 44, avgPrecipitationInches: 1.2, rainyDays: 6, sunnyDays: 19 },
      { month: 'October', avgHighF: 59, avgLowF: 32, avgPrecipitationInches: 1.3, rainyDays: 6, sunnyDays: 19 },
      { month: 'November', avgHighF: 45, avgLowF: 21, avgPrecipitationInches: 0.6, rainyDays: 5, sunnyDays: 17 },
      { month: 'December', avgHighF: 36, avgLowF: 13, avgPrecipitationInches: 0.4, rainyDays: 5, sunnyDays: 17 },
    ],
  },
  {
    slug: 'channel-islands',
    monthly: [
      { month: 'January', avgHighF: 63, avgLowF: 45, avgPrecipitationInches: 2.5, rainyDays: 6, sunnyDays: 18 },
      { month: 'February', avgHighF: 63, avgLowF: 46, avgPrecipitationInches: 2.8, rainyDays: 6, sunnyDays: 16 },
      { month: 'March', avgHighF: 64, avgLowF: 47, avgPrecipitationInches: 2.0, rainyDays: 5, sunnyDays: 18 },
      { month: 'April', avgHighF: 66, avgLowF: 49, avgPrecipitationInches: 0.8, rainyDays: 3, sunnyDays: 22 },
      { month: 'May', avgHighF: 67, avgLowF: 52, avgPrecipitationInches: 0.2, rainyDays: 1, sunnyDays: 25 },
      { month: 'June', avgHighF: 69, avgLowF: 55, avgPrecipitationInches: 0.1, rainyDays: 0, sunnyDays: 27 },
      { month: 'July', avgHighF: 72, avgLowF: 58, avgPrecipitationInches: 0.0, rainyDays: 0, sunnyDays: 30 },
      { month: 'August', avgHighF: 73, avgLowF: 59, avgPrecipitationInches: 0.0, rainyDays: 0, sunnyDays: 30 },
      { month: 'September', avgHighF: 73, avgLowF: 58, avgPrecipitationInches: 0.2, rainyDays: 1, sunnyDays: 27 },
      { month: 'October', avgHighF: 70, avgLowF: 54, avgPrecipitationInches: 0.6, rainyDays: 2, sunnyDays: 24 },
      { month: 'November', avgHighF: 67, avgLowF: 49, avgPrecipitationInches: 1.5, rainyDays: 4, sunnyDays: 20 },
      { month: 'December', avgHighF: 63, avgLowF: 45, avgPrecipitationInches: 2.2, rainyDays: 5, sunnyDays: 18 },
    ],
  },
  {
    slug: 'crater-lake',
    monthly: [
      { month: 'January', avgHighF: 33, avgLowF: 18, avgPrecipitationInches: 8.5, rainyDays: 17, sunnyDays: 5 },
      { month: 'February', avgHighF: 34, avgLowF: 18, avgPrecipitationInches: 6.8, rainyDays: 15, sunnyDays: 5 },
      { month: 'March', avgHighF: 36, avgLowF: 19, avgPrecipitationInches: 6.2, rainyDays: 15, sunnyDays: 7 },
      { month: 'April', avgHighF: 41, avgLowF: 23, avgPrecipitationInches: 3.8, rainyDays: 12, sunnyDays: 9 },
      { month: 'May', avgHighF: 50, avgLowF: 30, avgPrecipitationInches: 2.5, rainyDays: 10, sunnyDays: 13 },
      { month: 'June', avgHighF: 58, avgLowF: 36, avgPrecipitationInches: 1.6, rainyDays: 7, sunnyDays: 18 },
      { month: 'July', avgHighF: 68, avgLowF: 43, avgPrecipitationInches: 0.5, rainyDays: 2, sunnyDays: 26 },
      { month: 'August', avgHighF: 69, avgLowF: 43, avgPrecipitationInches: 0.6, rainyDays: 3, sunnyDays: 25 },
      { month: 'September', avgHighF: 62, avgLowF: 38, avgPrecipitationInches: 1.3, rainyDays: 5, sunnyDays: 21 },
      { month: 'October', avgHighF: 50, avgLowF: 30, avgPrecipitationInches: 3.5, rainyDays: 10, sunnyDays: 13 },
      { month: 'November', avgHighF: 37, avgLowF: 23, avgPrecipitationInches: 7.5, rainyDays: 16, sunnyDays: 5 },
      { month: 'December', avgHighF: 32, avgLowF: 18, avgPrecipitationInches: 8.8, rainyDays: 18, sunnyDays: 4 },
    ],
  },
  {
    slug: 'death-valley',
    monthly: [
      { month: 'January', avgHighF: 67, avgLowF: 40, avgPrecipitationInches: 0.3, rainyDays: 2, sunnyDays: 25 },
      { month: 'February', avgHighF: 73, avgLowF: 46, avgPrecipitationInches: 0.3, rainyDays: 2, sunnyDays: 23 },
      { month: 'March', avgHighF: 82, avgLowF: 54, avgPrecipitationInches: 0.2, rainyDays: 1, sunnyDays: 26 },
      { month: 'April', avgHighF: 92, avgLowF: 62, avgPrecipitationInches: 0.1, rainyDays: 1, sunnyDays: 28 },
      { month: 'May', avgHighF: 101, avgLowF: 72, avgPrecipitationInches: 0.1, rainyDays: 0, sunnyDays: 30 },
      { month: 'June', avgHighF: 111, avgLowF: 81, avgPrecipitationInches: 0.0, rainyDays: 0, sunnyDays: 30 },
      { month: 'July', avgHighF: 117, avgLowF: 88, avgPrecipitationInches: 0.1, rainyDays: 1, sunnyDays: 29 },
      { month: 'August', avgHighF: 115, avgLowF: 85, avgPrecipitationInches: 0.1, rainyDays: 1, sunnyDays: 29 },
      { month: 'September', avgHighF: 106, avgLowF: 75, avgPrecipitationInches: 0.2, rainyDays: 1, sunnyDays: 28 },
      { month: 'October', avgHighF: 92, avgLowF: 62, avgPrecipitationInches: 0.2, rainyDays: 1, sunnyDays: 27 },
      { month: 'November', avgHighF: 76, avgLowF: 48, avgPrecipitationInches: 0.2, rainyDays: 1, sunnyDays: 26 },
      { month: 'December', avgHighF: 65, avgLowF: 39, avgPrecipitationInches: 0.3, rainyDays: 2, sunnyDays: 24 },
    ],
  },
  {
    slug: 'lassen-volcanic',
    monthly: [
      { month: 'January', avgHighF: 40, avgLowF: 20, avgPrecipitationInches: 6.8, rainyDays: 13, sunnyDays: 8 },
      { month: 'February', avgHighF: 42, avgLowF: 21, avgPrecipitationInches: 5.8, rainyDays: 12, sunnyDays: 8 },
      { month: 'March', avgHighF: 44, avgLowF: 22, avgPrecipitationInches: 5.5, rainyDays: 13, sunnyDays: 9 },
      { month: 'April', avgHighF: 50, avgLowF: 26, avgPrecipitationInches: 3.2, rainyDays: 9, sunnyDays: 13 },
      { month: 'May', avgHighF: 59, avgLowF: 33, avgPrecipitationInches: 1.8, rainyDays: 7, sunnyDays: 18 },
      { month: 'June', avgHighF: 69, avgLowF: 40, avgPrecipitationInches: 0.8, rainyDays: 3, sunnyDays: 24 },
      { month: 'July', avgHighF: 80, avgLowF: 47, avgPrecipitationInches: 0.3, rainyDays: 1, sunnyDays: 28 },
      { month: 'August', avgHighF: 79, avgLowF: 46, avgPrecipitationInches: 0.3, rainyDays: 1, sunnyDays: 28 },
      { month: 'September', avgHighF: 72, avgLowF: 41, avgPrecipitationInches: 0.8, rainyDays: 3, sunnyDays: 24 },
      { month: 'October', avgHighF: 59, avgLowF: 33, avgPrecipitationInches: 2.8, rainyDays: 7, sunnyDays: 17 },
      { month: 'November', avgHighF: 45, avgLowF: 25, avgPrecipitationInches: 5.5, rainyDays: 12, sunnyDays: 9 },
      { month: 'December', avgHighF: 39, avgLowF: 20, avgPrecipitationInches: 6.5, rainyDays: 13, sunnyDays: 7 },
    ],
  },
  {
    slug: 'north-cascades',
    monthly: [
      { month: 'January', avgHighF: 36, avgLowF: 24, avgPrecipitationInches: 8.5, rainyDays: 18, sunnyDays: 4 },
      { month: 'February', avgHighF: 40, avgLowF: 25, avgPrecipitationInches: 6.2, rainyDays: 15, sunnyDays: 5 },
      { month: 'March', avgHighF: 44, avgLowF: 27, avgPrecipitationInches: 5.5, rainyDays: 15, sunnyDays: 7 },
      { month: 'April', avgHighF: 52, avgLowF: 32, avgPrecipitationInches: 4.0, rainyDays: 13, sunnyDays: 9 },
      { month: 'May', avgHighF: 60, avgLowF: 39, avgPrecipitationInches: 3.0, rainyDays: 11, sunnyDays: 13 },
      { month: 'June', avgHighF: 66, avgLowF: 45, avgPrecipitationInches: 2.5, rainyDays: 10, sunnyDays: 15 },
      { month: 'July', avgHighF: 73, avgLowF: 50, avgPrecipitationInches: 1.0, rainyDays: 4, sunnyDays: 23 },
      { month: 'August', avgHighF: 74, avgLowF: 50, avgPrecipitationInches: 1.2, rainyDays: 5, sunnyDays: 22 },
      { month: 'September', avgHighF: 66, avgLowF: 44, avgPrecipitationInches: 2.5, rainyDays: 8, sunnyDays: 16 },
      { month: 'October', avgHighF: 52, avgLowF: 35, avgPrecipitationInches: 5.5, rainyDays: 14, sunnyDays: 8 },
      { month: 'November', avgHighF: 40, avgLowF: 28, avgPrecipitationInches: 8.0, rainyDays: 18, sunnyDays: 4 },
      { month: 'December', avgHighF: 34, avgLowF: 23, avgPrecipitationInches: 9.0, rainyDays: 19, sunnyDays: 3 },
    ],
  },
  {
    slug: 'pinnacles',
    monthly: [
      { month: 'January', avgHighF: 58, avgLowF: 37, avgPrecipitationInches: 3.2, rainyDays: 8, sunnyDays: 15 },
      { month: 'February', avgHighF: 62, avgLowF: 39, avgPrecipitationInches: 3.0, rainyDays: 7, sunnyDays: 14 },
      { month: 'March', avgHighF: 66, avgLowF: 41, avgPrecipitationInches: 2.5, rainyDays: 7, sunnyDays: 16 },
      { month: 'April', avgHighF: 72, avgLowF: 44, avgPrecipitationInches: 1.0, rainyDays: 4, sunnyDays: 22 },
      { month: 'May', avgHighF: 81, avgLowF: 49, avgPrecipitationInches: 0.3, rainyDays: 1, sunnyDays: 27 },
      { month: 'June', avgHighF: 90, avgLowF: 55, avgPrecipitationInches: 0.1, rainyDays: 0, sunnyDays: 29 },
      { month: 'July', avgHighF: 96, avgLowF: 59, avgPrecipitationInches: 0.0, rainyDays: 0, sunnyDays: 31 },
      { month: 'August', avgHighF: 95, avgLowF: 58, avgPrecipitationInches: 0.0, rainyDays: 0, sunnyDays: 31 },
      { month: 'September', avgHighF: 90, avgLowF: 54, avgPrecipitationInches: 0.2, rainyDays: 1, sunnyDays: 28 },
      { month: 'October', avgHighF: 79, avgLowF: 47, avgPrecipitationInches: 0.7, rainyDays: 3, sunnyDays: 24 },
      { month: 'November', avgHighF: 66, avgLowF: 40, avgPrecipitationInches: 1.8, rainyDays: 5, sunnyDays: 19 },
      { month: 'December', avgHighF: 57, avgLowF: 36, avgPrecipitationInches: 2.8, rainyDays: 7, sunnyDays: 16 },
    ],
  },
  {
    slug: 'redwood',
    monthly: [
      { month: 'January', avgHighF: 54, avgLowF: 40, avgPrecipitationInches: 8.5, rainyDays: 16, sunnyDays: 6 },
      { month: 'February', avgHighF: 55, avgLowF: 40, avgPrecipitationInches: 7.2, rainyDays: 14, sunnyDays: 6 },
      { month: 'March', avgHighF: 55, avgLowF: 40, avgPrecipitationInches: 7.0, rainyDays: 15, sunnyDays: 7 },
      { month: 'April', avgHighF: 57, avgLowF: 41, avgPrecipitationInches: 4.0, rainyDays: 11, sunnyDays: 10 },
      { month: 'May', avgHighF: 59, avgLowF: 44, avgPrecipitationInches: 2.2, rainyDays: 8, sunnyDays: 14 },
      { month: 'June', avgHighF: 62, avgLowF: 48, avgPrecipitationInches: 0.8, rainyDays: 4, sunnyDays: 19 },
      { month: 'July', avgHighF: 63, avgLowF: 50, avgPrecipitationInches: 0.2, rainyDays: 1, sunnyDays: 23 },
      { month: 'August', avgHighF: 64, avgLowF: 50, avgPrecipitationInches: 0.4, rainyDays: 2, sunnyDays: 22 },
      { month: 'September', avgHighF: 64, avgLowF: 49, avgPrecipitationInches: 0.8, rainyDays: 3, sunnyDays: 20 },
      { month: 'October', avgHighF: 61, avgLowF: 46, avgPrecipitationInches: 3.5, rainyDays: 9, sunnyDays: 14 },
      { month: 'November', avgHighF: 56, avgLowF: 42, avgPrecipitationInches: 7.8, rainyDays: 15, sunnyDays: 6 },
      { month: 'December', avgHighF: 53, avgLowF: 39, avgPrecipitationInches: 9.0, rainyDays: 17, sunnyDays: 5 },
    ],
  },
  {
    slug: 'biscayne',
    monthly: [
      { month: 'January', avgHighF: 77, avgLowF: 61, avgPrecipitationInches: 1.8, rainyDays: 6, sunnyDays: 20 },
      { month: 'February', avgHighF: 79, avgLowF: 62, avgPrecipitationInches: 1.6, rainyDays: 5, sunnyDays: 20 },
      { month: 'March', avgHighF: 81, avgLowF: 65, avgPrecipitationInches: 2.0, rainyDays: 5, sunnyDays: 22 },
      { month: 'April', avgHighF: 84, avgLowF: 69, avgPrecipitationInches: 2.8, rainyDays: 6, sunnyDays: 22 },
      { month: 'May', avgHighF: 87, avgLowF: 73, avgPrecipitationInches: 5.5, rainyDays: 12, sunnyDays: 15 },
      { month: 'June', avgHighF: 89, avgLowF: 76, avgPrecipitationInches: 8.5, rainyDays: 16, sunnyDays: 11 },
      { month: 'July', avgHighF: 91, avgLowF: 77, avgPrecipitationInches: 6.5, rainyDays: 16, sunnyDays: 12 },
      { month: 'August', avgHighF: 91, avgLowF: 77, avgPrecipitationInches: 7.8, rainyDays: 17, sunnyDays: 11 },
      { month: 'September', avgHighF: 89, avgLowF: 76, avgPrecipitationInches: 8.2, rainyDays: 17, sunnyDays: 10 },
      { month: 'October', avgHighF: 86, avgLowF: 73, avgPrecipitationInches: 6.2, rainyDays: 13, sunnyDays: 14 },
      { month: 'November', avgHighF: 82, avgLowF: 68, avgPrecipitationInches: 2.8, rainyDays: 7, sunnyDays: 19 },
      { month: 'December', avgHighF: 78, avgLowF: 63, avgPrecipitationInches: 1.8, rainyDays: 5, sunnyDays: 21 },
    ],
  },
  {
    slug: 'congaree',
    monthly: [
      { month: 'January', avgHighF: 56, avgLowF: 33, avgPrecipitationInches: 3.8, rainyDays: 9, sunnyDays: 12 },
      { month: 'February', avgHighF: 60, avgLowF: 36, avgPrecipitationInches: 3.2, rainyDays: 8, sunnyDays: 12 },
      { month: 'March', avgHighF: 68, avgLowF: 43, avgPrecipitationInches: 4.0, rainyDays: 9, sunnyDays: 13 },
      { month: 'April', avgHighF: 76, avgLowF: 50, avgPrecipitationInches: 3.2, rainyDays: 7, sunnyDays: 16 },
      { month: 'May', avgHighF: 84, avgLowF: 59, avgPrecipitationInches: 3.5, rainyDays: 8, sunnyDays: 17 },
      { month: 'June', avgHighF: 90, avgLowF: 67, avgPrecipitationInches: 5.2, rainyDays: 11, sunnyDays: 14 },
      { month: 'July', avgHighF: 93, avgLowF: 71, avgPrecipitationInches: 5.8, rainyDays: 12, sunnyDays: 14 },
      { month: 'August', avgHighF: 91, avgLowF: 70, avgPrecipitationInches: 5.5, rainyDays: 12, sunnyDays: 14 },
      { month: 'September', avgHighF: 86, avgLowF: 64, avgPrecipitationInches: 4.2, rainyDays: 8, sunnyDays: 16 },
      { month: 'October', avgHighF: 76, avgLowF: 52, avgPrecipitationInches: 3.2, rainyDays: 6, sunnyDays: 19 },
      { month: 'November', avgHighF: 66, avgLowF: 42, avgPrecipitationInches: 3.0, rainyDays: 7, sunnyDays: 16 },
      { month: 'December', avgHighF: 57, avgLowF: 34, avgPrecipitationInches: 3.2, rainyDays: 8, sunnyDays: 13 },
    ],
  },
  {
    slug: 'cuyahoga-valley',
    monthly: [
      { month: 'January', avgHighF: 34, avgLowF: 20, avgPrecipitationInches: 2.5, rainyDays: 13, sunnyDays: 7 },
      { month: 'February', avgHighF: 37, avgLowF: 22, avgPrecipitationInches: 2.2, rainyDays: 11, sunnyDays: 7 },
      { month: 'March', avgHighF: 47, avgLowF: 29, avgPrecipitationInches: 2.8, rainyDays: 12, sunnyDays: 9 },
      { month: 'April', avgHighF: 59, avgLowF: 39, avgPrecipitationInches: 3.2, rainyDays: 12, sunnyDays: 10 },
      { month: 'May', avgHighF: 70, avgLowF: 49, avgPrecipitationInches: 3.8, rainyDays: 13, sunnyDays: 11 },
      { month: 'June', avgHighF: 79, avgLowF: 59, avgPrecipitationInches: 3.5, rainyDays: 11, sunnyDays: 14 },
      { month: 'July', avgHighF: 83, avgLowF: 63, avgPrecipitationInches: 3.6, rainyDays: 10, sunnyDays: 16 },
      { month: 'August', avgHighF: 81, avgLowF: 62, avgPrecipitationInches: 3.2, rainyDays: 9, sunnyDays: 16 },
      { month: 'September', avgHighF: 75, avgLowF: 55, avgPrecipitationInches: 3.0, rainyDays: 9, sunnyDays: 15 },
      { month: 'October', avgHighF: 62, avgLowF: 44, avgPrecipitationInches: 2.8, rainyDays: 10, sunnyDays: 13 },
      { month: 'November', avgHighF: 49, avgLowF: 35, avgPrecipitationInches: 3.2, rainyDays: 12, sunnyDays: 7 },
      { month: 'December', avgHighF: 38, avgLowF: 25, avgPrecipitationInches: 2.8, rainyDays: 13, sunnyDays: 6 },
    ],
  },
  {
    slug: 'dry-tortugas',
    monthly: [
      { month: 'January', avgHighF: 75, avgLowF: 65, avgPrecipitationInches: 1.5, rainyDays: 5, sunnyDays: 22 },
      { month: 'February', avgHighF: 76, avgLowF: 65, avgPrecipitationInches: 1.2, rainyDays: 4, sunnyDays: 22 },
      { month: 'March', avgHighF: 79, avgLowF: 68, avgPrecipitationInches: 1.3, rainyDays: 4, sunnyDays: 24 },
      { month: 'April', avgHighF: 82, avgLowF: 71, avgPrecipitationInches: 1.5, rainyDays: 4, sunnyDays: 24 },
      { month: 'May', avgHighF: 86, avgLowF: 76, avgPrecipitationInches: 3.5, rainyDays: 8, sunnyDays: 19 },
      { month: 'June', avgHighF: 89, avgLowF: 79, avgPrecipitationInches: 5.5, rainyDays: 12, sunnyDays: 15 },
      { month: 'July', avgHighF: 90, avgLowF: 80, avgPrecipitationInches: 4.8, rainyDays: 12, sunnyDays: 16 },
      { month: 'August', avgHighF: 90, avgLowF: 80, avgPrecipitationInches: 5.8, rainyDays: 14, sunnyDays: 14 },
      { month: 'September', avgHighF: 89, avgLowF: 79, avgPrecipitationInches: 6.5, rainyDays: 15, sunnyDays: 12 },
      { month: 'October', avgHighF: 85, avgLowF: 76, avgPrecipitationInches: 4.8, rainyDays: 11, sunnyDays: 16 },
      { month: 'November', avgHighF: 80, avgLowF: 71, avgPrecipitationInches: 2.2, rainyDays: 6, sunnyDays: 20 },
      { month: 'December', avgHighF: 77, avgLowF: 67, avgPrecipitationInches: 1.5, rainyDays: 5, sunnyDays: 22 },
    ],
  },
  {
    slug: 'hot-springs',
    monthly: [
      { month: 'January', avgHighF: 50, avgLowF: 30, avgPrecipitationInches: 3.5, rainyDays: 9, sunnyDays: 12 },
      { month: 'February', avgHighF: 55, avgLowF: 33, avgPrecipitationInches: 3.3, rainyDays: 9, sunnyDays: 11 },
      { month: 'March', avgHighF: 64, avgLowF: 41, avgPrecipitationInches: 4.5, rainyDays: 10, sunnyDays: 12 },
      { month: 'April', avgHighF: 73, avgLowF: 50, avgPrecipitationInches: 4.8, rainyDays: 9, sunnyDays: 14 },
      { month: 'May', avgHighF: 80, avgLowF: 59, avgPrecipitationInches: 5.2, rainyDays: 10, sunnyDays: 15 },
      { month: 'June', avgHighF: 88, avgLowF: 66, avgPrecipitationInches: 4.2, rainyDays: 9, sunnyDays: 17 },
      { month: 'July', avgHighF: 93, avgLowF: 71, avgPrecipitationInches: 3.5, rainyDays: 8, sunnyDays: 19 },
      { month: 'August', avgHighF: 93, avgLowF: 69, avgPrecipitationInches: 3.0, rainyDays: 7, sunnyDays: 20 },
      { month: 'September', avgHighF: 85, avgLowF: 62, avgPrecipitationInches: 3.8, rainyDays: 7, sunnyDays: 18 },
      { month: 'October', avgHighF: 74, avgLowF: 50, avgPrecipitationInches: 3.8, rainyDays: 8, sunnyDays: 17 },
      { month: 'November', avgHighF: 62, avgLowF: 40, avgPrecipitationInches: 4.2, rainyDays: 9, sunnyDays: 13 },
      { month: 'December', avgHighF: 52, avgLowF: 32, avgPrecipitationInches: 3.8, rainyDays: 9, sunnyDays: 12 },
    ],
  },
  {
    slug: 'indiana-dunes',
    monthly: [
      { month: 'January', avgHighF: 32, avgLowF: 18, avgPrecipitationInches: 2.0, rainyDays: 12, sunnyDays: 7 },
      { month: 'February', avgHighF: 36, avgLowF: 21, avgPrecipitationInches: 1.8, rainyDays: 10, sunnyDays: 8 },
      { month: 'March', avgHighF: 46, avgLowF: 29, avgPrecipitationInches: 2.5, rainyDays: 11, sunnyDays: 10 },
      { month: 'April', avgHighF: 58, avgLowF: 39, avgPrecipitationInches: 3.5, rainyDays: 12, sunnyDays: 10 },
      { month: 'May', avgHighF: 69, avgLowF: 49, avgPrecipitationInches: 3.8, rainyDays: 12, sunnyDays: 12 },
      { month: 'June', avgHighF: 79, avgLowF: 59, avgPrecipitationInches: 3.8, rainyDays: 10, sunnyDays: 15 },
      { month: 'July', avgHighF: 84, avgLowF: 65, avgPrecipitationInches: 3.8, rainyDays: 10, sunnyDays: 17 },
      { month: 'August', avgHighF: 82, avgLowF: 64, avgPrecipitationInches: 3.5, rainyDays: 9, sunnyDays: 17 },
      { month: 'September', avgHighF: 76, avgLowF: 56, avgPrecipitationInches: 3.2, rainyDays: 9, sunnyDays: 15 },
      { month: 'October', avgHighF: 63, avgLowF: 44, avgPrecipitationInches: 3.0, rainyDays: 10, sunnyDays: 13 },
      { month: 'November', avgHighF: 49, avgLowF: 34, avgPrecipitationInches: 3.2, rainyDays: 12, sunnyDays: 7 },
      { month: 'December', avgHighF: 36, avgLowF: 23, avgPrecipitationInches: 2.5, rainyDays: 12, sunnyDays: 6 },
    ],
  },
  {
    slug: 'mammoth-cave',
    monthly: [
      { month: 'January', avgHighF: 44, avgLowF: 25, avgPrecipitationInches: 3.5, rainyDays: 10, sunnyDays: 9 },
      { month: 'February', avgHighF: 49, avgLowF: 28, avgPrecipitationInches: 3.3, rainyDays: 10, sunnyDays: 9 },
      { month: 'March', avgHighF: 59, avgLowF: 36, avgPrecipitationInches: 4.2, rainyDays: 11, sunnyDays: 10 },
      { month: 'April', avgHighF: 69, avgLowF: 45, avgPrecipitationInches: 4.5, rainyDays: 11, sunnyDays: 12 },
      { month: 'May', avgHighF: 78, avgLowF: 55, avgPrecipitationInches: 5.0, rainyDays: 11, sunnyDays: 13 },
      { month: 'June', avgHighF: 86, avgLowF: 63, avgPrecipitationInches: 4.2, rainyDays: 10, sunnyDays: 15 },
      { month: 'July', avgHighF: 89, avgLowF: 67, avgPrecipitationInches: 4.5, rainyDays: 10, sunnyDays: 16 },
      { month: 'August', avgHighF: 89, avgLowF: 65, avgPrecipitationInches: 3.5, rainyDays: 8, sunnyDays: 18 },
      { month: 'September', avgHighF: 82, avgLowF: 58, avgPrecipitationInches: 3.2, rainyDays: 7, sunnyDays: 17 },
      { month: 'October', avgHighF: 70, avgLowF: 46, avgPrecipitationInches: 3.0, rainyDays: 8, sunnyDays: 16 },
      { month: 'November', avgHighF: 57, avgLowF: 36, avgPrecipitationInches: 3.8, rainyDays: 10, sunnyDays: 10 },
      { month: 'December', avgHighF: 46, avgLowF: 28, avgPrecipitationInches: 3.8, rainyDays: 11, sunnyDays: 8 },
    ],
  },
  {
    slug: 'new-river-gorge',
    monthly: [
      { month: 'January', avgHighF: 42, avgLowF: 22, avgPrecipitationInches: 3.2, rainyDays: 11, sunnyDays: 8 },
      { month: 'February', avgHighF: 46, avgLowF: 24, avgPrecipitationInches: 3.0, rainyDays: 10, sunnyDays: 8 },
      { month: 'March', avgHighF: 55, avgLowF: 31, avgPrecipitationInches: 3.8, rainyDays: 12, sunnyDays: 9 },
      { month: 'April', avgHighF: 65, avgLowF: 40, avgPrecipitationInches: 3.5, rainyDays: 11, sunnyDays: 11 },
      { month: 'May', avgHighF: 73, avgLowF: 49, avgPrecipitationInches: 4.2, rainyDays: 13, sunnyDays: 11 },
      { month: 'June', avgHighF: 80, avgLowF: 57, avgPrecipitationInches: 3.8, rainyDays: 11, sunnyDays: 14 },
      { month: 'July', avgHighF: 83, avgLowF: 62, avgPrecipitationInches: 4.5, rainyDays: 12, sunnyDays: 14 },
      { month: 'August', avgHighF: 82, avgLowF: 60, avgPrecipitationInches: 3.8, rainyDays: 10, sunnyDays: 15 },
      { month: 'September', avgHighF: 76, avgLowF: 53, avgPrecipitationInches: 3.2, rainyDays: 8, sunnyDays: 16 },
      { month: 'October', avgHighF: 65, avgLowF: 42, avgPrecipitationInches: 2.8, rainyDays: 8, sunnyDays: 15 },
      { month: 'November', avgHighF: 54, avgLowF: 33, avgPrecipitationInches: 3.2, rainyDays: 10, sunnyDays: 10 },
      { month: 'December', avgHighF: 44, avgLowF: 25, avgPrecipitationInches: 3.2, rainyDays: 11, sunnyDays: 8 },
    ],
  },
  {
    slug: 'shenandoah',
    monthly: [
      { month: 'January', avgHighF: 39, avgLowF: 19, avgPrecipitationInches: 2.8, rainyDays: 9, sunnyDays: 10 },
      { month: 'February', avgHighF: 42, avgLowF: 21, avgPrecipitationInches: 2.8, rainyDays: 9, sunnyDays: 10 },
      { month: 'March', avgHighF: 51, avgLowF: 28, avgPrecipitationInches: 3.5, rainyDays: 10, sunnyDays: 11 },
      { month: 'April', avgHighF: 62, avgLowF: 38, avgPrecipitationInches: 3.5, rainyDays: 10, sunnyDays: 12 },
      { month: 'May', avgHighF: 70, avgLowF: 47, avgPrecipitationInches: 4.2, rainyDays: 12, sunnyDays: 12 },
      { month: 'June', avgHighF: 77, avgLowF: 55, avgPrecipitationInches: 4.0, rainyDays: 11, sunnyDays: 14 },
      { month: 'July', avgHighF: 81, avgLowF: 60, avgPrecipitationInches: 4.2, rainyDays: 12, sunnyDays: 14 },
      { month: 'August', avgHighF: 80, avgLowF: 58, avgPrecipitationInches: 3.8, rainyDays: 10, sunnyDays: 15 },
      { month: 'September', avgHighF: 73, avgLowF: 52, avgPrecipitationInches: 3.5, rainyDays: 8, sunnyDays: 16 },
      { month: 'October', avgHighF: 62, avgLowF: 41, avgPrecipitationInches: 3.2, rainyDays: 8, sunnyDays: 15 },
      { month: 'November', avgHighF: 51, avgLowF: 31, avgPrecipitationInches: 3.0, rainyDays: 9, sunnyDays: 11 },
      { month: 'December', avgHighF: 42, avgLowF: 23, avgPrecipitationInches: 2.8, rainyDays: 9, sunnyDays: 10 },
    ],
  },
  {
    slug: 'gateway-arch',
    monthly: [
      { month: 'January', avgHighF: 40, avgLowF: 24, avgPrecipitationInches: 2.2, rainyDays: 8, sunnyDays: 12 },
      { month: 'February', avgHighF: 45, avgLowF: 28, avgPrecipitationInches: 2.2, rainyDays: 8, sunnyDays: 11 },
      { month: 'March', avgHighF: 56, avgLowF: 37, avgPrecipitationInches: 3.2, rainyDays: 10, sunnyDays: 12 },
      { month: 'April', avgHighF: 67, avgLowF: 47, avgPrecipitationInches: 3.8, rainyDays: 10, sunnyDays: 13 },
      { month: 'May', avgHighF: 76, avgLowF: 57, avgPrecipitationInches: 4.2, rainyDays: 11, sunnyDays: 14 },
      { month: 'June', avgHighF: 85, avgLowF: 66, avgPrecipitationInches: 3.8, rainyDays: 9, sunnyDays: 17 },
      { month: 'July', avgHighF: 90, avgLowF: 71, avgPrecipitationInches: 3.8, rainyDays: 8, sunnyDays: 19 },
      { month: 'August', avgHighF: 89, avgLowF: 69, avgPrecipitationInches: 3.0, rainyDays: 7, sunnyDays: 20 },
      { month: 'September', avgHighF: 81, avgLowF: 60, avgPrecipitationInches: 2.8, rainyDays: 7, sunnyDays: 18 },
      { month: 'October', avgHighF: 69, avgLowF: 49, avgPrecipitationInches: 3.0, rainyDays: 8, sunnyDays: 16 },
      { month: 'November', avgHighF: 55, avgLowF: 37, avgPrecipitationInches: 3.2, rainyDays: 9, sunnyDays: 12 },
      { month: 'December', avgHighF: 43, avgLowF: 27, avgPrecipitationInches: 2.5, rainyDays: 9, sunnyDays: 10 },
    ],
  },
  {
    slug: 'great-basin',
    monthly: [
      { month: 'January', avgHighF: 36, avgLowF: 14, avgPrecipitationInches: 0.8, rainyDays: 5, sunnyDays: 19 },
      { month: 'February', avgHighF: 39, avgLowF: 17, avgPrecipitationInches: 0.8, rainyDays: 5, sunnyDays: 17 },
      { month: 'March', avgHighF: 47, avgLowF: 23, avgPrecipitationInches: 1.0, rainyDays: 6, sunnyDays: 18 },
      { month: 'April', avgHighF: 55, avgLowF: 29, avgPrecipitationInches: 1.0, rainyDays: 6, sunnyDays: 18 },
      { month: 'May', avgHighF: 65, avgLowF: 37, avgPrecipitationInches: 1.2, rainyDays: 7, sunnyDays: 20 },
      { month: 'June', avgHighF: 76, avgLowF: 45, avgPrecipitationInches: 0.8, rainyDays: 4, sunnyDays: 24 },
      { month: 'July', avgHighF: 85, avgLowF: 53, avgPrecipitationInches: 0.8, rainyDays: 5, sunnyDays: 24 },
      { month: 'August', avgHighF: 83, avgLowF: 51, avgPrecipitationInches: 0.9, rainyDays: 5, sunnyDays: 23 },
      { month: 'September', avgHighF: 74, avgLowF: 42, avgPrecipitationInches: 0.8, rainyDays: 4, sunnyDays: 23 },
      { month: 'October', avgHighF: 60, avgLowF: 31, avgPrecipitationInches: 0.9, rainyDays: 5, sunnyDays: 21 },
      { month: 'November', avgHighF: 45, avgLowF: 21, avgPrecipitationInches: 0.8, rainyDays: 5, sunnyDays: 19 },
      { month: 'December', avgHighF: 35, avgLowF: 14, avgPrecipitationInches: 0.8, rainyDays: 5, sunnyDays: 18 },
    ],
  },
  {
    slug: 'isle-royale',
    monthly: [
      { month: 'January', avgHighF: 18, avgLowF: 2, avgPrecipitationInches: 1.5, rainyDays: 12, sunnyDays: 7 },
      { month: 'February', avgHighF: 20, avgLowF: 2, avgPrecipitationInches: 1.0, rainyDays: 9, sunnyDays: 8 },
      { month: 'March', avgHighF: 30, avgLowF: 12, avgPrecipitationInches: 1.5, rainyDays: 10, sunnyDays: 10 },
      { month: 'April', avgHighF: 42, avgLowF: 26, avgPrecipitationInches: 1.8, rainyDays: 10, sunnyDays: 11 },
      { month: 'May', avgHighF: 55, avgLowF: 36, avgPrecipitationInches: 2.5, rainyDays: 11, sunnyDays: 13 },
      { month: 'June', avgHighF: 65, avgLowF: 46, avgPrecipitationInches: 2.8, rainyDays: 11, sunnyDays: 14 },
      { month: 'July', avgHighF: 72, avgLowF: 53, avgPrecipitationInches: 2.8, rainyDays: 10, sunnyDays: 16 },
      { month: 'August', avgHighF: 71, avgLowF: 54, avgPrecipitationInches: 2.8, rainyDays: 10, sunnyDays: 16 },
      { month: 'September', avgHighF: 62, avgLowF: 46, avgPrecipitationInches: 3.0, rainyDays: 11, sunnyDays: 13 },
      { month: 'October', avgHighF: 49, avgLowF: 36, avgPrecipitationInches: 2.5, rainyDays: 11, sunnyDays: 10 },
      { month: 'November', avgHighF: 35, avgLowF: 22, avgPrecipitationInches: 2.2, rainyDays: 12, sunnyDays: 6 },
      { month: 'December', avgHighF: 23, avgLowF: 8, avgPrecipitationInches: 1.5, rainyDays: 12, sunnyDays: 6 },
    ],
  },
  {
    slug: 'voyageurs',
    monthly: [
      { month: 'January', avgHighF: 14, avgLowF: -7, avgPrecipitationInches: 0.8, rainyDays: 9, sunnyDays: 10 },
      { month: 'February', avgHighF: 20, avgLowF: -3, avgPrecipitationInches: 0.6, rainyDays: 7, sunnyDays: 11 },
      { month: 'March', avgHighF: 33, avgLowF: 10, avgPrecipitationInches: 1.0, rainyDays: 8, sunnyDays: 13 },
      { month: 'April', avgHighF: 49, avgLowF: 27, avgPrecipitationInches: 1.6, rainyDays: 8, sunnyDays: 13 },
      { month: 'May', avgHighF: 63, avgLowF: 39, avgPrecipitationInches: 2.8, rainyDays: 11, sunnyDays: 13 },
      { month: 'June', avgHighF: 73, avgLowF: 50, avgPrecipitationInches: 3.8, rainyDays: 12, sunnyDays: 14 },
      { month: 'July', avgHighF: 78, avgLowF: 55, avgPrecipitationInches: 3.5, rainyDays: 10, sunnyDays: 17 },
      { month: 'August', avgHighF: 76, avgLowF: 54, avgPrecipitationInches: 3.2, rainyDays: 10, sunnyDays: 17 },
      { month: 'September', avgHighF: 64, avgLowF: 44, avgPrecipitationInches: 3.2, rainyDays: 10, sunnyDays: 13 },
      { month: 'October', avgHighF: 49, avgLowF: 32, avgPrecipitationInches: 2.2, rainyDays: 9, sunnyDays: 12 },
      { month: 'November', avgHighF: 32, avgLowF: 16, avgPrecipitationInches: 1.2, rainyDays: 8, sunnyDays: 8 },
      { month: 'December', avgHighF: 17, avgLowF: -2, avgPrecipitationInches: 0.8, rainyDays: 9, sunnyDays: 8 },
    ],
  },
  {
    slug: 'hawaii-volcanoes',
    monthly: [
      { month: 'January', avgHighF: 67, avgLowF: 52, avgPrecipitationInches: 5.5, rainyDays: 14, sunnyDays: 12 },
      { month: 'February', avgHighF: 67, avgLowF: 51, avgPrecipitationInches: 4.8, rainyDays: 12, sunnyDays: 11 },
      { month: 'March', avgHighF: 68, avgLowF: 52, avgPrecipitationInches: 5.8, rainyDays: 15, sunnyDays: 10 },
      { month: 'April', avgHighF: 68, avgLowF: 53, avgPrecipitationInches: 5.2, rainyDays: 15, sunnyDays: 10 },
      { month: 'May', avgHighF: 70, avgLowF: 54, avgPrecipitationInches: 3.2, rainyDays: 11, sunnyDays: 14 },
      { month: 'June', avgHighF: 73, avgLowF: 57, avgPrecipitationInches: 2.5, rainyDays: 10, sunnyDays: 16 },
      { month: 'July', avgHighF: 74, avgLowF: 58, avgPrecipitationInches: 3.0, rainyDays: 12, sunnyDays: 15 },
      { month: 'August', avgHighF: 75, avgLowF: 59, avgPrecipitationInches: 3.2, rainyDays: 12, sunnyDays: 15 },
      { month: 'September', avgHighF: 75, avgLowF: 58, avgPrecipitationInches: 3.0, rainyDays: 11, sunnyDays: 15 },
      { month: 'October', avgHighF: 73, avgLowF: 57, avgPrecipitationInches: 4.0, rainyDays: 13, sunnyDays: 13 },
      { month: 'November', avgHighF: 70, avgLowF: 55, avgPrecipitationInches: 5.5, rainyDays: 14, sunnyDays: 11 },
      { month: 'December', avgHighF: 68, avgLowF: 53, avgPrecipitationInches: 5.8, rainyDays: 14, sunnyDays: 11 },
    ],
  },
  {
    slug: 'gates-of-the-arctic',
    monthly: [
      { month: 'January', avgHighF: -5, avgLowF: -25, avgPrecipitationInches: 0.4, rainyDays: 6, sunnyDays: 5 },
      { month: 'February', avgHighF: 0, avgLowF: -22, avgPrecipitationInches: 0.3, rainyDays: 5, sunnyDays: 7 },
      { month: 'March', avgHighF: 12, avgLowF: -12, avgPrecipitationInches: 0.3, rainyDays: 5, sunnyDays: 12 },
      { month: 'April', avgHighF: 28, avgLowF: 5, avgPrecipitationInches: 0.3, rainyDays: 4, sunnyDays: 15 },
      { month: 'May', avgHighF: 47, avgLowF: 26, avgPrecipitationInches: 0.5, rainyDays: 6, sunnyDays: 16 },
      { month: 'June', avgHighF: 62, avgLowF: 40, avgPrecipitationInches: 1.5, rainyDays: 10, sunnyDays: 14 },
      { month: 'July', avgHighF: 65, avgLowF: 45, avgPrecipitationInches: 2.2, rainyDays: 13, sunnyDays: 11 },
      { month: 'August', avgHighF: 58, avgLowF: 40, avgPrecipitationInches: 2.0, rainyDays: 13, sunnyDays: 10 },
      { month: 'September', avgHighF: 44, avgLowF: 28, avgPrecipitationInches: 1.2, rainyDays: 10, sunnyDays: 10 },
      { month: 'October', avgHighF: 22, avgLowF: 5, avgPrecipitationInches: 0.6, rainyDays: 8, sunnyDays: 9 },
      { month: 'November', avgHighF: 5, avgLowF: -14, avgPrecipitationInches: 0.5, rainyDays: 6, sunnyDays: 5 },
      { month: 'December', avgHighF: -5, avgLowF: -24, avgPrecipitationInches: 0.4, rainyDays: 6, sunnyDays: 4 },
    ],
  },
  {
    slug: 'glacier-bay',
    monthly: [
      { month: 'January', avgHighF: 32, avgLowF: 22, avgPrecipitationInches: 5.5, rainyDays: 17, sunnyDays: 4 },
      { month: 'February', avgHighF: 35, avgLowF: 24, avgPrecipitationInches: 4.5, rainyDays: 15, sunnyDays: 5 },
      { month: 'March', avgHighF: 38, avgLowF: 26, avgPrecipitationInches: 4.0, rainyDays: 15, sunnyDays: 6 },
      { month: 'April', avgHighF: 45, avgLowF: 32, avgPrecipitationInches: 3.5, rainyDays: 14, sunnyDays: 8 },
      { month: 'May', avgHighF: 53, avgLowF: 38, avgPrecipitationInches: 3.5, rainyDays: 14, sunnyDays: 10 },
      { month: 'June', avgHighF: 59, avgLowF: 44, avgPrecipitationInches: 3.0, rainyDays: 14, sunnyDays: 10 },
      { month: 'July', avgHighF: 62, avgLowF: 48, avgPrecipitationInches: 4.2, rainyDays: 16, sunnyDays: 8 },
      { month: 'August', avgHighF: 61, avgLowF: 47, avgPrecipitationInches: 5.5, rainyDays: 18, sunnyDays: 6 },
      { month: 'September', avgHighF: 55, avgLowF: 42, avgPrecipitationInches: 6.8, rainyDays: 19, sunnyDays: 5 },
      { month: 'October', avgHighF: 46, avgLowF: 35, avgPrecipitationInches: 7.5, rainyDays: 20, sunnyDays: 4 },
      { month: 'November', avgHighF: 37, avgLowF: 27, avgPrecipitationInches: 6.2, rainyDays: 18, sunnyDays: 3 },
      { month: 'December', avgHighF: 33, avgLowF: 23, avgPrecipitationInches: 5.8, rainyDays: 17, sunnyDays: 3 },
    ],
  },
  {
    slug: 'katmai',
    monthly: [
      { month: 'January', avgHighF: 28, avgLowF: 14, avgPrecipitationInches: 2.8, rainyDays: 14, sunnyDays: 5 },
      { month: 'February', avgHighF: 30, avgLowF: 16, avgPrecipitationInches: 2.5, rainyDays: 12, sunnyDays: 6 },
      { month: 'March', avgHighF: 33, avgLowF: 18, avgPrecipitationInches: 2.2, rainyDays: 12, sunnyDays: 8 },
      { month: 'April', avgHighF: 40, avgLowF: 26, avgPrecipitationInches: 2.0, rainyDays: 11, sunnyDays: 10 },
      { month: 'May', avgHighF: 50, avgLowF: 34, avgPrecipitationInches: 2.5, rainyDays: 13, sunnyDays: 10 },
      { month: 'June', avgHighF: 58, avgLowF: 42, avgPrecipitationInches: 2.5, rainyDays: 13, sunnyDays: 10 },
      { month: 'July', avgHighF: 62, avgLowF: 47, avgPrecipitationInches: 3.0, rainyDays: 15, sunnyDays: 9 },
      { month: 'August', avgHighF: 60, avgLowF: 46, avgPrecipitationInches: 4.0, rainyDays: 16, sunnyDays: 7 },
      { month: 'September', avgHighF: 54, avgLowF: 40, avgPrecipitationInches: 4.5, rainyDays: 17, sunnyDays: 6 },
      { month: 'October', avgHighF: 42, avgLowF: 30, avgPrecipitationInches: 3.8, rainyDays: 16, sunnyDays: 5 },
      { month: 'November', avgHighF: 33, avgLowF: 20, avgPrecipitationInches: 3.2, rainyDays: 15, sunnyDays: 4 },
      { month: 'December', avgHighF: 29, avgLowF: 16, avgPrecipitationInches: 3.0, rainyDays: 15, sunnyDays: 4 },
    ],
  },
  {
    slug: 'kenai-fjords',
    monthly: [
      { month: 'January', avgHighF: 27, avgLowF: 14, avgPrecipitationInches: 3.0, rainyDays: 14, sunnyDays: 5 },
      { month: 'February', avgHighF: 30, avgLowF: 17, avgPrecipitationInches: 2.5, rainyDays: 12, sunnyDays: 6 },
      { month: 'March', avgHighF: 34, avgLowF: 19, avgPrecipitationInches: 2.2, rainyDays: 12, sunnyDays: 8 },
      { month: 'April', avgHighF: 42, avgLowF: 28, avgPrecipitationInches: 2.0, rainyDays: 11, sunnyDays: 10 },
      { month: 'May', avgHighF: 51, avgLowF: 36, avgPrecipitationInches: 2.2, rainyDays: 12, sunnyDays: 11 },
      { month: 'June', avgHighF: 58, avgLowF: 43, avgPrecipitationInches: 2.0, rainyDays: 12, sunnyDays: 12 },
      { month: 'July', avgHighF: 62, avgLowF: 48, avgPrecipitationInches: 2.8, rainyDays: 14, sunnyDays: 10 },
      { month: 'August', avgHighF: 61, avgLowF: 47, avgPrecipitationInches: 4.0, rainyDays: 16, sunnyDays: 8 },
      { month: 'September', avgHighF: 55, avgLowF: 41, avgPrecipitationInches: 5.0, rainyDays: 17, sunnyDays: 6 },
      { month: 'October', avgHighF: 43, avgLowF: 31, avgPrecipitationInches: 4.5, rainyDays: 16, sunnyDays: 5 },
      { month: 'November', avgHighF: 33, avgLowF: 21, avgPrecipitationInches: 3.5, rainyDays: 15, sunnyDays: 4 },
      { month: 'December', avgHighF: 28, avgLowF: 16, avgPrecipitationInches: 3.2, rainyDays: 15, sunnyDays: 4 },
    ],
  },
  {
    slug: 'kobuk-valley',
    monthly: [
      { month: 'January', avgHighF: -5, avgLowF: -22, avgPrecipitationInches: 0.5, rainyDays: 6, sunnyDays: 4 },
      { month: 'February', avgHighF: 0, avgLowF: -18, avgPrecipitationInches: 0.4, rainyDays: 5, sunnyDays: 7 },
      { month: 'March', avgHighF: 14, avgLowF: -8, avgPrecipitationInches: 0.3, rainyDays: 4, sunnyDays: 14 },
      { month: 'April', avgHighF: 28, avgLowF: 7, avgPrecipitationInches: 0.3, rainyDays: 4, sunnyDays: 16 },
      { month: 'May', avgHighF: 48, avgLowF: 28, avgPrecipitationInches: 0.5, rainyDays: 5, sunnyDays: 18 },
      { month: 'June', avgHighF: 64, avgLowF: 42, avgPrecipitationInches: 1.2, rainyDays: 9, sunnyDays: 16 },
      { month: 'July', avgHighF: 68, avgLowF: 48, avgPrecipitationInches: 2.0, rainyDays: 12, sunnyDays: 12 },
      { month: 'August', avgHighF: 62, avgLowF: 43, avgPrecipitationInches: 2.2, rainyDays: 13, sunnyDays: 10 },
      { month: 'September', avgHighF: 48, avgLowF: 32, avgPrecipitationInches: 1.5, rainyDays: 10, sunnyDays: 10 },
      { month: 'October', avgHighF: 25, avgLowF: 10, avgPrecipitationInches: 0.8, rainyDays: 8, sunnyDays: 8 },
      { month: 'November', avgHighF: 8, avgLowF: -10, avgPrecipitationInches: 0.6, rainyDays: 7, sunnyDays: 4 },
      { month: 'December', avgHighF: -4, avgLowF: -20, avgPrecipitationInches: 0.5, rainyDays: 6, sunnyDays: 3 },
    ],
  },
  {
    slug: 'lake-clark',
    monthly: [
      { month: 'January', avgHighF: 22, avgLowF: 6, avgPrecipitationInches: 1.8, rainyDays: 12, sunnyDays: 6 },
      { month: 'February', avgHighF: 26, avgLowF: 10, avgPrecipitationInches: 1.5, rainyDays: 10, sunnyDays: 7 },
      { month: 'March', avgHighF: 32, avgLowF: 14, avgPrecipitationInches: 1.2, rainyDays: 10, sunnyDays: 10 },
      { month: 'April', avgHighF: 42, avgLowF: 25, avgPrecipitationInches: 1.2, rainyDays: 9, sunnyDays: 12 },
      { month: 'May', avgHighF: 53, avgLowF: 34, avgPrecipitationInches: 1.5, rainyDays: 10, sunnyDays: 13 },
      { month: 'June', avgHighF: 61, avgLowF: 43, avgPrecipitationInches: 1.8, rainyDays: 11, sunnyDays: 13 },
      { month: 'July', avgHighF: 63, avgLowF: 48, avgPrecipitationInches: 2.8, rainyDays: 14, sunnyDays: 10 },
      { month: 'August', avgHighF: 61, avgLowF: 46, avgPrecipitationInches: 3.2, rainyDays: 15, sunnyDays: 8 },
      { month: 'September', avgHighF: 54, avgLowF: 38, avgPrecipitationInches: 3.0, rainyDays: 15, sunnyDays: 7 },
      { month: 'October', avgHighF: 40, avgLowF: 26, avgPrecipitationInches: 2.5, rainyDays: 14, sunnyDays: 6 },
      { month: 'November', avgHighF: 28, avgLowF: 14, avgPrecipitationInches: 2.0, rainyDays: 13, sunnyDays: 5 },
      { month: 'December', avgHighF: 23, avgLowF: 8, avgPrecipitationInches: 2.0, rainyDays: 13, sunnyDays: 4 },
    ],
  },
  {
    slug: 'wrangell-st-elias',
    monthly: [
      { month: 'January', avgHighF: 10, avgLowF: -10, avgPrecipitationInches: 0.8, rainyDays: 8, sunnyDays: 9 },
      { month: 'February', avgHighF: 16, avgLowF: -6, avgPrecipitationInches: 0.6, rainyDays: 6, sunnyDays: 11 },
      { month: 'March', avgHighF: 26, avgLowF: 0, avgPrecipitationInches: 0.5, rainyDays: 5, sunnyDays: 15 },
      { month: 'April', avgHighF: 40, avgLowF: 18, avgPrecipitationInches: 0.5, rainyDays: 5, sunnyDays: 16 },
      { month: 'May', avgHighF: 55, avgLowF: 32, avgPrecipitationInches: 1.0, rainyDays: 8, sunnyDays: 15 },
      { month: 'June', avgHighF: 65, avgLowF: 42, avgPrecipitationInches: 2.0, rainyDays: 12, sunnyDays: 13 },
      { month: 'July', avgHighF: 68, avgLowF: 47, avgPrecipitationInches: 2.5, rainyDays: 13, sunnyDays: 12 },
      { month: 'August', avgHighF: 63, avgLowF: 43, avgPrecipitationInches: 2.5, rainyDays: 14, sunnyDays: 10 },
      { month: 'September', avgHighF: 52, avgLowF: 33, avgPrecipitationInches: 2.0, rainyDays: 12, sunnyDays: 10 },
      { month: 'October', avgHighF: 33, avgLowF: 16, avgPrecipitationInches: 1.2, rainyDays: 10, sunnyDays: 10 },
      { month: 'November', avgHighF: 16, avgLowF: -2, avgPrecipitationInches: 1.0, rainyDays: 9, sunnyDays: 7 },
      { month: 'December', avgHighF: 10, avgLowF: -10, avgPrecipitationInches: 0.8, rainyDays: 8, sunnyDays: 7 },
    ],
  },
  {
    slug: 'virgin-islands',
    monthly: [
      { month: 'January', avgHighF: 85, avgLowF: 73, avgPrecipitationInches: 2.5, rainyDays: 10, sunnyDays: 17 },
      { month: 'February', avgHighF: 85, avgLowF: 73, avgPrecipitationInches: 1.8, rainyDays: 8, sunnyDays: 18 },
      { month: 'March', avgHighF: 86, avgLowF: 73, avgPrecipitationInches: 1.5, rainyDays: 7, sunnyDays: 20 },
      { month: 'April', avgHighF: 87, avgLowF: 74, avgPrecipitationInches: 2.2, rainyDays: 8, sunnyDays: 19 },
      { month: 'May', avgHighF: 88, avgLowF: 76, avgPrecipitationInches: 3.0, rainyDays: 10, sunnyDays: 17 },
      { month: 'June', avgHighF: 89, avgLowF: 78, avgPrecipitationInches: 2.5, rainyDays: 9, sunnyDays: 18 },
      { month: 'July', avgHighF: 90, avgLowF: 78, avgPrecipitationInches: 2.8, rainyDays: 10, sunnyDays: 18 },
      { month: 'August', avgHighF: 90, avgLowF: 78, avgPrecipitationInches: 3.5, rainyDays: 12, sunnyDays: 16 },
      { month: 'September', avgHighF: 89, avgLowF: 77, avgPrecipitationInches: 5.0, rainyDays: 14, sunnyDays: 13 },
      { month: 'October', avgHighF: 88, avgLowF: 76, avgPrecipitationInches: 5.2, rainyDays: 14, sunnyDays: 13 },
      { month: 'November', avgHighF: 87, avgLowF: 75, avgPrecipitationInches: 5.5, rainyDays: 14, sunnyDays: 13 },
      { month: 'December', avgHighF: 86, avgLowF: 74, avgPrecipitationInches: 3.2, rainyDays: 12, sunnyDays: 16 },
    ],
  },
  {
    slug: 'american-samoa',
    monthly: [
      { month: 'January', avgHighF: 87, avgLowF: 77, avgPrecipitationInches: 10.5, rainyDays: 20, sunnyDays: 8 },
      { month: 'February', avgHighF: 87, avgLowF: 77, avgPrecipitationInches: 10.8, rainyDays: 19, sunnyDays: 7 },
      { month: 'March', avgHighF: 87, avgLowF: 77, avgPrecipitationInches: 10.2, rainyDays: 19, sunnyDays: 8 },
      { month: 'April', avgHighF: 87, avgLowF: 77, avgPrecipitationInches: 7.5, rainyDays: 16, sunnyDays: 10 },
      { month: 'May', avgHighF: 86, avgLowF: 76, avgPrecipitationInches: 5.5, rainyDays: 13, sunnyDays: 13 },
      { month: 'June', avgHighF: 85, avgLowF: 75, avgPrecipitationInches: 4.0, rainyDays: 10, sunnyDays: 16 },
      { month: 'July', avgHighF: 84, avgLowF: 74, avgPrecipitationInches: 3.5, rainyDays: 9, sunnyDays: 17 },
      { month: 'August', avgHighF: 85, avgLowF: 74, avgPrecipitationInches: 3.8, rainyDays: 9, sunnyDays: 17 },
      { month: 'September', avgHighF: 85, avgLowF: 75, avgPrecipitationInches: 4.8, rainyDays: 12, sunnyDays: 14 },
      { month: 'October', avgHighF: 86, avgLowF: 76, avgPrecipitationInches: 6.8, rainyDays: 15, sunnyDays: 12 },
      { month: 'November', avgHighF: 87, avgLowF: 77, avgPrecipitationInches: 8.5, rainyDays: 17, sunnyDays: 9 },
      { month: 'December', avgHighF: 87, avgLowF: 77, avgPrecipitationInches: 10.0, rainyDays: 19, sunnyDays: 8 },
    ],
  },
]

export function getParkWeatherBySlug(slug: string): ParkWeather | undefined {
  return parkWeatherData.find((w) => w.slug === slug)
}
